### ISSUE TITLE
tcpip::socketException :error while running run_example in artery directory

### ISSUE THREAD

**Issue by palash1794** [riebl/artery#100]
Hey I have completely installed the artery setup successfully with no errors.While I try to run run_example in artery directory with the following command **cmake --build build --target run_example**,the omnetpp simulation window pops up with the following error 

**tcpip::SocketException: tcpip::Socket::connect() @ connect: Connection refused -- in module (traci::Core) World.traci.core (id=5), at t=0s, event #1**

also it is showing sumo not found error on terminal
**Loading NED files from /home/palash/artery/artery/src/artery:  83
Loading NED files from /home/palash/artery/artery/src/traci:  16
Loading NED files from /home/palash/artery/artery/extern/veins/examples/veins:  1
Loading NED files from /home/palash/artery/artery/extern/veins/src/veins:  41
Loading NED files from /home/palash/artery/artery/extern/inet/src:  666
Loading NED files from /home/palash/artery/artery/extern/inet/examples:  174
Loading NED files from /home/palash/artery/artery/extern/inet/tutorials:  19
Loading NED files from /home/palash/artery/artery/extern/inet/showcases:  33

Loading images from './bitmaps': *: 0 
Loading images from './images': *: 0 
Loading images from '/home/palash/artery/artery/omnetpp-5.5.1/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 

sh: 1: sumo-gui: not found**
Please let me know my problem

**Comment by riebl** [comment]
Your problem is exactly what the error message tells: The program `sumo-gui` is not found.
Hence, Artery cannot launch SUMO for you and connect to its TCP socket.
Just install SUMO and make sure you can launch SUMO from your command line via sumo or sumo-gui.

**Comment by palash1794** [comment]
I have installed the sumo setup beforehand by downloading it's zip and then extracting it in a followed by cmake ../.. and make -j8. But artery setup is not detecting it.How can I download sumo 1.2.0 through command line in terminal.

**Comment by palash1794** [comment]
I have installed the sumo through terminal and now it is working,thanks!
After simulation how can I get the results, I have set ****.scalar-recording = true** & ****.vector-recording = true**.I mean in which directory am I supposed to look for them.

**Comment by riebl** [comment]
Results are usually recorded in a *results* folder relative to the employed *omnetpp.ini* file, i.e. *scenarios/artery/results* contains the scalar and vector files generated by the `run_example` target.
