### ISSUE TITLE
Make failure on make inet

### ISSUE THREAD

**Issue by mattherbert1** [riebl/artery#101]
Dear Riebl,

I tried to clone and build a fresh version of Artery but the make procedure failed with the errors below:

`In file included from inet/visualizer/scene/SceneOsgEarthVisualizer.cc:24:0:
./inet/visualizer/scene/SceneOsgEarthVisualizer.h:42:15: error: ‘GeoTransform’ in namespace ‘osgEarth’ does not name a type
     osgEarth::GeoTransform *geoTransform = nullptr;
               ^
inet/visualizer/scene/SceneOsgEarthVisualizer.cc: In member function ‘virtual void inet::visualizer::SceneOsgEarthVisualizer::initializeScene()’:
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:79:5: error: ‘geoTransform’ was not declared in this scope
     geoTransform = new osgEarth::GeoTransform();
     ^
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:79:24: error: expected type-specifier
     geoTransform = new osgEarth::GeoTransform();
                        ^
inet/visualizer/scene/SceneOsgEarthVisualizer.cc: In member function ‘virtual void inet::visualizer::SceneOsgEarthVisualizer::initializeLocator()’:
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:89:5: error: ‘geoTransform’ was not declared in this scope
     geoTransform->setPosition(osgEarth::GeoPoint(mapNode->getMapSRS()->getGeogr
     ^
Makefile:1360: recipe for target '../out/gcc-release/src/inet/visualizer/scene/SceneOsgEarthVisualizer.o' failed
`

Before make all I just called a `git clone --recurse-submodule https://github.com/riebl/artery.git` command. Is this issue in connection with the fact that the heads of the submodules are detached at certain commits?

Sincerly,
mattherbert1

**Comment by riebl** [comment]
I suppose the osgEarth installed on your system is incompatible with OMNeT++/INET. You can disable osgEarth in OMNeT++'s `configure.user` by setting `WITH_OSGEARTH=no`. Of course, you need to rebuild OMNeT++ afterwards to apply this change.

**Comment by riebl** [comment]
Added to http://artery.v2x-research.eu/questions-n-answers/#inet-dependency-does-not-compile-because-of-osgearth
