### ISSUE TITLE
Build INET failed 

### ISSUE THREAD

**Issue by yugushihuang** [riebl/artery#104]
When I execute make inet under the artery directory, it fails with error ->

‘GeoTransform’ in namespace ‘osgEarth’ does not name a type

**Comment by riebl** [comment]
I assume that your osgEarth with is not compatible with INET. If you are not intending to use any osgEarth visualization feature, you can safely disable it by editing the `configure.user` file in your OMNeT++ directory and rebuild it.

**Comment by yugushihuang** [comment]
@riebl 
Thanks for the suggestion, my osgearth version is (2.7.0+dfsg-2~xenial6) and I am using Ubuntu 16.04 LTS.

**Comment by riebl** [comment]
Ultimately, this is an INET issue, not Artery. Please seek advice from INET project.
