### ISSUE TITLE
get exchanges in PCAP file

### ISSUE THREAD

**Issue by cuita85202** [riebl/artery#105]
Hello,
I use Artery for simulations of communications between vehicles, It's super tool. First, thank you for that.
Question: I wonder if you can help me recover all the messages sent by the vehicles on a PCAP file.

Best regards
Cuita

**Comment by riebl** [comment]
Hi @cuita85202,

I think you can simply add `inet.common.packet.PcapRecorder` modules to vehicles, i.e. as submodule of `artery.inet.Car`. So far, I have never tried `PcapRecorder` before but this would be my first step.

Best regards,
Raphael

**Comment by xrispa-m** [comment]
@cuita85202 did you manage to use Artery with recording the pcap file?

**Comment by mfyuce** [comment]
It seems like 



        import inet.common.packet.PcapRecorder;

        .......


           submodules:
         ..........


                recorder: PcapRecorder{
                    parameters:
                        @pcapFile("./pcap");
                        @alwaysFlush(true);
                }




on files

        src/artery/envmod/Car.ned

        src/artery/envmod/PlainVehicle.ned

        src/artery/inet/Car.ned

        src/artery/inet/PlainVehicle.ned

        src/artery/inet/RSU.ned


At least saw the recorder on Omnet++ IDE, but still searching to output pcap files.

**Comment by maat-team** [comment]
Hello,

I have tried the solution suggested by @mfyuce, which involved adding a pcap recorder to all the *.ned files, but no pcap files were generated. I also tried configuring pcap recording in omnetpp.ini, but again, no pcap files were generated.

Do you have any recommendations, @mfyuce  @riebl  @cuita85202

Thank you in advance.
