### ISSUE TITLE
Limit the network area

### ISSUE THREAD

**Issue by danieladriano** [riebl/artery#106]
Hi, @riebl 

It's possible to limit the network area in an artery scenario?

I would like to use the Luxemburg Sumo Traffic Scenario by [Codeca et al (2017)](https://doi.org/10.1109/MITS.2017.2666585) as my sumo model and limit the network coverage/simulation area because of the size of it.

Regards,
Daniel

**Comment by riebl** [comment]
Sure, `traci.RegionOfInterestNodeManager` is your friend :-)
You can also find a usage example called "region_of_interest_vehicle_insertion" in *scenarios/artery*.

**Comment by danieladriano** [comment]
Hi, @riebl ,

Thanks :-D

Regards,
Daniel
