### ISSUE TITLE
Unit of Heading in VehicleDataProvider

### ISSUE THREAD

**Issue by kenog** [riebl/artery#108]
Hi,

I just have a quick question: In VehicleDataProvider.h, the function `heading()` is defined and the line has a comment saying "degree from north, clockwise". The implementation however looks more like radians and when I check them using `heading().value()` in my service, I also only got what seemed to be radians. Is the comment misleading or am I just missing something?

Cheers
Keno

**Comment by riebl** [comment]
Hi Keno,

you are right that the stored raw value is in radian. Please avoid using the `value()` getter on quantity types. If you need to access the plain value and expect it to be of a certain unit, I recommend to divide the quantity by that unit.
For example, `double heading_deg = vdp.heading() / vanetza::units::degree;` should do the job.
All in all, I am not that happy with the present handling of units at all…

Best regards,
Raphael

**Comment by kenog** [comment]
Hi Raphael,

thank you very much for the prompt reply. I am afraid I have quite a lot of `value()`s in my code. I will revisit them.
However your provided suggestion does give me the following compiler error (using clang 9.0.1):
`error: no viable conversion from 'typename divide_typeof_helper<quantity<unit<list<dim<plane_angle_base_dimension, static_rational<1, 1> >, dimensionless_type>, homogeneous_system<list<meter_base_unit, list<scaled_base_unit<gram_base_unit, scale<10, static_rational<3> > >, list<second_base_unit, list<ampere_base_unit, list<kelvin_base_unit, list<mole_base_unit, list<candela_base_unit, list<radian_base_unit, list<steradian_base_unit, dimensionless_type> > > > > > > > > >, void>, double>, unit<list<dim<plane_angle_base_dimension, static_rational<1, 1> >, dimensionless_type>, homogeneous_system<list<degree_base_unit, dimensionless_type> > > >::type' (aka 'quantity<unit<boost::units::dimensionless_type, heterogeneous_system<heterogeneous_system_impl<boost::units::list<boost::units::heterogeneous_system_dim<boost::units::angle::degree_base_unit, boost::units::static_rational<-1, 1> >, boost::units::list<boost::units::heterogeneous_system_dim<boost::units::angle::radian_base_unit, boost::units::static_rational<1, 1> >, boost::units::dimensionless_type> >, boost::units::dimensionless_type, boost::units::dimensionless_type> > >, double>') to 'double'
        double currentHeadingDeg = vdp.heading() / vanetza::units::degree;
               ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
I am not very familiar with boost and therefore have a hard time understanding this mess of an error message. Can you see anything obvious?

Not sure if this issue is a good place to talk about it but do you have any specific plans towards a better way of handling units?

Best regards
Keno

**Comment by riebl** [comment]
A good example of boost::units getting in your way instead of being helpful…
The "trick" to divide by the respective unit works only if the original type has already the matching unit, i.e. it really only strips the unit but does not convert anything.
`double heading_deg = vanetza::units::GeoAngle { vdp.heading() } / vanetza::units::degree;` works, but is far away from being nice at all.
You may adapt something like the `round` template function I have written for `CaService` to access the raw values safely, though.

**Comment by kenog** [comment]
Okay thank you very much for the clarification and advice :) I will implement a function similar to your `round` then. Would it be helpful to have something like that `getValueInUnit()` or your `round()` globally available in, e.g., artery/utility or vanetza/units?

**Comment by riebl** [comment]
Yes, if such a function is used in more than one place, then I prefer to have `getValueInUnit` in artery/utility.

**Comment by riebl** [comment]
Closing this issue ticket. Feel free to open a PR when you are ready, @kenog.
