### ISSUE TITLE
Troubleshooting custom DEN use case [was: problem of priorities!]

### ISSUE THREAD

**Issue by koh-gl** [riebl/artery#110]
Hi,
During my project, I developed "UseCases" for the DenService, I wanted to assign priority for each of them using access category so I tried with "request.gn.traffic_class.map_tc_onto_profile (1); " in the createRequest () method but it doesn't work and that poses a problem, please direct me to the right solution.
As well, I have tried to develop I2V applications but I have not been able to do it.
Cordially.

**Comment by riebl** [comment]
Can you please give more details than a plain "it doesn't work"?
Setting the traffic class in data requests works and will ultimately be translated to a matching access category at MAC layer.
`request.gn.traffic_class.tc_id(0)` will be mapped to the highest priority AC_VO, for example.

**Comment by koh-gl** [comment]
Thank you for answering me and for your help.
Among the applications, I developed a "usecase" where the "causecode" is "HazardousLocation_ObstacleOnTheroad", and I wanted to identify an area where vehicles can exchange DENM on this case but the result of the number of packets exchanged is still at 0.
here is my code.

bool ObstacleOnTheRoad::checkObstacleOnTheRoad() const
{
    return mDenmMemory->count(CauseCode::HazardousLocation_ObstacleOnTheroad) >= 1;
}

bool ObstacleOnTheRoad::checkPosition() const
{
    using vanetza::units::GeoAngle;
    using boost::units::degree::degree;

    static const GeoAngle lat { 49.572400 * degree };
    static const GeoAngle lon { 11.031546 * degree };

    const auto& latSamples = mLatSampler.buffer();
    const auto& lonSamples = mLonSampler.buffer();

    bool fulfilled = false;
    
    if ((!latSamples.empty() && latSamples.latest().value == lat) && (!lonSamples.empty() && lonSamples.latest().value == lon)) {

        printf("%d Latitude \n",lat);
        fflush(stdout); 

        printf("%d Longitude \n",lon);
        fflush(stdout); }
    return fulfilled;
    

}

bool ObstacleOnTheRoad::checkConditions()
{
    const TriggeringCondition tc0 = std::bind(&ObstacleOnTheRoad::checkEgoDeceleration, this);
    const TriggeringCondition tc1 = std::bind(&ObstacleOnTheRoad::checkObstacleOnTheRoad, this);
    const TriggeringCondition tc2 = std::bind(&ObstacleOnTheRoad::checkPosition, this);

    return (tc0() && tc1() && tc2());
}


void ObstacleOnTheRoad::check()
{
    mVelocitySampler.feed(mVdp->speed(), mVdp->updated());
    mLatSampler.feed(mVdp->latitude(), mVdp->updated());
    mLonSampler.feed(mVdp->longitude(), mVdp->updated());
    
    if(checkConditions()){
    auto denm = createMessage();
    auto request = createRequest();
    mService->sendDenm(std::move(denm), request);
    eed = omnetpp::simTime() - FirstTimestamp;        
        numSentOR++; 
        printf("%d Sent OR \n",numSentOR);
}
}

void ObstacleOnTheRoad::indicate(const artery::DenmObject& denm)
{
    if (denm & CauseCode::HazardousLocation_ObstacleOnTheroad ) {
        const vanetza::asn1::Denm& asn1 = denm.asn1();
        numReceivedOR++;
        printf("%d Received OR \n",numReceivedOR);
        fflush(stdout); 
        totalBitsOR+=(denm.asn1().size())*8;
         }
}

**Comment by riebl** [comment]
What is the observed behaviour? Is `numSentOR` incremented, but `numReceivedOR` is not?
Please consider using OMNeT++'s logging mechanism instead of `printf`, see https://doc.omnetpp.org/omnetpp/api/group__Logging.html.

**Comment by koh-gl** [comment]
numSentOR and numReceivedOR are both always 0.
my goal is to indicate that such an area contains obstacles and I want to know the number of numSentOR and numReceivedOR when a vehicle checks the indicated area.

**Comment by riebl** [comment]
Your triggering conditions are never fulfilled:
- `checkPosition` always returns `false`
- `checkObstacleOnTheRoad` is only `true` if at least one matching warning has been received. Is some entity sending an appropriate warning at all?

**Comment by koh-gl** [comment]
I added the variable "fulfilled" to "true" but the result is still 0 :
if ((! latSamples.empty () && latSamples.latest (). value == lat) && (! lonSamples.empty () && lonSamples.latest (). value == lon)) {
         fulfilled = true; }
 else {
          fulfilled = false; }
return fulfilled; }

No, there is no entity sending.
I just defined "msg-> denm.situation-> eventType.causeCode = CauseCodeType_hazardousLocation_ObstacleOnTheRoad;" in the createMessage () method.

**Comment by riebl** [comment]
I suppose one of your `tcX` conditions is still not fulfilled. You may simply `return true` by `checkConditions()` to simplify your program for debugging purposes.

**Comment by koh-gl** [comment]
Hello,
I am sorry for the disarrangement, I have another question in the same context of the checking of the position.
can i use the "cover" function of the RegionsOfInteretst class? I just want to limit the area for one application (unlike to RegionOfInterestVehiclePolicy which manages all useCases application).
here is the modification of my code:
```
void ObstacleOnTheRoad::initialize(int stage)
{
    UseCase::initialize(stage);
    if (stage == 0){
    
        mDenmMemory = mService->getMemory();
        mVelocitySampler.setDuration(par("sampleDuration"));
        mVelocitySampler.setInterval(par("sampleInterval"));}


        numSentOR=0;
        numReceivedOR=0;
       
        mVehicleController = &mService->getFacilities().get_const<traci::VehicleController>();
    
        omnetpp::cXMLElement* regions = par("regionsOfInterest").xmlValue();
        if (regions) {
        traci::Boundary boundary { mVehicleController->getLiteAPI().simulation().getNetBoundary() };
        m_regions.initialize(*regions, boundary);
             poss = position_cast(boundary, mVdp->position());
    }
}

bool ObstacleOnTheRoad::checkPosition() const
{
    bool fulfilled = false;
	if(m_regions.cover(poss)){
              fulfilled = true; }

         else {
         	fulfilled= false; }
    return fulfilled ;
}
```
and I add to the configuration of veins of the omnetpp.ini file: 

> *.traci.nodes.regionsOfInterest = xmldoc("regions_of_interest.xml") .

**Comment by riebl** [comment]
Yes, you can use the `RegionOfInterest` class for this purpose though it has been originally written for the TraCI modules.
Please note that your code does not use the current position in `checkPosition` but only the position as it has been during initialisation.
Furthermore, you will need to add the `regionsOfInterest` parameter to your `ObstacleOnTheRoad.ned` and set this one instead of `*.traci.nodes.regionsOfInterest` (which is similar but unrelated to your use case).

**Comment by koh-gl** [comment]
I did `poss = position_cast (boundary, mVdp-> position ())`; in the initialization because when I declare it in the method "checkPosition ()", a problem occurs which the boundary variable is private in his contexte !
however I made the method `position_cast ()` because `cover ()` takes in parameter `const libsumo :: TraCIPosition&`  so I cannot put in parameter `mVdp-> position ()` !

**Comment by riebl** [comment]
I would add `traci::Boundary` as member variable of `ObstacleOnTheRoad`. Calling `position_cast(mBoundary, mVdp->position())` in `checkPosition` is no issue then.

**Comment by koh-gl** [comment]
Yes, I have already added it to `ObstacleOnTheRoad.h` but no result yet `numSentOR` still zero, the `checkPosition` has not been verified. Is there a problem with the `mVehicleController` or with the initialization of the region in your opinion?
I followed your advice, I added` xml regionsOfInterest = default (xml ("<regions />"));` to the ned file and at the omnetpp.ini level I modified `* .node [*]. appl.middleware.DEN.regionsOfInterest = xmldoc ("regions_of_interest.xml")`.

**Comment by riebl** [comment]
I think the region is not configured properly because there is no `regionsOfInterest` parameter for DEN service. Try `**.middleware.DEN.ObstacleOnTheRoad.regionsOfInterest = xmldoc("regions_of_interest.xml")` and verify parameter settings, e.g. run simulation with Qtenv and look at the settings in the module tree.

**Comment by koh-gl** [comment]
Thank you very much, it is going well.
