### ISSUE TITLE
I can't get all source code via git command.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [riebl/artery#111]
There are much inconvenience to get all source code via git command in China.I can't get a complete version of artery.Could you send a complete version of artery to my email include the ''extern" folder?
My email is 201921009024@mail.scut.edu.cn .

**Comment by riebl** [comment]
Do you know what is the actual problem? Is the git protocol causing trouble or is it "just" the connection to github servers in general?
So far,  I have seen no sense in creating releases of Artery on github, but these could be downloaded as ZIP archives from github then. I am not sure if these include submodules, however.

**Comment by Sheldon-Zhou1997** [comment]
It is the connection to github servers in China was limited by some policy.Thanks for sharing!
