### ISSUE TITLE
Artery build trouble

### ISSUE THREAD

**Issue by sofianedahmane** [riebl/artery#112]
Dears,
Dear @riebl
I am new in this,
I just downloaded artery zip file and its separated sub-modules and put them in extern directory.
I am using ubuntu 18.04, when I use cmake .., I got the following:
```
CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "Vanetza" with any
  of the following names:
    VanetzaConfig.cmake
    vanetza-config.cmake
  Add the installation prefix of "Vanetza" to CMAKE_PREFIX_PATH or set
  "Vanetza_DIR" to a directory containing one of the above files.  If
  "Vanetza" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
```
Could you plz help me!

**Comment by riebl** [comment]
Hi @sofianedahmane,

why do you download those repositories as zip files? This sounds very inconvenient to me.

You need to build Vanetza before Artery. The missing VanetzaConfig.cmake will be generated as part of Vanetza's build process. See http://artery.v2x-research.eu/install/#build-extern-components for detailed instructions.

**Comment by sofianedahmane** [comment]
Hi @riebl 
Thank you for the quick answer.
When I tried to build vanetza, I got:
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CryptoPP (missing: CryptoPP_INCLUDE_DIR CryptoPP_LIBRARY)
  (Required is at least version "5.6.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCryptoPP.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)

**Comment by riebl** [comment]
Please read Artery's build instructions carefully. It tells you which requirements need to get installed beforehand: http://artery.v2x-research.eu/install/#requirements

**Comment by sofianedahmane** [comment]
Well, the requirements are:
    C++ compiler with C++11 support (GNU GCC 4.9 or later or Clang)
------ I am using: c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    Boost (1.65.1 or later is recommended)
------ I am using: BOOST_LIB_VERSION "1_65_1"
    CMake 3.1 or later
------ I am using: cmake version 3.10.2
    OMNeT++ 5.4 or later
------ I am using: OMNeT++ 6.0
    Python 3
------ I am using: Python 3.7.3

I am using ubuntu 18.04 LTS.
What do you suggest sir?

**Comment by riebl** [comment]
But you have missed
-     GeographicLib 1.37 or later
-     Crypto++ 5.6 or later

**Comment by sofianedahmane** [comment]
Dear @riebl,
I just built vanetza correctly, thank you.
I am facing the following error with inet build:
---------
opp_msgtool: error in 1 file(s)
Makefile:1029: recipe for target 'inet/applications/dhcp/DHCPMessage_m.h' failed
make[1]: *** [inet/applications/dhcp/DHCPMessage_m.h] Error 1
make[1]: Leaving directory '/home/sofiane/omnetpp-6.0/samples/artery/extern/inet/src'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
---------
What to do plz?

**Comment by riebl** [comment]
Most likely, you have discovered an incompatibility of (yet unreleased) OMNeT++ 6.0 and INET 3.6. I recommend to stick with a 5.x release of OMNeT++. Version 5.6 works fine on my systems.

**Comment by sofianedahmane** [comment]
Dear @riebl,
I changed omnetpp to 5.6.
For inet, I just cloned it to my extern directory then make makefiles and make I got the following
inet/applications/packetdrill/PacketDrill.cc:1522:41: error: expected ')'
        printf("srs_number_streams = %" INT64_PRINTF_FORMAT "d\n", rs->s...
                                        ^
inet/applications/packetdrill/PacketDrill.cc:1522:15: note: to match this '('
        printf("srs_number_streams = %" INT64_PRINTF_FORMAT "d\n", rs->s...
              ^
inet/applications/packetdrill/PacketDrill.cc:1549:41: error: expected ')'
        printf("add streams assoc id=%" INT64_PRINTF_FORMAT "d\n", as->s...
                                        ^
inet/applications/packetdrill/PacketDrill.cc:1549:15: note: to match this '('
        printf("add streams assoc id=%" INT64_PRINTF_FORMAT "d\n", as->s...
              ^
2 errors generated.
I tried to fix them  putting PRId64 istead of INT64_PRINTF_FORMAT.
I got the following:
inet/applications/packetdrill/PacketDrillApp.cc:939:45: error: ordered
      comparison between pointer and zero ('PacketDrillExpression *' and 'int')
            if (expr_params->spp_hbinterval > 0)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
inet/applications/packetdrill/PacketDrillApp.cc:941:45: error: ordered
      comparison between pointer and zero ('PacketDrillExpression *' and 'int')
            if (expr_params->spp_pathmaxrxt > 0)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
2 errors generated.
===================
is it normal, sir?

**Comment by riebl** [comment]
No, this is not normal. I bet you have manually cloned an incompatible INET version. There is a reason why the Artery repository tracks those things as submodules in *extern*.

**Comment by sofianedahmane** [comment]
Well, should I clone this inet version:
https://github.com/inet-framework/inet.git
because it seems the working version!

**Comment by riebl** [comment]
Currently, Artery tracks the `artery-v3.6.7` branch of https://github.com/riebl/inet.git, i.e. a fork of the INET repository with some small bugfixes based on INET 3.6.7.
The `master` branch of the upstream INET repository is not suitable.
