### ISSUE TITLE
Record and display CA Object content

### ISSUE THREAD

**Issue by libertt1** [riebl/artery#114]
Hi,
I am new to Artery and OMNET and i am running your examples of CA Service use. I would like to know where and how i could record CA objects contents and add them to the logs (printing the CAM data while running the simulation).

**Comment by riebl** [comment]
Printing CAMs during simulation is rather unusual, however, `vanetza/facilities/cam_functions.hpp` contains a `print_indented` function you may use for this purpose.
For example, you can add `vanetza::facilities::print_indented(EV_INFO, *cam, "  ");` to CaService.cc at line 117 to print received CAMs.
OMNeT++ facilities are not suitable to record structured data, i.e. you can easily record reception times, byte lengths etc. of CAMs in an OMNeT++ output vector, but not the whole CAM.
If you only need to record a few CAM fields, I recommend to use OMNeT++'s `@statistic` feature. Artery's CA service emits `CaObject` signals for received and transmitted CAMs, to which you can attach statistics. See `record=vector(camStationId)` in CaService.ned for reference.

**Comment by riebl** [comment]
You can record any information representable as numeric value in an output vector. Going the `@statistic` way, you just need to add a NED function `camSpeed`, which returns the speed encoded in a `CaObject`. At the moment, two such NED functions (`camStationId` and `camGenerationDeltaTime`) are implemented in `CaObject.cc`. You may use them as a blueprints for your `camSpeed` function. The speed field of a CAM is accessible via (assuming `cam` is a `CaObject*` pointer): `cam->asn1()->cam.camParameters.highFrequencyContainer.choice.basicVehicleContainerHighFrequency.speed.speedValue;`
Yes, the speed field is deeply buried in the CAM structure…

Please note that not every CAM necessarily contains a `basicVehicleContainerHighFrequency`. You should check if `highFrequencyContainer.present == HighFrequencyContainer_PR_basicVehicleContainerHighFrequency` beforehand. If another type of high frequency container is present, e.g. if the station is actually a roadside unit, you may return a "not available" value such as -1.

**Comment by libertt1** [comment]
The CAM structure is where i got lost but it's clear now thanks.

**Comment by aintzel2** [comment]
> Printing CAMs during simulation is rather unusual, however, `vanetza/facilities/cam_functions.hpp` contains a `print_indented` function you may use for this purpose. For example, you can add `vanetza::facilities::print_indented(EV_INFO, *cam, " ");` to CaService.cc at line 117 to print received CAMs. OMNeT++ facilities are not suitable to record structured data, i.e. you can easily record reception times, byte lengths etc. of CAMs in an OMNeT++ output vector, but not the whole CAM. If you only need to record a few CAM fields, I recommend to use OMNeT++'s `@statistic` feature. Artery's CA service emits `CaObject` signals for received and transmitted CAMs, to which you can attach statistics. See `record=vector(camStationId)` in CaService.ned for reference.

Hi @riebl I try what you say for printing CAM messages and it works perfectly but how can I extract information from a received CAM? I want to extract the position information.

**Comment by riebl** [comment]
The position is in CAM's basic container, see its `referencePosition` field: `cam->asn1()->cam.camParameters.basicContainer.referencePosition`
Please open a new issue ticket if you face a specific question.
