### ISSUE TITLE
Parallel simulation

### ISSUE THREAD

**Issue by cuita85202** [riebl/artery#115]
Hey Riebl, 
I'm wondering how can I execute parallel simulations, knowing that I am using a huge network containing spread nodes. 
First question: how can I send messages only to the vehicles that within the range (700m) 
Second question: how can I make two different communications in two different places (parallel simulations).

can you help me with it? 
thank you

**Comment by riebl** [comment]
Hi @cuita85202,

unfortunately, it is not possible to run a single simulation in parallel. At the moment, you can only make use of multiple CPU cores by running multiple Artery instances in parallel, e.g. with different random seeds or as a parameter study.

You may explicitly limit the transmission range by setting the `rangeFilter` parameter of the RadioMedium module.
I don't quite understand your second question, though. What do you mean by "different communications"?

**Comment by cuita85202** [comment]
Thank you for your quick response. 

get the transmission limit by adding 
Radiomedium.rangefilter=... 
in Ned file?

I meant "parallel simulations" but you already answered.

I know it's not the matter of this issue but can you tell how can I specify Multiple CPU cores for a single simulation. 
I have 23 cores but OMNET++ uses just one at the time. I can't find where I can modify it in Ubuntu.

**Comment by riebl** [comment]
You can set the `rangeFilter` in omnetpp.ini

> *.radioMedium.rangeFilter = "communicationRange"
> *.radioMedium.mediumLimitCache.maxCommunicationRange = 700m

OMNeT++'s parallelisation capabilities are covered by its manual: https://doc.omnetpp.org/omnetpp/manual/#cha:parallel-exec
Again, this is not really useful for wireless networks with dynamically created modules.
