### ISSUE TITLE
Interfacing Artery and CARLA

### ISSUE THREAD

**Issue by libertt1** [riebl/artery#116]
Hi riebl, 
Our team is working with Artery and the CARLA Simulator. Here are some useful links concerning CARLA 
- Link to the CARLA website : https://carla.org/
- Link to the interfacing of SUMO and CARLA on its Git : https://github.com/carla-simulator/carla/tree/master/Co-Simulation/Sumo

We are trying to use Artery and CARLA simultanously. Do you know anyone who has done this before? 
CARLA has a python script that allows a co-simulation with SUMO, interacting with it via TraCI (Python API, both synchronous and asynchronous modes are possible).

We were wondering how hard it would be to get this simulator to run with Artery and add it to the TraCI Manager (since TraCI has multiple submodules).

We are still quite uncertain of how we should manage the synchronization of these three tools; as SUMO is the common node, we are wondering if SUMO could be the master of this synchronization. This means that both CARLA and Artery would synchronize their time-steps based on SUMO.
Is this the right approach? Or should we try to synchronize based on something else? 

Finally, on a slightly different note, CARLA uses a ROS Bridge to interface with ROS (to publish CARLA's data over ROS topics); do you know any method of doing the same for Artery? Does a ROS Bridge exist already for it?

Thank you for your help,

**Comment by riebl** [comment]
Hi @libertt1,

your plan sounds interesting! Though I have heard of CARLA before, I have never used it and am not aware of anyone combining Artery, CARLA, and SUMO.
I see no reason why it should not be possible to get them running cooperatively.

Usually, I keep OMNeT++ as master clock because its step length is variable and finer than SUMO's clock. If CARLA is attached to SUMO's clock, this should still work:
> OMNeT++ --triggers step--> SUMO --is time source of--> CARLA

As far as I have understood the SUMO/CARLA co-simulation, this approach requires also no changes to the existing architecture.

Please see our `ros` branch for some preliminary integration of Artery into the ROS ecosystem. It basically works but you need to launch it manually at the moment, i.e. fire up ROS master and then launch Artery. Currently, only GPS fixes are forwarded from Artery to ROS for demonstration. It should be quite easy to extend it, e.g. exposing ITS-G5/BTP as ROS service per vehicle.

**Comment by libertt1** [comment]
Thank you for your answer, we are soon going to investigate this interfacing. We'll let you know the advances as we might have questions about wisely managing the TraCI modules.

**Comment by libertt1** [comment]
Hi riebl,
 
We thought about how we would synchronize the tools and one possibility would be to launch SUMO with CARLA and then connect Artery to this SUMO instance. I guess I understood right that we can launch a simulation using SUMO with PosixLauncher or ConnectLauncher, would ConnectLauncher support what we are trying to do (I did not see any example using it)?
 
Thank you

**Comment by riebl** [comment]
Just set the `hostname` (defaults to localhost) and `port` of `ConnectLauncher` and it will connect to the specified SUMO endpoint. Our TraCI manager module uses `ConnectLauncher` by default, i.e. just remove the `*.traci.launcher.typename =  "PosixLauncher"` from your omnetpp.ini.

**Comment by libertt1** [comment]
Hi @riebl,

What I am doing now is trying to connect Carla and Artery to a SUMO instance that is independant of both launching mechanisms. To achieve that I specify the number of clients expected by SUMO and it waits for both to start but both Carla and Artery need to specify the client order as prerequisites via the TraCI setOrder() that I saw in TraCIAPI. My question is where should I call this function at launch and how should I point to the API at this time? I use the ConnectLauncher as you told me.

**Comment by riebl** [comment]
From your description I conclude that setOrder needs to called only once at the very beginning of the simulation. I suggest to add this call to `traci::Core::handleMessage` where also `checkVersion` and `syncTime` are called during connect event handling. Core has also the full TraCI API accessible via its `m_traci` member variable.

**Comment by libertt1** [comment]
Following your instructions, we successfully connected OMNeT to a distant SUMO and then connected CARLA to this instance of SUMO. We are now testing it with a concordant map to fit the 3D visualization as map are created separately.

**Comment by aniolm9** [comment]
Hi @libertt1,

We are also working in interfacing Artery and CARLA and I'm interested in your solution. Could you send me an e-mail to talk about it?

Thank you.
