### ISSUE TITLE
Intersection management service using CAM messages

### ISSUE THREAD

**Issue by libertt1** [riebl/artery#117]
Hi @riebl,

I am trying to create a service to manage an intersection with two vehicles going through it orthogonally at the same time. The two vehicles do not follow any priority rule and i would like to implement a basic service to avoid the collision using the CAM.

My questions are : Is there any similar work on an intersection management service using CAM? Does a right approach would be to override CAService and its trigger function to analyze the messages passed, do the calculations and react on the vehicles with TraCI? Or should I use a different service that is triggered on CA reception signal?

Thank you for your engagement

**Comment by riebl** [comment]
I suggest to create a separate service which is subscribing to the CA receive and transmit signals emitted by `CaService`. This way, you can intercept all CAMs but do not need to bother when and how they are created. You can then control the vehicle's behaviour in your service by calling appropriate TraCI commands. Access to the full TraCI API is possible via the `VehicleController` registered at `Facilities`.

**Comment by libertt1** [comment]
Alright, do you have any example of such a service using signals?

**Comment by riebl** [comment]
https://github.com/riebl/artery/blob/master/src/artery/application/ExampleService.cc subscribes to CAM receptions by its sibling CaService. You can cast the `cObject` of the signal handler to `CaObject`, which contains the whole CAM.

**Comment by Amir-Teshome** [comment]
Hello @riebl , 

is this the correct way to cast the `cObject` to `CaObject` 
`CaObject* ca = check_and_cast<CaObject*>(c_obj);` ? 
I'm getting `error: ‘check_and_cast’ was not declared in this scope` . This error seems from omnet++ but I couldn't figure it out.

I have imported CaObject.h in the ExampleService `#include  "artery/application/CaObject.h"`
Thank you for the help.

**Comment by libertt1** [comment]
Hi @Amir-Teshome,

I used dynamic_cast instead of check_and_cast and it worked fine.
`CaObject* ca = dynamic_cast<CaObject*>(c_obj);`

**Comment by libertt1** [comment]
Hi @riebl,

I'm working on my service to manage an intersection of two cars. My service now casts the CaObject received from the other vehicle and I get access to the current vehicle positions via the VehicleDataProvider but i would like to get the distance between the two vehicles using this data. Is there already a distance method for GeoPositions?

Thank you,

**Comment by riebl** [comment]
@Amir-Teshome `omnetpp::check_and_cast` is using `dynamic_cast` internally as well. You find this function in `#include <omnetpp/checkandcast.h>`, i.e. you have to include this header in your sources.

@libertt1 `vanetza::facilities::distance` calculates distance between two `ReferencePosition_t` from CAMs. This function is defined in `vanetza/facilities/cam_functions.hpp`.

**Comment by Amir-Teshome** [comment]
Hello @riebl 

I have an issue while using  the [ExamplaService](https://github.com/riebl/artery/blob/master/src/artery/application/ExampleService.cc ) , specifically the service seems not receiving the CAM signal emitted from CA service.  
My scenario: I have 3 vehicles with `CaService`s and a 4th node as a road side unit (RSU) with the `ExampleService`. I initialized the RSU following the `rsu_grid` example scenario. 

My RSUs.xml
```
<RSUs>
  <rsu id="gneJ5" positionX="500.84" positionY="0.0"/>
</RSUs>
```   
I'm using `network = artery.envmod.World` network and inside omnetpp.ini, I have
```
*.staticNodes.nodes = xmldoc("RSUs.xml")

*.rsu*.middleware.datetime = "2018-03-19 10:00:00"
*.rsu*.middleware.services = xmldoc("rsuservices.xml")
```
The `rsuservices.xml` contains 
```
<services>
	<service  type="artery.application.ExampleService">
		<listener  port="4711"  />
	</service>
</services>
```
I was trying to print something (just for debugging purpose) from `ExampleService::receiveSignal(...)` method, but the execution never reached that function. I did checked that the CAM signal is being emitted from `CaService::sendCam(...)` method.  

Can you please help? What am I missing here ?

**Comment by libertt1** [comment]
Hi @riebl,

Thank you for the previous answer. For reminder, my custom service is used by two cars entering an intersection. To fit the decentralized management of this intersection, I want to save positions and other values independently from each vehicle (store them to be used on the next trigger of the service). Where should I declare those variables so the instance of the service in the other car doesn't have access to them?

**Comment by kenog** [comment]
Hi @Amir-Teshome,

maybe I got you wrong but it sounds like you want the vehicles to send CAMs (which seems to work according to your test) and you want an RSU to receive those CAMs. Is that correct?

In that case, you confuse Omnet internal _signals_ with _messages_ sent via the network like, e.g., the CAM.
The `receiveSignal()` function is used to receive signals within one node. I.e. the ExampleService on vehicle A could receive the signal from the CaService on the same vehicleA and do something upon CAM transmission.
If you want the CA message to be received at the RSU instead, the simplest solution would be to start the CaService on the RSU, too. Whenever it receives a CAM then, its `indicate()` function is called by Artery and you can process the message there.
You could modify your `rsuservices.xml` like this:
```
<services>
       <service  type="artery.application.ExampleService">
		<listener  port="4711"  />
	</service>
	<service  type="artery.application.CaService">
		<listener  port="2001"  />
	</service>
</services>
```

Or did I get you wrong?

Regards

**Comment by riebl** [comment]
Truly distributed services will need to store the required data on their own @libertt1. What you call "independently from each vehicle" boils down to a global data structure.
If you need to fake the distributed nature of your service, just add a global module to your network which is accessed by both vehicles' services then.

**Comment by libertt1** [comment]
"independently from each vehicle" was certainly not appropriate, i meant fully distributed and independently from others vehicles. For the fully distributed way, where should I best declare the data for each vehicle? Sorry I didn't understand how the global module should help having distributed nature could you explain it more?

**Comment by riebl** [comment]
A global module does not enable a distributed service but it may simplify some aspects for initial development. From my point of view, it is perfectly fine to omit global modules.
Why not simply add member variables to your service for storing the necessary data for upcoming triggering events? If you have different types of services, you may also add your auxiliary data structures to the middleware's Facilities instance. Otherwise, simply keep data local to a service at the respective service.

**Comment by Amir-Teshome** [comment]
@kenog Thank you for your response.

In fact you are right, my goal is for the RSU to receive the CAMs  sent from the vehicles. Thank you for the explanation it cleared the confusion I have. 

However while trying your proposed direction (i.e., adding CA service to the RSU) I got the following error when the RSU are initialized
```
no valid object of type 'N6artery19VehicleDataProviderE' registered -- in module 
(artery::CaService) World.rsugneJ5.middleware.CaService (id=300), 
at t=0.548813502304s, event #129
```  
Note: `gneJ5` is the ID of the RSU
I didn't understand what the error is saying, is the CA service supposed to be used only with vehicles (i.e., NED modules with `artery.application.ItsG5Service` tags) ?

**Comment by riebl** [comment]
Right, `CaService` is in its current shape only usable for vehicles. I recommend to create a separate `RsuCaService` for RSUs as their CAMs are generated differently. According to EN 302 637-2 v1.4.1 RSUs are expected to generate a CAM one per second or at even longer intervals. Because of this low rate, RSUs do not throttle their rate due to DCC at all. The dynamic trigger conditions do not apply either for obvious reasons.
Instead of `BasicVehicleContainerHighFrequency` you will need to add a `RSUContainerHighFrequency`. In the end, `CaService` and `RsuCaService` do not have much code in common, except for their `indicate()` methods…

**Comment by kenog** [comment]
Okay sorry I did not check that and assumed the `CaService` was implemented for RSUs as well.

**Comment by Amir-Teshome** [comment]
@riebl Thank you for the explanation. 

In that case, what would be the approach to receive CAM messages from vehicles at the RSU ?

Thank you

**Comment by riebl** [comment]
Just for my personal amusement, I have implemented `RsuCaService`, which emits the same signals as `CaService`. Both services also receive their CAMs mutually. Optionally, you can even define protected communication zones to be included for each RSU individually.

**Comment by Amir-Teshome** [comment]
@riebl Thank you. I will try it

**Comment by libertt1** [comment]
Hi Riebl,

In my service, I am using the current vehicle geoposition and the CAM sender vehicle geoposition. I would like to determine the point of intersection between their trajectories but to do so I would like to switch to x,y space to calculate the coordinates of intersection that I would therefore cast back. How should I manage such a convert, using TraCIPosition?

**Comment by riebl** [comment]
You can convert `TraCIPosition` to `artery::Position` having Cartesian coordinates with `position_cast` functions back and forth. Those functions are declared in traci/Position.h.
However, these functions also require the SUMO network boundary for those conversions. The source code of `VehicleController` should give you an idea how to obtain this network boundary.

**Comment by Amir-Teshome** [comment]
@riebl  Thanks again for the `RsuCaService` implementation. I'm able to receive the `CA` Messages from vehicles at the RSU.

I'm trying to extract extract the content of CAM (like speed, latitude, longitude ..)  which are set in CaService inside the indicate method of RSUCaService. I tried
```
BasicContainer_t& basic = cam->camParameters.basicContainer;
double lat = basic.referencePosition.longitude;
``` 
(this is after receiving and validating CAM acceptance). However I'm getting an error `‘const class vanetza::asn1::Cam’ has no member named ‘camParameters’`. What is the correct way to get the data from CAM messages ? Thank you for the help

**Comment by libertt1** [comment]
Hi @Amir-Teshome, you should go see this issue #114.

**Comment by libertt1** [comment]
Hi @riebl,

Before using the boundary, I might convert my TraCIGeoPosition transmitted by the CAM into a TraCIPosition. I tried using API::convert2D but it returns lon,lat values and "invalid longitude" warnings appear in my simulation. Does this function modifies the behaviour of the simulation or am i using it wrong and it should do the cast as I want?

**Comment by riebl** [comment]
Ah, yes, `TraCIPosition` is Cartesian as well of course. Have you converted the longitude included in a CAM to degree beforehand? Please note that CAM's latitude and longitude are in tenths of microdegree.

**Comment by libertt1** [comment]
Hi @riebl,

The problem was the units, now it works. For the vanetza::facilities::distance function, I used the one with the (ReferencePosition,GeoAngle,GeoAngle) but now I want to use with two ReferencePosition. I already have the CAM ReferencePosition but I am struggling getting the one from the VehicleDataProvider. I tried to declare a ReferencePosition as in the createCAM from CaService but it is complaining about the round function. Here's the code:

```
auto mVehicleDataProvider = &getFacilities().get_const<VehicleDataProvider>();
ReferencePosition_t refPosVDP;`
refPosVDP.longitude = round(mVehicleDataProvider->longitude(), microdegree) * Longitude_oneMicrodegreeEast;
refPosVDP.latitude = round(mVehicleDataProvider->latitude(), microdegree) * Longitude_oneMicrodegreeNorth;
```

What did I miss and how can I have access to the two Longitude_oneMicrodegree constants?
Thank you

**Comment by riebl** [comment]
The `round` function is only defined in `CaService` at the moment. You may simply copy it to your service for now. For CAM related data elements such as `ReferencePosition_t`, `Latitude_oneMicrodegreeNorth` etc. you need to `#include <vanetza/asn1/its/CAM.h>` (`CaService` includes this header implicitly via vanetza/asn1/cam.hpp).
Beware that `Latitude_oneMicrodegreeEast` does not exist.

**Comment by libertt1** [comment]
Ok thanks, does the ReferencePosition_t from the CAM is ready to be used by distance()? And if it does, do I need to round and multiply the ReferencePosition_t created with the VehicleDataProvider lon,lat?

**Comment by riebl** [comment]
The `distance` functions in cam_functions.hpp can handle two `ReferencePosition_t` arguments or a `ReferencePosition_t` and two `units::GeoAngle` representing latitude and longitude.
Latter can be directly fed by `VehicleDataProvider` without any need for prior rounding operations.

**Comment by libertt1** [comment]
Thank you Riebl, I am trying to use VehicleTypeScope traci commands (setAccel). I added it to vehicleController but SUMO crashes due to this : `libsumo::TraCIException: .. Answered with error to command (197), [description: Vehicle type '1.0' is not known] -- in module (artery::Router) World.node[0].vanetza[0].router (id=84), at t=1.690901401405s`.

I have two vehicles of type '1.0' and '0.0' in my xml. What could it be complaining about? The vehicle not being part of the router already?

**Comment by riebl** [comment]
Is `1.0` really the vehicle type? Looks more like a vehicle ID to me.

**Comment by libertt1** [comment]
You are right, it was waiting for the string ID and not the type, my bad.

**Comment by libertt1** [comment]
Hi @riebl, 
Is it possible to record variables declared inside my service to plot them after the simulation as I did earlier to record the CAM components? They are not attached to signals as for the CAM and each node as its own set of values (angle calculated between the vehicles, collision threat, etc...)

**Comment by riebl** [comment]
Yes, you can record them as output vector. See the OMNeT++ manual for details.

**Comment by Jannat00177** [comment]
Hi @riebl,
I am beginner in this field and struggling to implement CAM communication (sending and receiving). When I apply CaService in service.xml, I couldn't see any V2X enabled vehicles on sumo-gui. All vehicles are sumo auto-configured. They are not responding to CaService. How will I enable them that one vehicle is sending CAM and others are receiving?I have used the code CaService::indicate for receiving CAMs. Here's the code:

<?xml version="1.0" encoding="utf-8"?>
<services>
    <service type="artery.application.CaService">
       <listener port="2001"/>
        <filters>
            <penetration rate="$penetration_rate$"/>
            <name pattern="VictimVehicle"/>
        </filters>
    </service>
</services>

Ned file:
import artery.application.ItsG5Service; 
simple VictimVehicle like ItsG5Service 
{
  @class(VictimVehicle);
  xml net;
  string victimVehicleIDs;
    double camTransmitFrequency = default(10.0);
    double camReactionPeriod = default(0.5);
    double stoppingDistanceSafetyCushion = default(5.0);
    double stoppingDistanceInterval = default(5.0);
    double evacuationZoneRadius = default(20.0);
    double fieldOfViewAngle = default(180.0);
}

**Comment by riebl** [comment]
Please open a separate discussion for your question @Jannat00177.
You won't see V2X messages or which vehicles are V2X enabled by Artery in *sumo-gui*, except you explicitly "mark" them for example by changing their colour via a TraCI command.

**Comment by Jannat00177** [comment]
Hi Riebl;

Thank you so much for your information and reply. I have used TraCI
command to see V2X enabled vehicles in sumo-gui for CAM implementation.
But it's not working.
This is Ned file:

import artery.application.ItsG5Service;
simple VictimVehicle like ItsG5Service
{
    @class(VictimVehicle);

    xml net;
    string victimVehicleIDs;
    double camTransmitFrequency = default(10.0);
    //double camReactionPeriod = default(0.5);
    double stoppingDistanceSafetyCushion = default(5.0);
    double stoppingDistanceInterval = default(5.0);

    double fieldOfViewAngle = default(180.0);
}

Also I have attached my (.cc) file. Please find the attachment below.
Could you please tell me what I am missing? It would be great help. Thank
you so much for your time and attention.

Best regards,
Jannat

**Comment by aintzel2** [comment]
> https://github.com/riebl/artery/blob/master/src/artery/application/ExampleService.cc subscribes to CAM receptions by its sibling CaService. You can cast the `cObject` of the signal handler to `CaObject`, which contains the whole CAM.

Hi @riebl I tried this code from `ExampleService.cc` trying to control vehicles:

`auto& vehicle = getFacilities().get_const<traci::VehicleController>();`

It works when I use `vehicle.getXX` functions but when I try with `vehicle.setXX` it doesn't work. I want to stop the vehicle by setting the speed to 0.
