### ISSUE TITLE
Fake messages

### ISSUE THREAD

**Issue by cuita85202** [riebl/artery#118]
Hello Riebl, 

I want to creat vehicles that gives a fake news and fake positions. And wanted to here from you what is the best way to do that. and which Modules do I have to modify or add?

thanks againt for this awesome tool

**Comment by kenog** [comment]
Hi @cuita85202,

you could modify the `CaService` and instead of reading the correct values from the `VehicleDataProvider`, you could just put whatever you like.

Regards
