### ISSUE TITLE
SUMO issues for run_example on Artery Vagrant VM

### ISSUE THREAD

**Issue by jweadick** [riebl/artery#119]
Hi @riebl ,

I am trying to use run_example and am having trouble getting SUMO to launch/appear to see what is happening. I'm assuming run_example is supposed to open a SUMO environment, although if not, please let me know. If it is supposed to run however, I'm hoping you'd know how I can view it? I initially added the line '*.traci.launcher.sumo = "sumo-gui"' to the omnetpp.ini file located at vagrant/artery/scenarios/artery/omnetpp.ini. SUMO still didn't appear for me, so I tried to update the VM by running "vagrant provision" but then received an error that I had made local changes to artery dependencies. 

Please let me know if there is a different omnetpp.ini file I should be modifying or if you know what could be the cause of SUMO not launching when running run_example using the cmake --build build --target run_example command.

Thanks for your time,

Josh Weadick

![artery_run_example_no_sumo](https://user-images.githubusercontent.com/54491904/84955749-a6f29280-b0ac-11ea-899e-eb6d5ed61325.jpg)

**Comment by riebl** [comment]
Hi @jweadick,

Artery launches SUMO for you, it is just running in the background without GUI on your screenshot. Adding `*.traci.launcher.sumo = "sumo-gui"` is the right way to enable SUMO's GUI. Please note that the content of the /vagrant directory is your host machine, i.e. the very same directory where you have run `vagrant up` before. The VM usually operates on the /home/vagrant/artery directory, i.e. you need to modify /home/vagrant/artery/scenarios/artery/omnetpp.ini.

The repository located at /home/vagrant/artery has a git remote configured named "vagrant", which is pointing to /vagrant, your Artery clone on the host machine. You may push and pull to and from this git remote to keep changes between VM and host machine in sync.
Usually, you need to provision a VM only once. I recommend to simply use git to keep your repository up-to-date.

**Comment by jweadick** [comment]
That clears up everything thank you so much! SUMO is working now and I did a git pull and was given an "already updated" message in the terminal. Thank you so much!
