### ISSUE TITLE
Running with veins configuration

### ISSUE THREAD

**Issue by jweadick** [riebl/artery#121]
Does running a model with the Veins configuration assume WAVE protocols instead of ITS-G5 protocols? I'm a little uncertain of the difference between running with Veins and running with INET and how that affects the models and would greatly appreciate any advice!

**Comment by riebl** [comment]
Just for the record: ITS-G5 and WAVE share a common radio technology, namely IEEE 802.11p. Artery can use Veins' 802.11 radio model, but it is still a ITS-G5 network then.

**Comment by jweadick** [comment]
Thank you! After reading the documentation more closely I realized this. I
appreciate the feedback though!
