### ISSUE TITLE
Multi-core execution

### ISSUE THREAD

**Issue by rtobi** [riebl/artery#122]
Hi, 
I am wondering if it is possible to use multiple cores for one single simulation, so no parallelization. Once building and running with _cmake --build build --target run_example_ the option -j does only speed up the building process. The simulation is still kept on one core. Do you have some suggestions?
Best regards!

**Comment by riebl** [comment]
Hi @rtobi,

no, you cannot use multiple cores for a single simulation run. At most two cores are utilised because SUMO and OMNeT++ are individual processes, which are coupled via TraCI.

**Comment by rtobi** [comment]
thanks a lot for the quick reply!
