### ISSUE TITLE
Vagrant Failure 

### ISSUE THREAD

**Issue by wargas92** [riebl/artery#123]
Hi, 
I'm trying to build artery inside a vm using your instruction.
Both Ubuntu 20.04 and Windows 10 gives this error runing valgrant up:

TASK [omnetpp : delete deprecated /opt/omnetpp directory] **********************
fatal: [default]: FAILED! => {"msg": "The conditional check 'opt_omnetpp.stat.isdir' failed. The error was: error while evaluating conditional (opt_omnetpp.stat.isdir): 'dict object' has no attribute 'isdir'\n\nThe error appears to have been in '/vagrant/ansible/omnetpp/tasks/main.yml': line 28, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: delete deprecated /opt/omnetpp directory\n  ^ here\n"}

Am I doing something wrong?

**Comment by riebl** [comment]
Hi @wargas92,

thanks for reporting this issue. I have just pushed a bugfix to the repository. Please pull this change and try again.

Regards,
Raphael

**Comment by wargas92** [comment]
Thanks for the quick reply. It works!!!
