### ISSUE TITLE
Confused on radio functionality

### ISSUE THREAD

**Issue by jweadick** [riebl/artery#124]
Hi Riebl,

I am trying to build a project that will estimate the amount of time two cars will be in communication proximity of each other. However, to do so, I need a better understanding of how the IEEE 802.11 radios in Artery are set up and I'm hoping you'll have some advice/info?

I am currently modifying the highway-police scenario and took out the police car, commented out all of ClearLaneService.cc and .h so it's just a blank initialize function, and adjusted both omnetpp.ini as well as CMakeLists.txt in an attempt to get the cars to stop communicating in OMNeT++ so I could write my own service that would perform the needed calculations and only transmit if the amount of time the two vehicles will be in range is sufficient. However, after removing just about all the code to make the program function, other than the basic SUMO highway config I set up, the cars are still transmitting GeoNet packets to each other and I am unsure what code is actually controlling these transactions. If you have any advice or could lead me to the correct files to modify I would be exceedingly grateful.

Best,

Josh Weadick

**Comment by riebl** [comment]
Even though no Artery services are running, the `Router` will generate roughly every 3.75 seconds a so-called GeoNetworking Beacon. This behaviour is specified by ETSI EN 302 636-4-1.
You may disable those beacons entirely by setting `mib.vanetzaDisableBeaconing = true` in `Router::initializeManagementInformationBase`. If you feel fancy, you can add an OMNeT++ module parameter for this purpose as well similar to the `deferInitialBeacon` option :-)

**Comment by jweadick** [comment]
I attempted to do so in my service by using `namespace Router { class initializeManagementInformationBase; }` and then declaring `Router::initializeManagementInformationBase mib.vanetzaDisableBeaconing = true;` in my modified ClearLaneService.h file. Is this the correct implementation or should I be modifying mib.vanetzaDisableBeaconing = true in a different file? I tried omnetpp.ini by using `*.node[*].mib.vanetzaDisableBeaconing = true` to no avail and was met with several errors saying mib needed a semicolon between mib and vanetzaDisableBeacon and am overall just very confused on where to implement this modification. 

Thanks for your help!

Best,

Josh Weadick

**Comment by riebl** [comment]
I have just added the modification with commit 46788e0. You only need to override the default setting, i.e. add a line `**.vanetza[*].router.disableBeaconing = true` (if you are using our INET cars) to your omnetpp.ini.

**Comment by jweadick** [comment]
Thank you that worked! One last question, which branch do you recommend working on in the vagrant VM? I was initially working on remotes/vagrant/master as that was the default branch that the VM started on, but was unable to pull changes until switching to remotes/origin/master. I'm assuming it would be best to work on remotes/origin/master so I can continue to pull changes as you update artery but am still relatively new to git and don't want my commits to get tangled with yours on that branch. Since I don't have push rights I'm hoping that working on that branch is fine and commits are saved to the branch locally but please let me know!

Best,

Josh Weadick

**Comment by jweadick** [comment]
Ah just ran into an additional problem. I am now trying to implement the radio broadcasts into my service to parse the location, direction, and speed information being sent by the radios. However after looking through the Radio.cc file I was unable to determine where this information comes from/what exactly is being transmitted by the INET radios. I also looked through the INET OMNeT++ documentation and was unable to find a concrete answer and I'm hoping you'll be able to steer me in the right direction/to the correct classes/files.

Thanks again for all your help, I really appreciate it!

Best,

Josh Weadick

**Comment by riebl** [comment]
The repository at /home/vagrant/artery has two remotes defined, `origin` and `vagrant`.
Pushing to or pulling from `vagrant` allows you to exchange commits with the repository on your host system. Please note that this does not change the working directory on the host. However, you can call `git push vagrant HEAD:foo` in the VM and then checkout the pushed commit (`HEAD`) on your host machine with `git checkout foo`.
`origin` is simply Artery's upstream repository. It does not matter if you directly pull upstream changes in the VM from `origin` or first pull on the host machine and then pull from `vagrant`.

The content of data packets is not related to any radio module. `CaService::indicate` parses received CAMs. These messages contain position and speed information.

**Comment by jweadick** [comment]
Ah I see thank you!
