### ISSUE TITLE
Artery build issue

### ISSUE THREAD

**Issue by bseptember** [riebl/artery#126]
Hi @riebl 

I've followed the instructions as well as I could. I've installed all dependencies as follows:

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Boost 1.65.1
cmake version 3.18.0
OMNeT++ 5.6.2
Python 3.6.11
GeographicLib 1.50.1
Crypto++ 5.6.1

**output as follows:**

duser@duser:~/artery/build$ cmake ..
-- Found Boost: /usr/local/include (found suitable version "1.65.1", minimum required is "1.58") found components: date_time 
-- SimuLTE integration disabled
-- Found Boost: /usr/local/include (found suitable version "1.65.1", minimum required is "1.59") found components: date_time system 
-- Enable Veins integration
-- Enable INET integration
-- Configuring done
-- Generating done
-- Build files have been written to: /home/duser/artery/build

duser@duser:~/artery/build$ cmake --build .
[  6%] Built target veins
[ 62%] Built target INET
[ 63%] Built target common
[ 64%] Built target net
[ 65%] Built target access
[ 71%] Built target asn1_security
[ 88%] Built target asn1
[ 90%] Built target security
[ 91%] Built target dcc
[ 93%] Built target geonet
[ 93%] Built target btp
[ 93%] Built target facilities
[ 93%] Built target gnss
[ 93%] Built target proxy_fake_feed
[ 94%] Built target traci
[ 94%] Building CXX object src/artery/CMakeFiles/core.dir/networking/GeoNetPacket.cc.o
In file included from /home/duser/omnetpp-5.6.2/include/omnetpp/cobject.h:26:0,
                 from /home/duser/omnetpp-5.6.2/include/omnetpp/cnamedobject.h:23,
                 from /home/duser/omnetpp-5.6.2/include/omnetpp/cownedobject.h:23,
                 from /home/duser/omnetpp-5.6.2/include/omnetpp/cevent.h:19,
                 from /home/duser/omnetpp-5.6.2/include/omnetpp/cmessage.h:20,
                 from /home/duser/omnetpp-5.6.2/include/omnetpp/cpacket.h:19,
                 from /home/duser/artery/src/artery/networking/GeoNetPacket.h:5,
                 from /home/duser/artery/src/artery/networking/GeoNetPacket.cc:1:
/home/duser/artery/src/artery/networking/GeoNetPacket.cc: In function ‘omnetpp::cObject* __factoryfunc_3()’:
/home/duser/artery/src/artery/networking/GeoNetPacket.cc:3:24: error: no matching function for call to ‘artery::GeoNetPacket::GeoNetPacket()’
 Register_Class(artery::GeoNetPacket)
                        ^
/home/duser/omnetpp-5.6.2/include/omnetpp/regmacros.h:148:92: note: in definition of macro ‘__REGISTER_CLASS_X’
 ct *MAKE_UNIQUE_WITHIN_FILE(__factoryfunc_)() {BASECLASS *ret = new CLASSNAME; 
                                                                     ^
/home/duser/omnetpp-5.6.2/include/omnetpp/regmacros.h:113:36: note: in expansion of macro ‘__REGISTER_CLASS’
 #define Register_Class(CLASSNAME)  __REGISTER_CLASS(CLASSNAME, omnetpp::cObject
                                    ^
/home/duser/artery/src/artery/networking/GeoNetPacket.cc:3:1: note: in expansion of macro ‘Register_Class’
 Register_Class(artery::GeoNetPacket)
 ^
In file included from /home/duser/artery/src/artery/networking/GeoNetPacket.cc:1:0:
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note: candidate: artery::GeoNetPacket::GeoNetPacket(const char*, short int, int64_t)
         using omnetpp::cPacket::cPacket;
                                 ^
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note:   candidate expects 3 arguments, 0 provided
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note: candidate: artery::GeoNetPacket::GeoNetPacket(const char*, short int)
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note:   candidate expects 2 arguments, 0 provided
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note: candidate: artery::GeoNetPacket::GeoNetPacket(const char*)
/home/duser/artery/src/artery/networking/GeoNetPacket.h:14:33: note:   candidate expects 1 argument, 0 provided
/home/duser/artery/src/artery/networking/GeoNetPacket.h:18:9: note: candidate: artery::GeoNetPacket::GeoNetPacket(artery::GeoNetPacket&&)
         GeoNetPacket(GeoNetPacket&&) = default;
         ^
/home/duser/artery/src/artery/networking/GeoNetPacket.h:18:9: note:   candidate expects 1 argument, 0 provided
/home/duser/artery/src/artery/networking/GeoNetPacket.h:16:9: note: candidate: artery::GeoNetPacket::GeoNetPacket(const artery::GeoNetPacket&)
         GeoNetPacket(const GeoNetPacket& other);
         ^
/home/duser/artery/src/artery/networking/GeoNetPacket.h:16:9: note:   candidate expects 1 argument, 0 provided
src/artery/CMakeFiles/core.dir/build.make:492: recipe for target 'src/artery/CMakeFiles/core.dir/networking/GeoNetPacket.cc.o' failed
make[2]: *** [src/artery/CMakeFiles/core.dir/networking/GeoNetPacket.cc.o] Error 1
CMakeFiles/Makefile2:887: recipe for target 'src/artery/CMakeFiles/core.dir/all' failed
make[1]: *** [src/artery/CMakeFiles/core.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

**Please help, I'm not sure how to fix this. Thank you.**

**Comment by riebl** [comment]
Please fetch the bugfix from master branch and try again.
Unfortunately (?), my compiler seems to be more forgiving and triggered no errors.

**Comment by bseptember** [comment]
Hi @riebl 

I deleted my artery directory and then
what i did was instead of: git clone --recurse-submodule https://github.com/riebl/artery.git

I used: **git clone -b master https://github.com/riebl/artery.git**

then inside my path i used as per normal:
git submodule update --init --recursive

Then build was ok. THANK YOU!
![image](https://user-images.githubusercontent.com/68727050/88514595-aa056a80-cfea-11ea-9143-ce7893999a67.png)
