### ISSUE TITLE
E2ED of useCase DENM 

### ISSUE THREAD

**Issue by insafnmr** [riebl/artery#127]
Hello, 
I want to measure the end-to-end delay of a useCase of DENM. So i try to get the time of generation of the UseCase as it is written below : 
`void UnmanagedBlockageRoad::check()
{
    mVelocitySampler.feed(mVdp->speed(), mVdp->updated());
    if(checkPosition()){
    double FirstTimestamp = countTaiMilliseconds(mService->getTimer()->getTimeFor(mVdp->updated()));
    auto denm = createMessage();
    auto request = createRequest();
    mService->sendDenm(std::move(denm), request);
        numSentUBR++;   }  }`
but when i try to calculate the E2ED 
` void UnmanagedBlockageRoad::indicate(const artery::DenmObject& denm)
{
    if (denm & CauseCode::HazardousLocation_SurfaceCondition ) {
        const vanetza::asn1::Denm& asn1 = denm.asn1();
        numReceivedUBR++;
      eed = omnetpp::simTime().dbl() - FirstTimestamp;
        totalBitsReceivedUBR+= (asn1.size())*8;    }
}` 

a problem was occured during the simulation :
> Cannot convert -2.97175e+11 to simtime_t: Out of range (-9223372.036854775807,9223372.036854775807), allowed by scale exponent -12 -- in module  (artery::Router) .

Best regards.

**Comment by riebl** [comment]
First, `countTaiMilliseconds` does not return a `double` but `uint64_t`, which is fine for ETSI ITS `TimestampIts`.
Second, you need to attach the time stamp to the message. It is not sufficient to store a timestamp locally as you do with `FirstTimestamp`. If millisecond accuracy for calculating end-to-end delays is sufficient you may use the `detectionTime` timestamp in DENM's management container for this purpose.

**Comment by insafnmr** [comment]
When i try to use the `detectionTime`, a problem of conversion occured :```
 cannot convert ‘TimestampIts_t’ {aka ‘ASN__PRIMITIVE_TYPE_s’} to ‘uint64_t’ {aka ‘long unsigned int’} in assignment
     genDeltaTime = msg->denm.management.detectionTime;
```

`void UnmanagedBlockageRoad::check()
{
    mVelocitySampler.feed(mVdp->speed(), mVdp->updated());
    if(checkPosition()){
    auto denm = createMessage(FirstTimestamp);
    auto request = createRequest();
    mService->sendDenm(std::move(denm), request);

        numSentUBR++;     }    
}
vanetza::asn1::Denm UnmanagedBlockageRoad::createMessage(uint64_t genDeltaTime)
{
    auto msg = createMessageSkeleton();

    genDeltaTime = msg->denm.management.detectionTime;

     msg->denm.management.relevanceDistance = vanetza::asn1::allocate<RelevanceDistance_t>();
    *msg->denm.management.relevanceDistance = RelevanceDistance_lessThan1000m;
    msg->denm.management.relevanceTrafficDirection = vanetza::asn1::allocate<RelevanceTrafficDirection_t>();
    *msg->denm.management.relevanceTrafficDirection = RelevanceTrafficDirection_allTrafficDirections;
    msg->denm.management.validityDuration = vanetza::asn1::allocate<ValidityDuration_t>();
    *msg->denm.management.validityDuration = 3600;
    msg->denm.management.stationType = StationType_passengerCar; 
   

    msg->denm.situation = vanetza::asn1::allocate<SituationContainer_t>();
    msg->denm.situation->informationQuality = 1;
    msg->denm.situation->eventType.causeCode = CauseCodeType_hazardousLocation_SurfaceCondition;
    msg->denm.situation->eventType.subCauseCode = 0;

    return msg;
}
`

**Comment by riebl** [comment]
See UseCase.cc for an example how to use `asn_long2INTEGER` for this purpose.

**Comment by insafnmr** [comment]
Hello @riebl,
Sorry for this annoyance, I have a question that is not related to the E2ED. My question is about the size of a packet sent for the UnmanagedBlockageRoad useCase of DENM. I want to know the size of the packet so i tried this method : 
`void UnmanagedBlockageRoad::check()
{
    mVelocitySampler.feed(mVdp->speed(), mVdp->updated());
    if(checkPosition()){
        auto denm = createMessage();
        auto request = createRequest();
        mService->sendDenm(std::move(denm), request);
        DenmObject obj(std::move(denm));
        emit(UBRSentSignal, &obj);
        totalBitsSentUBR+=(obj.asn1().size())*8;
        t_gen = omnetpp::simTime();  }    
} ` 
but during the simulation I encountered this problem 

> std::runtime_error: Can't determine size for unaligned PER encoding of type DENM because of DENM sub-type -- in module (artery::VehicleMiddleware) World.node[0].appl.middleware (id=17), at t=8.584725173726s, event #951
i will be very grateful if you help me.
cordially.

**Comment by riebl** [comment]
Hi @insafnmr,

as the runtime error message tells you, the generated DENM is faulty and thus the ASN.1 encoder cannot determine a size for this message. "type DENM because of DENM sub-type" sounds odd, admittedly. Can you try if `denm.size()` works before `std::move(denm)` is invoked?

**Comment by insafnmr** [comment]
Thank you for your reply and for your help. I tried `denm.size()` before the invocation of  `std::move(denm)` and it get well. Thanks again.

**Comment by insafnmr** [comment]
Hi riebl,
I still have problems with the E2ED. I tried to implement a new parameter under "AlacarteContainer" as quoted below.
`	TimeGeneration_t	*timeGeneration; `
`#ifndef	_TimeGeneration_H_
#define	_TimeGeneration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeGeneration {
	TimeGeneration_oneMilliSec	= 1
} e_TimeGeneration;

/* TimeGeneration */
typedef long	 TimeGeneration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeGeneration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeGeneration;
asn_struct_free_f TimeGeneration_free;
asn_struct_print_f TimeGeneration_print;
asn_constr_check_f TimeGeneration_constraint;
ber_type_decoder_f TimeGeneration_decode_ber;
der_type_encoder_f TimeGeneration_encode_der;
xer_type_decoder_f TimeGeneration_decode_xer;
xer_type_encoder_f TimeGeneration_encode_xer;
oer_type_decoder_f TimeGeneration_decode_oer;
oer_type_encoder_f TimeGeneration_encode_oer;
per_type_decoder_f TimeGeneration_decode_uper;
per_type_encoder_f TimeGeneration_encode_uper;
per_type_decoder_f TimeGeneration_decode_aper;
per_type_encoder_f TimeGeneration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeGeneration_H_ */
#include "asn_internal.h"
`
Then at the level of my application in `createMessage()` function, I added these lines of code:
`
msg-> denm.alacarte = vanetza :: asn1 :: allocate <AlacarteContainer_t> ();
msg-> denm.alacarte-> timeGeneration = vanetza :: asn1 :: allocate <TimeGeneration_t> ();
* msg-> denm.alacarte-> timeGeneration = FirstTimestamp * TimeGeneration_oneMilliSec;

`
and here is my code for the `indicate()` function 
`void UnmanagedBlockageRoad::indicate(const artery::DenmObject& denm)
{
    if (denm & CauseCode::HazardousLocation_SurfaceCondition ) {
        const vanetza::asn1::Denm& asn1 = denm.asn1();
        if (asn1->denm.alacarte && asn1->denm.alacarte->timeGeneration) {
            auto gen = asn1->denm.alacarte->timeGeneration;
        eed = omnetpp::simTime().dbl() - gen ;
    }
}
}`

So my problem is when i calculate the E2ED, i have the problem of conversion. i tried to use the casting method but but it does not work. Can you help me please ? How can i get the value of "gen" in double.
Cordially.

**Comment by insafnmr** [comment]
Hello @riebl ,
I have a question please, how can i set the packet length of a useCase Denm?

**Comment by riebl** [comment]
You cannot set an arbitrary message size when using `DenService` and its use cases, which will always use the size of the ASN.1 UPER encoded DENM.
If you need custom message lengths, you should consider writing a custom service.

**Comment by insafnmr** [comment]
Thank you for your reply.
