### ISSUE TITLE
About cmake question:TARGETS given target  which does not exist in this directory.

### ISSUE THREAD

**Issue by kirsguo** [riebl/artery#128]
hi, when i run cmake .
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OmnetPP: /home/kirsguo/omnetpp-5.5.1/include (found suitable version "5.5.1", minimum required is "5.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
-- Found CryptoPP: /usr/include (found suitable version "5.6.4", minimum required is "5.6.1") 
-- Found GeographicLib: /usr/include (found suitable version "1.49", minimum required is "1.37") 
CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "access" which does not exist in this
  directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "asn1" which does not exist in this directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "btp" which does not exist in this directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "common" which does not exist in this
  directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "dcc" which does not exist in this directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "facilities" which does not exist in this
  directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "geonet" which does not exist in this
  directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "gnss" which does not exist in this directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "net" which does not exist in this directory.

CMake Error at CMakeLists.txt:32 (install):
  install TARGETS given target "security" which does not exist in this
  directory.

-- SimuLTE integration disabled
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   system
-- Enable Veins integration
-- Enable INET integration
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Configuring incomplete, errors occurred!
See also "/home/kirsguo/artery/CMakeFiles/CMakeOutput.log".
See also "/home/kirsguo/artery/CMakeFiles/CMakeError.log".

**Comment by riebl** [comment]
Could you please verify that the git submodule at extern/vanetza is up-to-date in your working copy?

**Comment by riebl** [comment]
Looks like CMake 3.13 is required for `install(TARGETS ...)` to work across directories. I am still looking for a workaround.

**Comment by QuentinDLZ** [comment]
I had the same issue (Ubuntu 18.04, cmake version 3.10.2).
Installed cmake version 3.18.0 and it worked fine

**Comment by bseptember** [comment]
Hi @kirsguo 

I had this same issue, what I did:
remove older version of cmake
install latest cmake which was 3.18.0..
but still didnt work because omnet was missing??
so I built omnetpp again
still didnt work...
after frustrations.. I made a note that before compiling any of artery dependencies (including vanetzas) make sure cmake is latest...
built boost again
then tried building artery again and it worked.

**Comment by kirsguo** [comment]
> I had the same issue (Ubuntu 18.04, cmake version 3.10.2).
> Installed cmake version 3.18.0 and it worked fine



> I had the same issue (Ubuntu 18.04, cmake version 3.10.2).
> Installed cmake version 3.18.0 and it worked fine
I had installed cmake version 3.18.0 and make successfully But,
when I run cmake --build build --target run_example 
kirsguo@KIrsguoLAB:~/artery$ cmake --build build --target run_example
make: *** 没有规则可制作目标“run_example”。 停止。 (No rule or target)
kirsguo@KIrsguoLAB:~/artery$ cd build/
kirsguo@KIrsguoLAB:~/artery/build$ make run_example
make: *** 没有规则可制作目标“run_example”。 停止。

**Comment by bseptember** [comment]
Hi @kirsguo 
Not sure why make run_example doesn't work, perhaps @riebl  can answer.

However, try opening a terminal in /artery/scenarios/car2car-grid 
then type: source /home/duser/artery/build/run_artery.sh

![image](https://user-images.githubusercontent.com/68727050/88553143-39c80a80-d025-11ea-82be-7f3585b3a756.png)

You should get the following output. Click Ok then Run...
![image](https://user-images.githubusercontent.com/68727050/88553406-8a3f6800-d025-11ea-9ffc-9dac6577f542.png)

**Comment by riebl** [comment]
I have just pushed commit 996a773bf which restores compatibility with older CMake versions. For my tests, I have used CMake 3.7 from Debian Stretch.

@kirsguo I have no idea why the `run_example` target is not generated on your system. Is your working copy pristine?

@bseptember You don't have to rebuild Boost and OMNeT++ if Artery does not compile.

**Comment by kirsguo** [comment]
Hi  @riebl , the complete sequence of operations and the results are as follows:
`git clone --recurse-submodule https://github.com/riebl/artery.git
Cloning into 'artery'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 32461 (delta 75), reused 126 (delta 63), pack-reused 32301
Receiving objects: 100% (32461/32461), 39.34 MiB | 7.66 MiB/s, done.
Resolving deltas: 100% (21332/21332), done.
Submodule 'extern/inet' (https://github.com/riebl/inet.git) registered for path 'extern/inet'
Submodule 'extern/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'extern/pybind11'
Submodule 'extern/sim0mqpp' (https://github.com/riebl/sim0mqpp.git) registered for path 'extern/sim0mqpp'
Submodule 'extern/simulte' (https://github.com/riebl/simulte.git) registered for path 'extern/simulte'
Submodule 'extern/vanetza' (https://github.com/riebl/vanetza.git) registered for path 'extern/vanetza'
Submodule 'extern/veins' (https://github.com/sommer/veins.git) registered for path 'extern/veins'
Submodule 'scenario_mt-its2017' (https://github.com/riebl/artery_scenario_mt-its2017.git) registered for path 'scenarios/mt-its2017'
Cloning into '/home/kirsguo/artery/extern/inet'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 209991 (delta 1), reused 0 (delta 0), pack-reused 209988        
Receiving objects: 100% (209991/209991), 80.11 MiB | 8.43 MiB/s, done.
Resolving deltas: 100% (169632/169632), done.
Cloning into '/home/kirsguo/artery/extern/pybind11'...
remote: Enumerating objects: 23, done.        
remote: Counting objects: 100% (23/23), done.        
remote: Compressing objects: 100% (17/17), done.        
remote: Total 11957 (delta 8), reused 12 (delta 4), pack-reused 11934        
Receiving objects: 100% (11957/11957), 4.46 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (8097/8097), done.
Cloning into '/home/kirsguo/artery/extern/sim0mqpp'...
remote: Enumerating objects: 88, done.        
remote: Counting objects: 100% (88/88), done.        
remote: Compressing objects: 100% (43/43), done.        
remote: Total 88 (delta 43), reused 82 (delta 37), pack-reused 0        
Cloning into '/home/kirsguo/artery/extern/simulte'...
remote: Enumerating objects: 13, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 5756 (delta 5), reused 1 (delta 0), pack-reused 5743        
Receiving objects: 100% (5756/5756), 4.02 MiB | 632.00 KiB/s, done.
Resolving deltas: 100% (4140/4140), done.
Cloning into '/home/kirsguo/artery/extern/vanetza'...
remote: Enumerating objects: 3970, done.        
remote: Counting objects: 100% (3970/3970), done.        
remote: Compressing objects: 100% (2263/2263), done.        
remote: Total 21137 (delta 2197), reused 2724 (delta 1480), pack-reused 17167        
Receiving objects: 100% (21137/21137), 11.79 MiB | 5.29 MiB/s, done.
Resolving deltas: 100% (14729/14729), done.
Cloning into '/home/kirsguo/artery/extern/veins'...
remote: Enumerating objects: 24536, done.        
remote: Total 24536 (delta 0), reused 0 (delta 0), pack-reused 24536        
Receiving objects: 100% (24536/24536), 15.99 MiB | 707.00 KiB/s, done.
Resolving deltas: 100% (18046/18046), done.
Cloning into '/home/kirsguo/artery/scenarios/mt-its2017'...
remote: Enumerating objects: 50, done.        
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50        
Submodule path 'extern/inet': checked out '32f18480e94372ea10225fd9fff5427789e72224'
Submodule 'showcases' (https://github.com/inet-framework/inet-showcases.git) registered for path 'extern/inet/showcases'
Submodule 'tutorials' (https://github.com/inet-framework/inet-tutorials.git) registered for path 'extern/inet/tutorials'
Cloning into '/home/kirsguo/artery/extern/inet/showcases'...
remote: Enumerating objects: 13, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (11/11), done.        
remote: Total 5165 (delta 2), reused 5 (delta 2), pack-reused 5152        
Receiving objects: 100% (5165/5165), 193.01 MiB | 8.04 MiB/s, done.
Resolving deltas: 100% (2579/2579), done.
Cloning into '/home/kirsguo/artery/extern/inet/tutorials'...
remote: Enumerating objects: 1991, done.        
remote: Total 1991 (delta 0), reused 0 (delta 0), pack-reused 1991        
Receiving objects: 100% (1991/1991), 69.25 MiB | 860.00 KiB/s, done.
Resolving deltas: 100% (1275/1275), done.
Submodule path 'extern/inet/showcases': checked out '04faf017ce522e55ccdd9a405ac1d79afd312380'
Submodule path 'extern/inet/tutorials': checked out 'cad6147ca84440a662dffc2d76aebc6c8cf596c8'
Submodule path 'extern/pybind11': checked out '3b1dbebabc801c9cf6f0953a4c20b904d444f879'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'extern/pybind11/tools/clang'
Cloning into '/home/kirsguo/artery/extern/pybind11/tools/clang'...
remote: Enumerating objects: 13, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 368 (delta 3), reused 6 (delta 1), pack-reused 355        
Receiving objects: 100% (368/368), 159.34 KiB | 336.00 KiB/s, done.
Resolving deltas: 100% (154/154), done.
Submodule path 'extern/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'extern/sim0mqpp': checked out '512b7caccb0a7cd2cfac0adcc3811cad180ac45e'
Submodule path 'extern/simulte': checked out 'd7373cadac93c26ca9a975ff3aab689dee3fc2eb'
Submodule path 'extern/vanetza': checked out '2dfed78e3f35ba06e03f0815eb04a5623132f7f3'
Submodule path 'extern/veins': checked out '7663eebc534ae3d9caa02ff2fea74fcce7c576ef'
Submodule path 'scenarios/mt-its2017': checked out '9f327b8d0dc4169450c4bffdb1c23913b6b6f799'
`
kirsguo@KIrsguoLAB:~$ cd artery/
kirsguo@KIrsguoLAB:~/artery$ mkdir build
kirsguo@KIrsguoLAB:~/artery$ cd build/
kirsguo@KIrsguoLAB:~/artery/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OmnetPP: /home/kirsguo/omnetpp-5.5.1/include (found suitable version "5.5.1", minimum required is "5.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.58") found components: date_time 
-- Found CryptoPP: /usr/include (found suitable version "5.6.4", minimum required is "5.6.1") 
-- Found GeographicLib: /usr/include (found suitable version "1.49", minimum required is "1.37") 
-- SimuLTE integration disabled
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.59") found components: date_time system 
-- Enable Veins integration
-- Enable INET integration
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kirsguo/artery/build

kirsguo@KIrsguoLAB:~/artery/build$ cmake --build .
kirsguo@KIrsguoLAB:~/artery/build$ cd ..
kirsguo@KIrsguoLAB:~/artery$ cmake --build build --target run_example
make: *** No rule to make target 'run_example'.  Stop.
kirsguo@KIrsguoLAB:~/artery$ cd build/
kirsguo@KIrsguoLAB:~/artery/build$ make run_example
make: *** No rule to make target 'run_example'.  Stop.
kirsguo@KIrsguoLAB:~/artery/build$
![2020-07-28 10-06-19 的屏幕截图](https://user-images.githubusercontent.com/17877233/88610811-2e72ee80-d0ba-11ea-95cb-73f7232ca7db.png)
![2020-07-28 10-06-54 的屏幕截图](https://user-images.githubusercontent.com/17877233/88610812-30d54880-d0ba-11ea-992f-d27866df7b7b.png)
![2020-07-28 10-07-01 的屏幕截图](https://user-images.githubusercontent.com/17877233/88610815-32067580-d0ba-11ea-8c04-82840b37815a.png)

**Comment by kirsguo** [comment]
HI @bseptember ,I tried your method and it worked. Thanks a lot!
I type: source ../../build/run_artery.sh      in       /artery/scenarios/artery
![2020-07-28 10-20-18 的屏幕截图](https://user-images.githubusercontent.com/17877233/88611614-f9679b80-d0bb-11ea-9380-c349456a161b.png)
But , I still have no idea why the 'run_example' target  cannot use.

**Comment by riebl** [comment]
Could you please try following steps @kirsguo 

1. change `if (EXISTS scenarios)` in CMakeLists.txt to `if (EXISTS ${PROJECT_SOURCE_DIR}/scenarios)`
2. remove your build directory
3. try your build steps again

Possibly your CMake version evaluates the expression to false and thus the scenarios are disabled and no run targets are added.

**Comment by kirsguo** [comment]
Hi @riebl   It worked !  THX !!
