### ISSUE TITLE
Crypto 8.2.0 error 

### ISSUE THREAD

**Issue by bseptember** [riebl/artery#129]
Hi @riebl 

my deps installed:
![image](https://user-images.githubusercontent.com/68727050/88918621-0fb35a00-d26a-11ea-92aa-6b62136dfea7.png)

used:
git clone -b master https://github.com/riebl/artery.git
and then in directory...
git submodule update --init --recursive

**I'm having some kind of library issue... frustrating because I've had it working on another VM which I no longer have. 

![image](https://user-images.githubusercontent.com/68727050/88917688-7d5e8680-d268-11ea-9fb0-904914d27f30.png) 

I used https://github.com/weidai11/cryptopp/releases/tag/CRYPTOPP_8_2_0
I gather it is something to do with my **Cryptopp lib** but haven't had this issue on other VM. 
Also I tried to build vanetza seperately and the output is as follows. I've even tried changing version ;( to no avail.

![image](https://user-images.githubusercontent.com/68727050/88918075-22795f00-d269-11ea-9b1a-99ffadb9b5b0.png)

locating libcrypto below:

![image](https://user-images.githubusercontent.com/68727050/88918240-72582600-d269-11ea-9260-7d31f4d90325.png)

Not sure on this... I will try installing crypto 5.6.2 and see if I get the same issue...
I also thought it is maybe pointing to the wrong python, I do have python 3.6 installed... not sure why it points to 3.5.2
let me know if im on the right track...
Thank you!

**Comment by riebl** [comment]
Using crypto++ 8.2 is fine, it works flawlessly on my computer. Please check if the `CryptoPP_LIBRARY` CMake variable is set correctly in your build directory, i.e. the file actually exists and matches the version of the Crypto++ headers. It should also not point to the static library, i.e. libcryptopp.a

**Comment by bseptember** [comment]
thank you @riebl 

I investigated what was going on in my /usr/lib 
**crypto 8.2.0 was installed** in /usr/local/lib

and there was an older version of crypto 5.6.2 installed as well.
I noticed that it kept on pointing to the old one...
So I removed all traces of it.
**started a fresh build with crypto 8.2.0 and it worked!**
![image](https://user-images.githubusercontent.com/68727050/88942568-bd366580-d28a-11ea-9624-29650070432d.png)

make run_example

**Thanks again!**
![image](https://user-images.githubusercontent.com/68727050/88942608-ca535480-d28a-11ea-9d37-528869b5f1da.png)
