### ISSUE TITLE
CBR calculation method

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#131]
Hi,

I'm investigating different methods to calculate the Channel Busy Ratio  (CBR), for the ITS-G5. And I want to test these methods on Artery. But I couldn't find where and how CBR is calculated. So could anyone help me?

Thanks.

**Comment by riebl** [comment]
If you are using the Veins radio model, the `VeinsRadioDriver` subscribes to the `veins::Mac1609_4::sigChannelBusy` and generates CBRs accordingly.
If you are using the INET radio model, you have two options: Either `ChannelLoadRx` which tracks the busy state similar to the Veins model, or `PowerLevelRx` which actually evaluates the signal power. As defined by ITS-G5, only signals above -85 dBm contribute to CBR. If the receiver sensitivity is set to -85 dBm, both variants report equal CBRs and you can use the simpler `ChannelLoadRx`. However, if you plan to use more sensitive receiver settings (-96 dBm is not unreasonable), this simpler approach produces too high CBRs as it also picks up rather weak signals. `PowerLevelRx` is a little bit more complicated, but its CBRs take only signals and noise above their respective thresholds into account (-85 and -65 dBm).

**Comment by SamirRachedi** [comment]
Thanks a lot, @riebl.
Just one other question. If I want to retrieve real-time CBR from a certain service (let's say CaService), how can I do it?

**Comment by riebl** [comment]
At the moment, no ready-to-go implementation exists for this purpose. You could add a public `getChannelLoad` method to `PowerLevelRx`, look-up this module during initialization of your service and cast the module pointer to `PowerLevelRx*` so you can call the `getChannelLoad` method from there.
Have a look at the `inet::getModuleFromPar` function which is quite handy for this purpose.
