### ISSUE TITLE
Install artery on Ubuntu docker container

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#132]
Dear Reibel, 

I'm working on docker, and I need to install Artery on one of my Ubuntu18.04 containers.

But I'm not sure if it is possible.
Any help?

Thanks.

**Comment by riebl** [comment]
Hi @SamirRachedi,

have you seen the Dockerfile at the root of Artery's repository? It is using Debian as base image, however, you should be able to use Ubuntu instead with minor modifications.
