### ISSUE TITLE
Queuing latency on Artery

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#133]
Hi @riebl, 

I'm trying to calculate the queuing latency (eg for CAM) on Artery.
I found the enqueue and dequeue function in Vanetza (in dcc/flow_control). So what I'm trying now is to print into a file (txt, csv ...) the enqueuing and dequeuing times of each message, then do a substraction. in addition to that, I need some identifier for each message so I can know what times to use to find their en/dequeuing times. You can imagine the structure of each line in the file as follows: "Msg_ID, enqueue/dequeue time".
The problem is that the request and packet objects used in the flow_control module don't contain any ID or anything that could serve as ID. Any suggestions?
Thanks

**Comment by riebl** [comment]
You could  use the memory address of the enqueued packet to match enqueue and dequeue timestamps. This address does not change as long as the packet exists. You may see the same address recurring for a later packet, though.

**Comment by SamirRachedi** [comment]
Hi @riebl, 

thanks for your help. 
I have another issue if you can help. I'm using in my scenario two flows of vehicles, in a two-way highway (4 lanes each), the first flow uses a service with DCC profile 0 (DP0); the second using DP2. 
I've noticed that only vehicles of the first flow (DP0) are enqueuing their messages, vehicles of the other flow don't (which I find very strange since backoffs of DP2 should be higher than DP0, i.e DP2 flow should enqueue more and wait longer !!)

So what's the problem?
Thanks.

**Comment by riebl** [comment]
Where do you observe that packets are enqueued, in `dcc::FlowControl`? Please be aware that DP0 is designated to emergency messages, which have a dedicated "burst budget". This special budget allows up to 20 DP0 packets within 1 second and then no further DP0 packets are allowed for 10 seconds.
This behaviour has been proposed by CAR 2 CAR Communication Consortium and is implemented by `vanetza::dcc::BurstyTransmitRateControl`. You may want to use another transmit rate control such as `SingleReactiveTransmitRateControl` that uses the same budget determined by reactive DCC for all DPs.
You can configure the employed transmit rate control by the "TransmitRateControl" parameter of the dcc module, just change this parameter from its default "Bursty" to "StateMachine".

**Comment by SamirRachedi** [comment]
Hi @riebl, 
First, to answer your question, I put a "cout" in the enqueue function, so whenever it's called, I would know. And for the DPs, I'm aware of the priorities, I'm just testing example of applications with DP0.
Second, I would like to understand how the implemented reactive TRC works. As a single reactive TRC, we have only one channel state. This means that the transmission rate should be fixed for all ITS stations during all the simulation (you can refer to ETSI TS 102 687 V1.2.1 section 5.3 and Annexe A), not only that but all packets before transmission are assigned to the corresponding queues depending on their access priority (ETSI TS 102 687 V1.1.1, section 5.2.2). When I'm using it, I've noticed that not only the transmission rate is changing for each ITS station, but also no packet is enqueued (the transmit_immediately function in flow_control always returns true).
So, how the implemented TRC works?
Thanks a lot.

**Comment by riebl** [comment]
The transmission rate is only fixed if the measured channel busy ratio remains stable. However, you will usually observe less congestion at the map fringe than in the centre region.

The `dcc::FlowControl` implementation allows immediate transmissions if no packet is enqueued yet and the time since the last transmission is longer than the mandatory transmission interval T_off. Hence, you need to generate packets faster than the currently allowed rate by TRC. Otherwise, there is no reason to enqueue a packet.

**Comment by SamirRachedi** [comment]
Well, then thanks for the clarification. Just one last question, what is the min/max transmission rate of the implemented TRC?
and where you are using the CBR to specify the appropriate transmission rate?
Thanks.

**Comment by riebl** [comment]
This depends on the parameterisation of the used state machine. The default is "FullyMeshed", which implements C2C-CC's DCC whitepaper/BSP v1.2. This particular state machine enforces inter-transmission gaps of 60ms to 460ms.
I am not sure if I have undestood the second part of your question correctly. Vanetza has a `vanetza::dcc::StateMachine` interface which demands implementation of an `update(ChannelLoad)` method. This method is invoked by Artery's `FsmDccEntity::onGlobalCbr` then.

**Comment by kenog** [comment]
Sidenote: The current BSP only references TS 102 687 and does not detail the state machine. TS 102 687 1.2.1 does not mention the fully meshed version any more. Therefore I assume the "FullyMeshed" state machine is obsolete.
To my understanding, the "Gradual 500us" is the state machine to use in order to be compliant to the current versions of TS 102 587 and the C2C-CC BSP 1.5.

**Comment by riebl** [comment]
Yes, @kenog, I also consider the "FullyMeshed" as an early days' relict. Using one of ETSI's parameter settings is definitely a reasonable option, however, they are only "informative" and the earlier BSP settings are still allowed as they comply with EN 302 571. That said, my impression is that most out there favour the adaptive approach anyway nowadays.
