### ISSUE TITLE
Read header from vanetza::UpPacket

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#135]
Hi @riebl, 
I'm trying to read header content in a received CAM message. First I changed the header structure (I added an attribute to contain info that I need, I set this info's value in **createCooperativeAwarenessMessage()**, using **(*message).header.info** to cout is working fine here). 
Now I'm trying to read this value in the Indicate() function where (if I'm not wrong) we should find it in the vanetza::UpPacket. 
So what can I do?
Thanks

**Comment by riebl** [comment]
You can access CAM's header via `(*cam)->header` in `CaService::indicate`.
