### ISSUE TITLE
Sensing range of RSU

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#137]
Hello @riebl, 

I'm trying to place RSUs on a highway of 2Km length, and I want all messages sent by vehicles to be received by one RSU at least.
So, what is the sensing range of RSU in Artery? 
Currently, I'm using two. is it sufficient?

**Comment by riebl** [comment]
Communication range depends on so many factors that I cannot give you an definite answer.
The employed path loss model, the transmitters' power and the receivers' sensitivity are the major factors affecting the resulting communication range. Assuming line-of-sight conditions you can expect a range of about 1 km. I would place RSUs at distances not more than 500m apart to reliably receive all vehicle messages. Nevertheless, you will need to check the results in the end.

**Comment by riebl** [comment]
Closing stale ticket.
