### ISSUE TITLE
Simulation Issue run_example

### ISSUE THREAD

**Issue by bargmann** [riebl/artery#14]
Hi, 
when i will run the run _example Omnet throws the following error:
`<!> std::runtime_error: Can't determine size for unaligned PER encoding of type CAM because of Latitude sub-type -- in module (artery::VehicleMiddleware) World.node[1].appl.middleware (id=15), at t=0.260276337038s, event #14
`

The start command gives the following output: 
`baa4hi@hi-z0f30:~/artery$ cmake --build build --target run_example
[ 13%] Built target traci
[ 14%] Building Vanetza (external dependency)
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:42 (find_package)

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:45 (find_package)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:45 (find_package)

-- Cohda SDK not found (missing:  COHDA_ROOT) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/baa4hi/artery/extern/vanetza/build
[ 80%] Built target asn1
[ 81%] Built target common
[ 83%] Built target net
[ 90%] Built target security
[ 92%] Built target dcc
[ 97%] Built target geonet
[ 98%] Built target btp
[ 99%] Built target facilities
[100%] Built target gnss
[100%] Built target proxy_fake_feed
[ 14%] Built target build_vanetza
[ 14%] Building INET (external dependency)
*** COMPILING with:
g++ -c -std=c++11 -O2 -DNDEBUG=1 -MMD -MP -MF .d  -fPIC  -fno-stack-protector -DHAVE_SWAPCONTEXT -DWITH_MPI -DXMLPARSER=libxml -DPREFER_QTENV -DWITH_QTENV -DWITH_TKENV -DWITH_PARSIM -DWITH_NETBUILDER -DWITH_OSG -DWITH_OSGEARTH -Wno-overloaded-virtual -include inet/common/precompiled_release.h  -DINET_EXPORT -I. -I/home/baa4hi/omnest-5.1.1/include
*** LINKING with:
g++ -shared -fPIC -o ../out/gcc-release/src/libINET.so -Wl,--no-as-needed -Wl,--whole-archive  -Wl,--no-whole-archive -loppenvir -loppsim -ldl -lstdc++  -lOpenThreads -losg -losgText -losgDB -losgEarth -losgEarthUtil -Wl,-rpath,/home/baa4hi/omnest-5.1.1/lib -Wl,-rpath,/lib -Wl,-rpath,.  -L/home/baa4hi/omnest-5.1.1/lib
Building...
[ 14%] Built target build_inet
[ 15%] Building Veins (external dependency)
[ 15%] Built target build_veins
[ 63%] Built target core
[ 78%] Built target envmod
[100%] Built target storyboard
Scanning dependencies of target run_example
OMNEST Discrete Event Simulation  (C) 1992-2017 Andras Varga, OpenSim Ltd.
Version: 5.1.1, build: 170508-adbabd0, edition: Commercial Edition
See the license for distribution terms and warranty disclaimer

Setting up Qtenv...

Loading NED files from /home/baa4hi/artery/src/artery:  41
Loading NED files from /home/baa4hi/artery/src/traci:  10
Loading NED files from /home/baa4hi/artery/extern/veins/examples/veins:  1
Loading NED files from /home/baa4hi/artery/extern/veins/src/veins:  33
Loading NED files from /home/baa4hi/artery/extern/inet/src:  666
Loading NED files from /home/baa4hi/artery/extern/inet/examples:  174
Loading NED files from /home/baa4hi/artery/extern/inet/tutorials:  19
Loading NED files from /home/baa4hi/artery/extern/inet/showcases:  33

Loading images from './bitmaps': *: 0 
Loading images from './images': *: 0 
Loading images from '/home/baa4hi/omnest-5.1.1/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 

Loading configuration... done.

[Warning: Program was compiled without debug info, ignoring debug-on-error=true setting.]
`

Sumo is starting without trouble. 
I think something with my installation is still wrong. 
I make Veins, INET and Vanetza out of the Artery root dir. 
In case off make all i got the error that Omnet find some "release" and some "debug" versions. 
So i must create INET with make INET MODE=release. 

I m very interested in to use Artery, but the installation is more difficult than I thought.

Regards, 
Bargmann

**Comment by riebl** [comment]
Sounds like failing coordinate conversion. Please check if your SUMO is compiled with `PROJ` feature, i.e. look at output of `sumo --version` or the "About SUMO" dialog window (Help -> About).

**Comment by bargmann** [comment]
I think you are right. 
``SUMO Version 0.30.0
 Build features: x86_64-unknown-linux-gnu TRACI GUI
 Copyright (C) 2001-2017 DLR and contributors; http://sumo.`

**Comment by bargmann** [comment]
How should the message look like?

**Comment by riebl** [comment]
@bargmann My SUMO outputs `Build features: x86_64-unknown-linux-gnu TRACI PROJ GDAL GUI`. Just install the proj4 development headers (the package is named libproj-dev on Ubuntu afaik), then configure and build SUMO again.

**Comment by bargmann** [comment]
Thanks for your SUMO outputs. I have already installed these libraries. When i run `./configure` without or with the possible options i get that this: 
"Optional features summary
Enabled: TRACI PROJ GDAL GUI"
But after make they are not used. I keep searching. 
Which Sumo Version are you using? 
I use the version 0.30.0.

**Comment by riebl** [comment]
Right now I am still using 0.31 but any recent version should work (I am confident about 0.30). Maybe your PATH is still pointing at another SUMO binary?

**Comment by bargmann** [comment]
Again, your hint was very helpful. Thanks a lot for your very fast and useful support. 
It was necessary to make an `make uninstall`. In my naive mind i thought it is enough to do `make clean ; ./configure; make and make install` . The run_example is running now.
