### ISSUE TITLE
pcap recording

### ISSUE THREAD

**Issue by vonmuenchow** [riebl/artery#140]
Hi,
I have a simple scenario with a single RSU und several vehicles sending out CAMs.
At the moment I record the station ID and vehicle speed as vectors in a .vec-file, which works fine.
But the first problem with this is, that I can't assign the speed to a specific vehicle anymore.
Secondly I can't record the path history stored in the CAM (or at least I don't know how to do this).

What I would like to do instead is to record all CAMs received from the RSU and store these messages in a seperate file for later analysis.
As far as I understand, INET is capable of recording messages as pcap-files, which would be perfect for my use-case.
To do so I added the following lines in my config but no recorder shows up in Omnet++

<pre><code>*.rsu[*].numPcapRecorders = 1
*.rsu[*].pcapRecorder[*].pcapLinkType = 105 # 802.11
*.rsu[*].pcapRecorder[*].pcapFile = "results/rsu.pcap"
</code></pre>

So my questions are:
1. Is it (at the moment) possible to record received CAMs in pcap format with Artery?
2. If the answer is yes: What do I have to consider? Or what am I doing wrong right now?
3. If the answer is no: What would be the best way to extract and store station ID, speed, position and path history as a tuple? BTW: The RSU is just a data sink (so I could replace it with something else that can receive CAMs).

Best reguards
Max

Note:
In generel I'm new to artery and network simulation. So I'm figuring out how everything works and how to get use out of it.
And if it matters: I'm using Artery via the provided virtual machine.

**Comment by vonmuenchow** [comment]
I just found the solution in issue #105!

**Comment by xrispa-m** [comment]
@vonmuenchow could you please elaborate on how you were able to use the INET pcap recorder to record the messages from Artery?
