### ISSUE TITLE
Bind issue on GlobalEnvironmentModel.cc while running (make run_example)

### ISSUE THREAD

**Issue by gsohan** [riebl/artery#144]
Hello,

I successfully installed artery on Ubuntu 18.04. following all the instructions given on the website. But when I tried to run an example, i got the bind issue on GlobalEnvironmentModel.cc. I also tried vagrant but end up getting the same issue. I have attached the screenshot of the issue here.
![Capture](https://user-images.githubusercontent.com/15043439/101086905-200c7600-3577-11eb-8fbe-edd5a1c6c13c.PNG)
](url)

**Comment by riebl** [comment]
Thanks for reporting this issue @gsohan. Please fetch the latest update from the master branch and try again. It would be nice if you could verify that this workaround solves the problem.

**Comment by gsohan** [comment]
Thank you. It works now.
