### ISSUE TITLE
Pedestrian detection and communication

### ISSUE THREAD

**Issue by vandit86** [riebl/artery#145]
Hi ! 

Is it possible to detect a pedestrian by vehicle's sensor with Artery? And communicate with the pedestrians ?? I don't found any example with pedestrians generated by the SUMO. 

Thank you ..

**Comment by riebl** [comment]
Dear @vandit86,

adding pedestrians to Artery should be feasible without too much effort. I have not worked on this yet, however.
Detection of pedestrians would be possible as soon as "SUMO persons" are added to the `GlobalEnvironmentModel`.
For the communication part, `BasicNodeManager` would need to create OMNeT++ module instances for pedestrians similar to how it handles vehicles at the moment.

**Comment by vandit86** [comment]
Thank you , @riebl  for the quick answer.

**Comment by riebl** [comment]
For future reference: `BasicNodeManager` can handle pedestrians meanwhile.

**Comment by akhilsimha7** [comment]
Was anyone able to implement this? I want the pedestrians to be detected by Radars, but currently, I am not able to implement it by adding person in `GlobalEnvironmentModel`.
