### ISSUE TITLE
Can I set a fixed packet size for CAM messages? 

### ISSUE THREAD

**Issue by aash92** [riebl/artery#148]
Hello team,
I am new to using Artery. I am trying to analyze the CAM generation behaviour in different traffic environments. 
Hence I am using Artery for simulating these scenarios. However, in my simulation, I noticed that two different sizes of packets is being transmitted. To make my analysis easy, I would like a fixed packet size. Hence is there a way to fix the message packet size. If so could you let me know in which file do I need to access to do this?
I have attached a screenshot to show you the two different packets that are being transmitted.

![ArteryCAMPacketSize](https://user-images.githubusercontent.com/35331573/103757676-6428e580-5011-11eb-83db-dfe30624e6f8.png)

Thank you
Best regards
Aashik

**Comment by riebl** [comment]
Dear Aaashik,

at the moment, you cannot fix the CAM packet sizes by a configuration option. However, you could set the `scLowFrequencyContainerInterval` constant in `CaService.cc` to 100ms. Then, every CAM will have a low frequency container and the observed sizes should become equal.

**Comment by aash92** [comment]
Thank you Raphael,
I'll try that.
