### ISSUE TITLE
Ansible failure within vagrant provisioning

### ISSUE THREAD

**Issue by jweadick** [riebl/artery#150]
Hi Riebl,

I'm currently trying to download the Artery VM to my new laptop, but am receiving this error during the vagrant provisioning process. Do you have any idea on what the issue is? 

"
TASK [omnetpp : delete deprecated /opt/omnetpp directory] **********************
skipping: [default]

fatal: [default]: FAILED! => {"changed": false, "msg": "The checksum for /home/vagrant/omnetpp-5.6.2-src-linux.tgz did not match 6a9a027f39044c56333318e71e52f97b; it was 7f2a46d6fee0c3421d834bf9ab1d0e0c."}
        to retry, use: --limit @/vagrant/ansible/vagrant.retry
"

Thanks,

Josh Weadick

**Comment by riebl** [comment]
Hi Josh,

I suppose something went wrong while downloading the `omnetpp-5.6.2-src-linux.tgz` archive. On my test system, the checksum is as expected. You may just delete the corrupted archive in /home/vagrant and restart Vagrant's provisioning via `vagrant up --provision`. Cross your fingers and hope for download without errors then.
