### ISSUE TITLE
Running multiple different scenarios in parallel. [multithreading]

### ISSUE THREAD

**Issue by Tuntenfisch** [riebl/artery#151]
Hello,

I'm currently working on an university project in which I am evaluating the travel time of  an emergency vehicle with different penetration rates of V2V. 

We have already implemented a DEN UseCase in which the emergency vehicle periodically (default: 10Hz) sends out DENM to V2V enabled vehicles which will yield if deemed necessary.

In total we are running 3 different traffic scenarios through SUMO, modelling "morning", "midday" and "evening" traffic respectively. The road network is the same for all scenarios.

Every scenario is run 12 times, each run having a different penetration rate of V2V set through Artery's [Services](http://artery.v2x-research.eu/features/middleware/#Services) feature. So that totals
`3 (scenarios) * 12 (penetration rates) = 36 (runs)`

Right now I'm running them all consecutively with a Python script that, each time a run starts,

1.  modifies the `.sumocfg` linked in the target's `omnetpp.ini` to include the correct traffic scenario, i. e. "morning", "midday", "evening",
2. modifies the `services.xml` linked in the target's `omnetpp.ini` to include the correct penetration rate
3. executes the following terminal commands to run the scenario
    
    ```
    mkdir -p build
    cd build
    cmake ..
    cmake -DCMAKE_BUILD_TYPE="Release" -DRUN_FLAGS="-uCmdenv" --build .
    make run_<redacted>
    ```

In total it took me approximately 24 hours to complete all 36 runs on an i7700k. I'm now trying to run multiple individual runs in parallel to speed things up. For that I am creating temporary `.sumocfg`, `services.xml` and `omnetpp.ini` files for each run.

The temporary `omnetpp.ini` will link to both the temporary `.sumocfg` and `services.xml`. The last part missing is the 3rd step from above. I need to somehow point OMNeT++ to use my temporary OMNeT++ `.ini` instead of the default one. But as far as I am aware, I cannot specify that `.ini` with OMNeT++ -f  option inside the "RUN_FLAGS" above, since that would affect all runs and could lead to race conditions, I think.

My current idea is to somehow create a custom run target with `add_opp_run` for each of the 36 runs, but I'm not sure how.

I also looked at OMNeT++ `opp_runall` Python script but since the dependencies of Artery are different I didn't go down that approach yet.

Do you have any advice on how to approach this problem?

Kind regards,
...

**Comment by kenog** [comment]
Hi,

if I understand you correctly, you are doing this a bit too complicated. The [Omnet documentation](https://doc.omnetpp.org/omnetpp/manual/#cha:config-sim) describes, how you can parametrise you simulations. You can then just have three different SUMO scenarios for example and create three different sections in the `omnetpp.ini` file, each of which sets a different value for the parameter `*.traci.launcher.sumocfg`.
Then you can use `opp_run` to start the different simulations. 

Regarding parallel execution: There are probably multiple ways to do this. The following is what we use and it works quite conveniently.
I wrote a small shell script which takes the scenario name, the section name and the run number and calls `opp_run` accordingly (to see how it needs to be called, you can have a look at the `make` target `run_<redacted>`, to find out the run numbers of your configurations, you can use `opp_run -f path/to/omnetpp.ini -c name-of-your-config-section -q runs`).
Once you did this, it is just a matter of calling this script for all runs you want to simulate. For this [GNU Parallel](https://www.gnu.org/software/parallel/) might be worth to check out. We use [SLURM](https://slurm.schedmd.com/documentation.html) at the institute but that is a bit more involved to set up.

Best regards
Keno

**Comment by riebl** [comment]
Keno gave you already some good hints to reduce the amount of (partially) redundant configuration files. You may also be interested in the `run_artery.sh` script, which is generated in Artery's build directory. You can pass arbitrary options to this shell script, e.g. `run_artery.sh -f your_omnetpp.ini -c your_config -r 0`, without worrying about Artery's dependencies.

**Comment by Tuntenfisch** [comment]
@kenog: Thank you for your help. I agree that having 3 different SUMO scenarios and 3 different OMNeT++ config sections respectively would work. 

As far as the penetration rates go, those are defined in the following, separate XML file
```
<?xml version="1.0" encoding="utf-8"?>
<services>
    <service type="artery.application.DenService">
        <listener port="2002"/>
        <filters>
            <penetration rate="1.0"/>
            <name pattern="EmVeh"/>
        </filters>
    </service>
</services>
```
and linked inside the `omnetpp.ini` with
```
*.node[*].middleware.services = xmldoc("omnetpp/services.xml")
```
I looked through the OMNeT++ documentation link you provided and found that OMNeT++ does provide a feature for generating different runs with different parameters (see [link](https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:parameter-studies)). But I don't think this feature allows me to modify what's inside the `services.xml` itself and I don't think I can access the penetration rate in the `omnetpp.ini` itself.

I could probably get away with creating 12 different `service.xml` files, each containing it's own penetration rate and doing something like
```
*.node[*].middleware.services = xmldoc(${"services_0.0.xml", "services_0.05.xml", "services_0.1.xml", ...})
```
inside the `omnetpp.ini`.

That way I would only need 15 different files:

- 3 `.sumocfg` for my 3 different traffic scenarios
- 12 `services.xml` for my 12 different penetration rates

With this approach I might even get away with having a single config section like so
```
[Config Main]
*.traci.launcher.sumocfg = ${"morning_traffic.sumocfg", "midday_traffic.sumocfg", "evening_traffic.sumocfg"}
*.node[*].middleware.services = xmldoc(${"services_0.0.xml", "services_0.05.xml", "services_0.1.xml", ...})
```

One thing I didn't mention yet is that inside my `.sumocfg` I log `tripinfo-output` like so
```
<tripinfo-output value="logs/scenario_<scenario>_penetration_rate_<penetration_rate>.xml"/>
```
which means my `.sumocfg` is dependant on both the traffic scenario and the penetration rate. Unless I can specify the tripinfo-output somehow over the terminal with `--tripinfo-output` (see [link](https://sumo.dlr.de/docs/sumo.html)) I would again need 
```
3 (scenarios) * 12 (penetration rates) = 36 (.sumocfg files)
```
 Perhaps @riebl knows if it's possible to pass SUMO command line args with the `run_artery.sh` script.

@riebl: Thank you, I think this is the missing piece I needed to link to the correct OMNeT++ `.ini`.

**Comment by Tuntenfisch** [comment]
@riebl: One issue I've encountered with `run_artery.sh` is that it cannot find the `.ned``file for my implemented DEN UseCase:
```
<!> Error: NED module type "EmVehApproachingUseCase" not found (fully qualified type name expected) -- in module (artery::DenService) World.node[2].middleware.DenService (id=224)
```
When running the scenario with
```
cmake --build build --target run_<redacted>
```
it works fine. My `den_use_case.xml` is
```
<?xml version="1.0" encoding="UTF-8"?>
<usecases>
    <usecase type="EmVehApproachingUseCase"/>
</usecases>
```
The `.ned` file for `EmVehApproachingUseCase` is
```
import artery.application.den.UseCase;

simple EmVehApproachingUseCase like UseCase
{
    @class(EmVehApproachingUseCase);

    xml net;
    
    double denmRelevanceRadius = default(250.0);
    double denmTransmitFrequency = default(10.0);
    double denmReactionPeriod = default(0.5);
    double stoppingDistanceSafetyCushion = default(5.0);
    double stoppingDistanceInterval = default(5.0);
    double evacuationZoneRadius = default(20.0);
    double fieldOfViewAngle = default(180.0);
}
```

**Comment by Tuntenfisch** [comment]
Okay when I specify `ned-path` inside my `omnetpp.ini` and call `run_artery.sh` with `-l <shared_library>` it works.

**Comment by riebl** [comment]
You can assign `--tripinfo-output=whatever` to `*.traci.launcher.extraOptions` in your omnetpp.ini. I am glad that you have figured out how to pass additional NED paths as `run_artery.sh` has only those NED paths required for Artery itself.

**Comment by Tuntenfisch** [comment]
@riebl, @kenog: Thank you for your support. I'll close this issue!
