### ISSUE TITLE
Cannot run the artery example

### ISSUE THREAD

**Issue by ron1090** [riebl/artery#153]
Dear @riebl 
My name is Ron, and I'm considering to use the framework Artery for my university's final project on C-V2X. 

So far I've installed the packages on both a stand-alone ubuntu VM using the manual process, and the VM created using the ansible script. Both give me the same error after Artery's build finishes: 
`ron1090@ron1090:~/artery/build$ make run_example
[ 53%] Built target INET
[ 54%] Built target traci
[ 59%] Built target veins
[ 59%] Built target common
[ 59%] Built target net
[ 59%] Built target access
[ 62%] Built target asn1_support
[ 76%] Built target asn1_its
[ 76%] Built target asn1
[ 84%] Built target asn1_pki
[ 89%] Built target asn1_security
[ 90%] Built target security
[ 91%] Built target dcc
[ 93%] Built target geonet
[ 94%] Built target btp
[ 95%] Built target facilities
[ 95%] Built target gnss
[100%] Built target core
OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

<!> Error: Cannot load library '/home/ron1090/artery/build/src/traci/libtraci.so': /home/ron1090/artery/build/src/traci/libtraci.so: undefined symbol: _ZNK6artery5Angle6radianEv

End.
make[3]: *** [scenarios/artery/CMakeFiles/run_example.dir/build.make:57: scenarios/artery/CMakeFiles/run_example] Error 1
make[2]: *** [CMakeFiles/Makefile2:1267: scenarios/artery/CMakeFiles/run_example.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1274: scenarios/artery/CMakeFiles/run_example.dir/rule] Error 2
make: *** [Makefile:474: run_example] Error 2
`

This is the image from the Debian VM instead: 
![image](https://user-images.githubusercontent.com/77664439/105044443-06f84f80-5a67-11eb-83a9-c4089a1a94b1.png)

while using the Ubuntu VM I might have doubted about some wrong settings, the ansible script, once finished, give me no clue on how to fix this problem. 
Do you have any solution about that? 

Any support would be really helpful, since the tool would be perfect for my use-case.

Thanks in advance. 

Regards, 

Ron

**Comment by riebl** [comment]
Hi @ron1090,

this seems to be a regression bug caused by commit 8bea923. It works with one commit earlier, i.e. 0a8a52ee.
You may just use this earlier commit until I have found a permanent fix.

BR, Raphael
