### ISSUE TITLE
Vagrant up not working

### ISSUE THREAD

**Issue by NagoreIturbe** [riebl/artery#155]
I am trying to install Artery through the automated creation of a virtual machine, for that I have followed the instructions on "http://artery.v2x-research.eu/install/#automated-creation-of-a-virtual-machine" but when I run "vagrant up" the following error occurs:

TASK [artery-workspace : clone Artery repository] ******************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin vagrant file:///vagrant/.git /home/vagrant/artery", "msg": "Cloning into '/home/vagrant/artery'...\nfatal: '/vagrant/.git' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/home/vagrant/artery'...\nfatal: '/vagrant/.git' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/home/vagrant/artery'...", "fatal: '/vagrant/.git' does not appear to be a git repository", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/ansible/vagrant.retry

PLAY RECAP *********************************************************************
default                    : ok=13   changed=9    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I am running vagrant in a 64bit windows computer, I have tried multiple things but I find myself unable to solve this issue and I would much appreciate a little bit of help here.

Thanks beforehand.

**Comment by riebl** [comment]
Can you confirm that the `.git` directory exists in the directory on your host machine where `Vagrantfile` is located?

**Comment by NagoreIturbe** [comment]
Thanks for the fast reply!

There is no .git in the .zip that I downloaded, but there are .gitattributes, .gitignore and .gitmodules files.

**Comment by riebl** [comment]
You need to clone the git repository on your machine, it will not work with a ZIP archive.

**Comment by NagoreIturbe** [comment]
Thank you, very much, I have installed Artery virtual machine, but when I execute the examples runtime errors occur.

For example when I try to execute rsu_grid the following runtime error occurs:


![Capture](https://user-images.githubusercontent.com/68902421/107043587-82763280-67c3-11eb-9beb-ac1daab197af.PNG)

**Comment by riebl** [comment]
Thank you for reporting this issue. It seems to be a regression bug introduced with 8bea923a. I am looking for a way to fix this as soon as possible. Meanwhile, you can just switch to 0a8a52eea, which is a slightly older version of Artery.

**Comment by NagoreIturbe** [comment]
Okay, thank you very much for everything!

**Comment by riebl** [comment]
For the record: The described problem does not occur with CMake 3.17 and later. For earlier CMake versions a workaround is now in place as of commit 02e77312.
