### ISSUE TITLE
How to lunch lte-blackice scenario

### ISSUE THREAD

**Issue by niturbe** [riebl/artery#159]
I am trying to launch lte-blackice scenario going to the artery-build folder and using "make run_lte-blackice" and the following error occurs "make: *** No rule to make target -run_lte-blackice. Stop.". I have tried multiple combinations but the same thing happens.

**Comment by riebl** [comment]
The run target is called `run_lte_blackice`. It Is available if the CMake options `WITH_SIMULTE` and `WITH_STORYBOARD` are enabled.

**Comment by niturbe** [comment]
Thank you for the fast reply!

I have enabled WITH_SIMULTE and WITH_STORYBOARD in the CMakeCache.txt but I get the same error.

**Comment by riebl** [comment]
I recommend to change the CMake cache either with ccmake or cmake-gui as those will re-generate the makefiles automatically then as well. You can manually trigger this by invoking `cmake <your build directory>`.

**Comment by niturbe** [comment]
Thank you very much!
