### ISSUE TITLE
after my command make run_example its is giving as

### ISSUE THREAD

**Issue by Aku1895** [riebl/artery#161]
HP-Pavilion-x360-Convertible:~/artery/build$ make run_example
[ 52%] Built target INET
[ 53%] Built target traci
[ 58%] Built target veins
[ 58%] Built target common
[ 58%] Built target net
[ 58%] Built target access
[ 61%] Built target asn1_support
[ 74%] Built target asn1_its
[ 79%] Built target asn1_security
[ 87%] Built target asn1_pki
[ 87%] Built target asn1
[ 89%] Built target security
[ 90%] Built target dcc
[ 92%] Built target geonet
[ 93%] Built target btp
[ 93%] Built target facilities
[ 93%] Built target gnss
[ 97%] Built target core
[ 98%] Built target envmod
[100%] Built target storyboard
OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Qtenv...

Loading NED files from /home/artery/src/artery:  93
Loading NED files from /home/artery/src/traci:  21
Loading NED files from /home/artery/extern/veins/examples/veins:  1
Loading NED files from /home/artery/extern/veins/src/veins:  43
Loading NED files from /home/artery/extern/inet/src:  666
Loading NED files from /home/artery/extern/inet/examples:  174
Loading NED files from /home/artery/extern/inet/tutorials:  19
Loading NED files from /home/artery/extern/inet/showcases:  33

Loading images from './bitmaps': *: 0 
Loading images from './images': *: 0 
Loading images from '/home/akash/omnetpp-5.6.2/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 

Loading configuration ... done.
Error: Could not build output file 'results/sumo-0.log' (No such file or directory).
Quitting (on error).
Killed
scenarios/artery/CMakeFiles/run_example.dir/build.make:57: recipe for target 'scenarios/artery/CMakeFiles/run_example' failed
make[3]: *** [scenarios/artery/CMakeFiles/run_example] Error 137
CMakeFiles/Makefile2:1400: recipe for target 'scenarios/artery/CMakeFiles/run_example.dir/all' failed
make[2]: *** [scenarios/artery/CMakeFiles/run_example.dir/all] Error 2
CMakeFiles/Makefile2:1407: recipe for target 'scenarios/artery/CMakeFiles/run_example.dir/rule' failed
make[1]: *** [scenarios/artery/CMakeFiles/run_example.dir/rule] Error 2
Makefile:474: recipe for target 'run_example' failed
make: *** [run_example] Error 2

**Comment by riebl** [comment]
I have just fixed this issue with commit c4d0995d. Thanks for reporting this issue.
