### ISSUE TITLE
Adaptive ETSI and Dual-α algorithms.

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#162]
Hi @riebl, 

the Adaptive ETSI approach and Dual-α algorithms, are they already implemented in Artery? 
If yes, where can I find them?

Thanks a lot.

**Comment by QuentinDLZ** [comment]
Hi @SamirRachedi,
Yes, it is already implemented. You can take a look at master/src/artery/networking/LimericDccEntity.ned.
The parameter to enable/disable Dual-alpha algorithm (based on paper https://ieeexplore.ieee.org/document/8671471) is "enableDualAlpha"

**Comment by riebl** [comment]
Completely answered by @QuentinDLZ, thanks!
