### ISSUE TITLE
After "make run_example" in artery Omnet++/Qtenv is openeing 

### ISSUE THREAD

**Issue by Aku1895** [riebl/artery#164]
After "make run_example" in artery Omnet++/Qtenv is openeing 
in that if i click on run its runs and in terminal it gives as 
*************************************************************************************************************
/artery/build$ make run_example
[ 52%] Built target INET
[ 53%] Built target traci
[ 58%] Built target veins
[ 58%] Built target common
[ 58%] Built target net
[ 58%] Built target access
[ 61%] Built target asn1_support
[ 74%] Built target asn1_its
[ 79%] Built target asn1_security
[ 87%] Built target asn1_pki
[ 87%] Built target asn1
[ 89%] Built target security
[ 90%] Built target dcc
[ 92%] Built target geonet
[ 93%] Built target btp
[ 93%] Built target facilities
[ 93%] Built target gnss
[ 97%] Built target core
[ 98%] Built target envmod
[100%] Built target storyboard
OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Qtenv...

Loading NED files from /home/artery/src/artery:  93
Loading NED files from /home/artery/src/traci:  21
Loading NED files from /home/artery/extern/veins/examples/veins:  1
Loading NED files from /home/artery/extern/veins/src/veins:  43
Loading NED files from /home/artery/extern/inet/src:  666
Loading NED files from /home/artery/extern/inet/examples:  174
Loading NED files from /home/artery/extern/inet/tutorials:  19
Loading NED files from /home/artery/extern/inet/showcases:  33

Loading images from './bitmaps': *: 0 
Loading images from './images': *: 0 
Loading images from '/home/omnetpp-5.6.2/images': *: 0  abstract/*: 90  background/*: 4  block/*: 320  device/*: 195  logo/*: 1  maps/*: 9  misc/*: 70  msg/*: 55  old/*: 111  status/*: 28 

Loading configuration ... done.
*************************************************************************************************************
Then after clicking on stop the simulation and i want to close the omnet++ so it gives as
------------------------------------------------------------------
Do you want to conclude the simulation by invoking finish() before exiting ?
---------------------------------------------------------------------------------------------------------
how to invoke finish()..?

**Comment by riebl** [comment]
OMNeT++ is asking you if it shall invoke `finish` before exiting. So just answer this dialog by clicking *Yes* then. You don't have to call `finish` manually.
