### ISSUE TITLE
scenarios

### ISSUE THREAD

**Issue by Aku1895** [riebl/artery#165]
There are 2 scenarios in artery.
one in build/scenarious/artery/ directory
second in artery/scenarios directory

I am running make run_example in build directory

What should i do if i want to run artery/scenarios files..

how can i run it..??

**Comment by riebl** [comment]
Just ignore *build/scenarios/artery* as these files are generated by CMake. These files are not a "scenario" at all. Calling `make run_example` runs the scenario located at *scenarios/artery*.

**Comment by Aku1895** [comment]
/artery/scenarios/artery$ make run_example
make: *** No rule to make target 'run_example'.  Stop

i am getting like this

**Comment by riebl** [comment]
`make run_example` is called from the build directory, where the *Makefile* generated by CMake lies.
