### ISSUE TITLE
Artery Build issues on Ubuntu 20.04 lts

### ISSUE THREAD

**Issue by divakar5** [riebl/artery#169]
I got this error at the very final stage of Artery Build, I searched about this but no help yet.
Could you please see if you have an idea on this? I have installed all the necessary dependencies to build artery.

divakar@divakar:~/artery/build$ cmake --build .
[  0%] Generating ../extern/inet/.oppfeaturestate
/bin/sh: 1: ./inet_featuretool: Permission denied
make[2]: *** [CMakeFiles/INET.dir/build.make:927: ../extern/inet/.oppfeaturestate] Error 126
make[1]: *** [CMakeFiles/Makefile2:563: CMakeFiles/INET.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

![Artery build issue](https://user-images.githubusercontent.com/80413167/110662470-8bf02180-81eb-11eb-9b26-aa3a5c3faab9.PNG)

**Comment by riebl** [comment]
Possibly the script `inet_featuretool` is simply lacking execution permissions, for whatever reason. You can add these permissions via `chmod +x extern/inet/inet_featuretool` called from Artery's root directory.

**Comment by divakar5** [comment]
Thanks for the quick support!

I tried the above solution you mentioned, after that I'm getting another error as 

divakar@divakar:~/artery/build$ cmake --build .
[  0%] Generating ../extern/inet/.oppfeaturestate
/usr/bin/env: ‘python3\r’: No such file or directory
make[2]: *** [CMakeFiles/INET.dir/build.make:927: ../extern/inet/.oppfeaturestate] Error 127
make[1]: *** [CMakeFiles/Makefile2:563: CMakeFiles/INET.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

![Artery build issue 2](https://user-images.githubusercontent.com/80413167/110765693-737b1800-827a-11eb-8372-82c93b213085.PNG)

**Comment by riebl** [comment]
Install python3 on your system then.

**Comment by divakar5** [comment]
Hi, I already have python 3.8.5 and i also had python 2..7 hence after the above error I removed python 2.7. still I'm having the same error.

**Comment by riebl** [comment]
Maybe this answer helps you: https://askubuntu.com/a/896880
Seems like your git clone completely went wrong as file permissions and line endings are broken. I suggest cloning the repository again.

**Comment by divakar5** [comment]
Sure Sir, I'll clone the repo again and let you know the result. Thanks for the help, much appreciated!

**Comment by divakar5** [comment]
Hi Sir, The issue resolved, as you told it was due to corruption of the Git clone. after recloning, the issue got resolved.
I tried simulating an Artery example, only Qtenv popped but Sumo didn't get started, I added the below line in Omnetpp.ini (veins example).

*.traci.launcher.sumo = "sumo-gui"


Note: (I have already installed sumo)

your guidance will be much appreciated, thank you

**Comment by riebl** [comment]
Do you see any error messages in the logging panel? Is SUMO really not started or just without GUI?

**Comment by divakar5** [comment]
There were no errors and Sumo didn't start at all. Qtenv worked as expected.

**Comment by riebl** [comment]
No error message and no vehicle nodes on the Qtenv canvas? I have no idea how I could help you with this little information.

**Comment by divakar5** [comment]
Hi Sir, I tried simulating Veins Example. I also launched sumo using the script but after triggering 'run' on Qtenv I'm facing below errors.
![Sumo launch error for veins example](https://user-images.githubusercontent.com/80413167/110955831-ffbb3700-836f-11eb-9962-656213bb78d0.PNG)
![VeinsExample_error](https://user-images.githubusercontent.com/80413167/110955837-0053cd80-8370-11eb-9c52-421c7f908904.PNG)

**Comment by riebl** [comment]
You are not using Artery but Veins. Neither `sumo-launchd.py` nor `veins::TraCIScenarioManagerLaunchd` are related to Artery. You should ask questions related to Veins at their project site.
