### ISSUE TITLE
Scenario in Cmdenv not working

### ISSUE THREAD

**Issue by Lock-up** [riebl/artery#172]
Hi,
I am trying to run my scenario in the Cmdenv. In Qtenv it is working fine.
To run in Cmdenv I added following properties to the `[General]` section in my omnetpp.ini:
```
user-interface = Cmdenv
cmdenv-interactive = true
cmdenv-express-mode = false
```

As soon as a vehicle gets generated the following is applied:
`*.node[*].middleware.services = xmldoc("services.xml")`

This works in Qtenv but in Cmdenv the terminal asks for input:
`Enter parameter 'World.node[5].middleware.services' (unassigned):`

After entering `xmldoc("services.xml")` the simulation keeps on running till next vehicle get generated.

Any ideas?

**Comment by riebl** [comment]
So far, I have not been aware of the `user-interface` parameter. I set the CMake variable *RUN_FLAGS* to *-u Cmdenv* to run simulations on the command line. It looks as if `user-interface` is a rarely used OMNeT++ feature, so there may be an undiscovered bug related to it. However, Artery cannot do much about it then.

**Comment by Lock-up** [comment]
Thank you @riebl, using _RUN_FLAGS_ works.
