### ISSUE TITLE
Recording sensor data as vector file in highway_police scenario(Help wanted)

### ISSUE THREAD

**Issue by gsohan** [riebl/artery#175]
Hello,

I am currently working on highway_police scenario to understand the working of local environment mode sensor in Artery. I want to record the local environment sensor detection as vector file. I am working with the radar sensor similar to the example. I added one line in Car.ned file in ../artery/envmod/ as:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/15043439/114418952-9d28a700-9b78-11eb-82ff-968bb2501250.png">

I want to record the sensor data from all the vehicles equipped with sensor in artery simulation. Can you please provide me some suggestions based on above code, if it is correct way to do or is there any other way to obtain sensor data in vector file format?

I have some more questions regarding sensor data: (A) Can artery radar sensor distinguish different objects such as car, tree, building? 
                                       (B) Can artery radar sensor tell the position of the detected objects?

Your suggestions will be highly appreciated. Looking forward to your suggestions.

Best

**Comment by riebl** [comment]
This refresh signal is not useful for gathering sensor data, it just indicates that the environment has changed. The sensor models themselves do not emit any signals at the moment, which could be used to record statistics. Feel free to extend them, though.
Have a look at the `EnvmodPrinter` service, which queries the local environment model. You can easily record vectors with sensor data or emit signals for `@statistic` from a similar service.

A) at the moment detected objects are reported as `EnvironmentModelObject`, i.e. any type of vehicle. It should be possible without too much effort to add static obstacles like trees and buildings to the list of detected objects. So far, we had simply no need for these objects types in our use cases.
B) Yes, see `EnvironmentModelObject` for the available attributes including the `VehicleDataProvider`. Actually, you can retrieve more attributes in Artery than with a real sensor. It is up to you to limit yourself realistically ;-)

**Comment by gsohan** [comment]
Thank you so much for the information. I will start working on it.

**Comment by gsohan** [comment]
Hi Riebl,
I am still having trouble in recording the sensor data. I am using cOutVector to record the sensor vector data. I have added the following lines in ../artery/envmod/service/EnvmodPrinter.cc
<img width="352" alt="image" src="https://user-images.githubusercontent.com/15043439/117373312-9dbf0f80-ae90-11eb-9e04-7becf236a0c3.png">

The build runs fine but I don't see any vector record with name 'sensorVector' or id. I don't know if cOutVector is a correct way to record the sensor data or if there is another way to record the sensor data in vector file. Your help will be highly appreciated.

Thank you so much!

**Comment by riebl** [comment]
You have to assign a name to your `cOutVector` either by passing the name to its constructor or calling its `setName` method before any `record` call.

**Comment by gsohan** [comment]
Hi Riebl, Thank you for the quick response. I was able to record the vector data for PoliceService.cc (for highway_police scenario). Actually, I wanted to record the vector data from PoliceServiceEnvmod.cc, but i was not able to do so. I checked the code and it seems cmake is not running the storyboard and envmod code. I went to build directory, and set the "With_envmod" variable to "ON" (in CMakeCache.txt); but still I didnot get the result. 

How to enable PoliceServiceEnvmod.cc in cmake build for highway_police scenario? (I havenot modified the default example code)
Your suggestions will be highly appreciated.

Thank you so much!

**Comment by riebl** [comment]
As you have already figured out, *PoliceServiceEnvmod.cc* is compiled only if the CMake variable `WITH_ENVMOD` (all uppercase) is set. Do not forget to re-build Artery with your updated CMake configuration, i.e. invoke `make` in the build directory.

**Comment by riebl** [comment]
I recommend `ccmake` or `cmake-gui` for editing the CMake build directory configuration. Lines such as `set(WITH _ENVMOD ON)` are not the intended way how you should use CMake.

**Comment by gsohan** [comment]
Thank you so much for your suggestions. I was finally able to record the sensor data.
