### ISSUE TITLE
display cam data

### ISSUE THREAD

**Issue by ghadi89** [riebl/artery#178]
Hi , 
I am new to artery , I want to display message CAM information, I did show some information for vehicles, but I cannot do the same for the roadside unit, I know that they use different type of highfrequancy container, is there is any solution to show the CAMs received by the RSU,
Thanks in advance!

**Comment by riebl** [comment]
Hi @ghadi89,

I am a little bit confused about what you are referring to. Do you want to display CAM information in the GUI? Both `CaService` and `RsuCaService` emit the same `CaObject` on reception of a CAM; there is no difference in this regard. Neither of these services has any particular visualisation code.

**Comment by ghadi89** [comment]
my problem is that i cannot record the information related to 'e.g **camStationId** (reception and transmission)' although it's exist in RsuCaService.ned so my file "result.anf" do not include any information about these vectors .
the line i added to my omnetpp.ini to record these info is : 
***.rsu*.middleware.artery.application.RsuCaService.reception.result-recording-modes = all**

**Comment by riebl** [comment]
I have added `*.rsu[*].**.RsuCaService.reception.result-recording-modes = all` and see the expected CAM vectors in my result file. Using the *inet_rsu* configuration of the example scenario, *rsu[0]* receives the first CAM at about 80.8s.

**Comment by ghadi89** [comment]
i just fixed it , thank you sir
