### ISSUE TITLE
Artery for UAV use case

### ISSUE THREAD

**Issue by mc-2021** [riebl/artery#180]
Hi Riebl,

I have used Artery with OMNeT ++ / SUMO to simulate V2V services.
Now, if we condider UAV use case, I would like to know if Artery presents the necessary communications modules to communicate drones and add specific services.

Thank you

**Comment by riebl** [comment]
To be honest, I don't know if UAVs need any special kind of communication modules. The ETSI ITS protocols do not take any height information into account, however. For example, the current GeoNetworking routing algorithms only evaluate longitude and latitude, but no altitude.
Aside from that, Artery can probably be used as a foundation for UAV use cases.
