### ISSUE TITLE
Artery examples and doubts

### ISSUE THREAD

**Issue by jai9318** [riebl/artery#182]
Hello sir, 
I have questions which might be basics. I just need help.

1) In artery/scenarios folder if I am trying to run the mt-its_2017.py ... I am getting error in storyboard and timeline. 
Not able to understand how to run and mainly which file should I run.
How to install it , if it should be installed.

2) From make run_example command . Actually which file is executing not able to get to know.

And what if I want to create My own scenarios and what should be configured.

And how can I use sumo-gui command in omnetpp.ini file. 
Like mainly how will i get to know after make run_example which file is executing.

3) after installing artery should I install veins, inet also. I have already installed vanetza.

4) where should I add  *.**traci.launcher.sumo="sumo-gui"**.
In which omnetpp.ini file.
I am not able to get to know which file is actually executing from command make run_command and in which file sumo-gui command should be written.

This is too many questions and might be basic.
But I need help

**Comment by riebl** [comment]
1. You are not expected to run *mt-its2017.py* manually. This script is loaded by the `Storyboard` module. Just invoke this scenario by `make run_mtits2017`.
2. `run_example` is running *scenarios/artery*. Sorry for the inconsistent naming. You can modify *scenarios/artery/omnetpp.ini* to run this example with *sumo-gui*.
3. You don't need to install any of them. These external dependencies are automatically built by Artery.
4. *scenarios/artery/omnetpp.ini* - you can tell `make` to be verbose with the *VERBOSE=1* setting (e.g. `make run_example VERBOSE=1`). You can then see which settings are passed to OMNeT++ by a *run_\** call, including the scenario directory.

If you have suggestions on how to extend our documentation on http://artery.v2x-research.eu, I am more than happy to hear them :-)

**Comment by Ak9318** [comment]
Thank you sir.

1).Is this the same way to run other scenarios.
For example : make run_scenarioname

2). If I want to RUN other , one particular scenario. Present in "artery/scenarios"
Where/what I should change. And how to invoke that scenario

3).And the above should be run in "artery/build" directory. Am I right ?

4). If I want to UPDATE the present scenarios that is "artery/scenarios" according to my requirement. 
In which file should I make change.

5). If I write my own scenario what changes I should make in files. 

I am new to this so I am asking too many questions.

**Comment by raul-parada** [comment]
@Ak9318  did you figure out how to run different scenarios either originals also create by our own?
