### ISSUE TITLE
Traffic lights in Artery

### ISSUE THREAD

**Issue by xrispa-m** [riebl/artery#190]
Hi! I need to create a scenario with traffic lights in Artery where the state of the traffic light could change at a certain time.
I have created a similar scenario using Veins and Sumo in OMNeT++ and I have used the traci trafficlight class and the setState function. I added the following code in the onWSM from OMNeT++.

`if (simTime() > 30 && simTime() < 50)
{traci->trafficlight("cluster_254108781_257412131").setState("rrrrrrrrrrrrrrrrrrrr");}`

Is there a similar way to do something like that using Artery?

Thanks!

**Comment by riebl** [comment]
Sure, every SUMO feature exposed by its C++ TraCI API can be used in Artery. I think you are looking for `TraCIAPI::TrafficLightScope::setRedYellowGreenState`.

**Comment by xrispa-m** [comment]
Thank you for the reply!
Is there a certain class that I should use to add the code for the traffic light? Is CaService and the RsuCaService something similar to the onWSM?

**Comment by riebl** [comment]
An `ItsG5Service`'s `indicate` method is invoked whenever a message has arrived for the respective service. In general, I recommend creating a dedicated service for each independent use case.

**Comment by xrispa-m** [comment]
I was using the RsuCaService before seeing your comment and I was able to use the setProgram to change the traffic lights but I cannot change it while the simulation is running.

Is there any way to change them in runtime?

**Comment by riebl** [comment]
I don't have a lot of experience controlling SUMO traffic lights. Please see the SUMO manual on how to change their programs properly.
