### ISSUE TITLE
error with my own RsuService

### ISSUE THREAD

**Issue by ghost** [riebl/artery#195]
HI @riebl ,
i've tried to create my own RsuService and i get inspired by the code of RsuCaService , the problem is this error pumped up .

> Class "RsuService" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (artery::StationaryMiddleware) World.rsuX0.middleware (id=97), at t=0.548813502304s, event #9

i already added define_module(RsuService) in my .cc file . 

thank you in advance for your help .

**Comment by kenog** [comment]
Hi @maddy-xx,

did you add your `RsuService.cc` to `src/artery/CMakeLists.txt`?

Best regards
Keno

**Comment by maddy-xx** [comment]
hi , yes

**Comment by maddy-xx** [comment]
> hi , yes

problem solved

**Comment by xrispa-m** [comment]
@maddy-xx did you add your service to the CMakeLists to solve the problem?

**Comment by Chiqq** [comment]
Hi~Could you share how you solve this problem? I also added define_module() and still pop out this error.
