### ISSUE TITLE
std::logic_error when adding an RSU

### ISSUE THREAD

**Issue by OverwatchGirl** [riebl/artery#196]
Hello @riebl 

I'm trying to run a basic scenario, with a bidirectional way, two flows and two RSUs, but when running the scenario, i get this error : 
`std::logic_error: basic_string::_M_construct null not valid -- in module (artery::StationaryMiddleware) World.rsu[0].middleware (id=23), during network initialization`

Thank you in advance.

**Comment by riebl** [comment]
Can you give me some more details how to reproduce this error? Have you modified some Artery sources or does this happen with the unmodified Artery source code as published on GitHub?

**Comment by OverwatchGirl** [comment]
Yep, it happens with it as long , as i add rsu to a very basic scenario, one road and two flows.

**Comment by riebl** [comment]
Can you run your setup with a debugger attached to see at which line the `std::logic_error` exception is thrown?
When I run the *rsu_grid* scenario, which features several RSUs equipped with `StationaryMiddleware` and `RsuCaService`, no exceptions are thrown. I don't know what is different in your scenario compared to *rsu_grid* that causes this error.

**Comment by OverwatchGirl** [comment]
I  think that my xml files weren't well written, because when i created a new project and with new xml files (.rou, .net and services) it worked just fine.

thank you for your time.
