### ISSUE TITLE
PER recording

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#197]
hello @riebl,

How to record only Packet Error rate for a scenario (disable all other recordings)?
I tried adding this on my _**omnetpp.ini**_ to disable all stats : _*.node[*].wlan[*].**.statistic-recording = false_

Then, I added these lines to record PER: 

_*.node[*].**.packetErrorRate.statistic-recording = true_
_*.node[*].**.packetErrorRate.result-recording-modes = all_

But it's not working?

Thanks in advance.

**Comment by MadeInPierre** [comment]
If i'm not mistaken, the first of these two lines does not match the second since `wlan[*]` != `middleware`:
_.node[].wlan[*].**.statistic-recording = false
.node[].middleware.CA.transmission.result-recording-modes = all_

So the parameter `.node[].middleware.CA.transmission.result-recording-modes` only finds the second line and not the first.
I hope I'm correct, if not please ignore my message :smile:

**Comment by SamirRachedi** [comment]
No problem at all @MadeInPierre , it's always nice to exchange with others.
In the beginning, without all these lines, I noticed that Artery is recording lots of stats (I got a 60GB file !!!!). So I used: _.node[].wlan[*].**.statistic-recording = false_ to disable all stats and it worked.
Than I added : 
_.node[].**.packetErrorRate.statistic-recording = true_
_.node[].**.packetErrorRate.result-recording-modes = all_
to recorded PER. When I saw it's not woking I tried to add: 
_.node[].middleware.CA.transmission.result-recording-modes = all_
_.node[].middleware.CA.reception.result-recording-modes = all_
Just to test (to be sure that moment is not ignoring other lines as you mentioned in your first reply) and it worked fine.

I guess you get my point. Thanks anyway.

**Comment by riebl** [comment]
I guess you have managed to record PERs, do you? Do you think we should add some information about result recording to our documentation, i.e. beyond the information provided by OMNeT++ itself?

**Comment by SamirRachedi** [comment]
Hello @riebl,

I managed to understand what I did wrong and I'm getting the PER now. Just Don't know how to get curves of PER vs Distance like in the figure below:

![image](https://user-images.githubusercontent.com/29753753/122352845-c5a19880-cf4f-11eb-9af8-a9e7fbd1b450.png)

Appreciate any help. thanks a lot.

**Comment by riebl** [comment]
I have added a task regarding "X-distance-plots" to #215 and thus close this issue now.
