### ISSUE TITLE
Datarate

### ISSUE THREAD

**Issue by OverwatchGirl** [riebl/artery#210]
Hello @riebl ,

Im trying to get the rate in `Radio.cc`, of the transmitted packets from each access category queue `(BE,  BK, VO, VI)`.
Is there any method that calculates the rate ? and what does `radioFrame->getDuration().inUnit(SIMTIME_PS)` really do ?

Thank you so much for your help, much appreciated.

**Comment by riebl** [comment]
I think you have to implement the rate calculation on your own as there are many ways to do this: average of the whole simulation time, average of a sliding window, etc.

`radioFrame->getDuration().inUnit(SIMTIME_PS)` is the duration of a radio frame in picoseconds.

**Comment by OverwatchGirl** [comment]
Hello,

Thank you for your answer .
