### ISSUE TITLE
Dynamic network configuration to target multicell scenarios

### ISSUE THREAD

**Issue by rtobi** [riebl/artery#217]
Hello @riebl!
I run into another problem where you or maybe someone else knows a workaround:
Once vehicles remain in the same cell (as in your lte-blackice example) D2D communication works very well, both using multicasts and unicasts. At the moment where a vehicle switches to another cell, only multicasts are working for this vehicle. Unicasts are also not working again once all vehicles completed their handover and are located in the new cell.
While trying to hunt the problem down, I have come to suspect that the problem is the IPv4NetworkConfigurator as it only supports static routes. I suppose that once a vehicle switches cell and the network topology changes, the routing to the corresponding eNodeB is not appropriate anymore. Can my assumption be correct? 
Is there a way to circumvent the problem? I tried to use the RIP routing, but it probably only works once the routing tables are updated. I also tried to reinitialize the IPv4NetworkConfigurator and tried to recompute the routes (IPv4NetworkConfigurator ::computeConfiguration()). Unfortunately, I did not have success. Maybe I can setup the network in a different way to not run into this problem? 

Many thanks for any ideas and comments!
Best regards!

**Comment by riebl** [comment]
Artery is simply relying on SimuLTE for this type of communication. Hence, all the nitty-gritty details of switching between cells belong to SimuLTE. I am definitely not an expert in this topic, so please ask for advice at the SimuLTE project site. If there is something I can change at Artery to better support your use case, I am happy to change Artery accordingly.

**Comment by rtobi** [comment]
Thank you for your quick reply @riebl! I will try the SimuLTE project site and let you know if I am able to find a solution.
