### ISSUE TITLE
Data request parameter mapping

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#219]
Hello @riebl, 

How the BTP data request in the CaService is mapped to the flow control data request?
What I found is that the parameters of a BTP request are mapped to a GeoNet data request, but nothing further. So any help ?

thanks.

**Comment by riebl** [comment]
Are you looking for this code segment: https://github.com/riebl/vanetza/blob/460f76f8863ff69a8d45a5b63dd724f831f622ed/vanetza/geonet/router.cpp#L694?
