### ISSUE TITLE
Minor Bug in the feature *.traci.core.startTime

### ISSUE THREAD

**Issue by bargmann** [riebl/artery#22]
Hi, with some special start times the simulation is crashing. For example 100 s in the artery run_exmaple.  99 s, 101 s and other times working fine. But when 100 s is used the simulation is crashing with this message: `opp_run_release: /home/baa4hi/artery/src/artery/application/LocalDynamicMap.cc:24: void artery::LocalDynamicMap::updateAwareness(const CaObject&): Assertion `entry.expiry > omnetpp::simTime() && entry.expiry < omnetpp::simTime() + 2.0' failed.`  I choose 100 s in my first test complete random. I could not reconstruct this failure with the storyboard example.

**Comment by riebl** [comment]
@bargmann Which scenario and configuration are you using? I am trying to reproduce this error but this error does not occur up to now.
Furthermore, it is odd that `opp_run_release` is invoked and an assertion triggers (they are disabled in release builds). What is your CMAKE_BUILD_TYPE?

**Comment by bargmann** [comment]
The error occur with the default run_example from the scenario directory. I rebuild artery completely in this morning after pulling the new/changed files.  In the cmake cache the build type is `CMAKE_BUILD_TYPE:STRING=`. I build the dependencies with `make all` and artery without additional parameters. Just in the way it is suggested.

**Comment by bargmann** [comment]
I am able to reproduce the error with my some of own scenarios. It is the same behavior. With some start times the system stucks in time and it looks like that are more messages are generated than scheduled. After some time in this case the simulation crashes. Again some small variation in the start time, like 51 s  instead of  50 s and now failure occur.

**Comment by riebl** [comment]
Okay, I am now able to reproduce this error. I will investigate it further.

**Comment by riebl** [comment]
e5b2d8f72228c0a94c3a0cbb89eb84a9d68fac53 replaces the failing assertion by a warning. Please note that the "inet" configuration works without problems while the "veins" configuration suffers from very long latencies (and thus exceed the CA expiry in LDM).
I am not saying that Veins is broken here but our integration of its radio sub-system.

**Comment by bargmann** [comment]
With the "inet" configuration and the run_example from Artery I receive again at special times an error massage  'Cannot convert 2.09892e+90 to simtime_t: Out of range (-9223372.036854775807,9223372.036854775807), allowed by scale exponent -12 -- in module (inet::physicallayer::Ieee80211Radio) World.node[11].wlan[0].radio (id=683), at t=100.000149s, event #109'. This behavioris shown if the traci.core.startTime is over a certain threshold. I figured out that in the run_example it occurs above 30 s skipping. The artery setup is the standard configuration from the git this morning.

**Comment by riebl** [comment]
I have fixed the trouble with the "veins" configuration in a5c182779b087eea2c24e0ad832bdd6c7ed31200.
I suppose that `simtime_t` being out of range is another (possibly unrelated) issue, which I cannot reproduce right now. Please open a new ticket if this problem remains.
Otherwise, I consider the initial `startTime` issue as fixed.
