### ISSUE TITLE
Error while adding sensors to road side units(RSU) to realize CPM transmission

### ISSUE THREAD

**Issue by MengGao-MG** [riebl/artery#221]
Hi @riebl,

I have an issue while using RSU and sensor. Furthermore, I have added sensor to the RSU to send CPM to avoid collision between two vehicles.
In my scenario: an intersection, two vehicles and a RSU.

I initialized the RSU following the **rsu_grid** example scenario.I'm using **network = artery.envmod.World** network and inside  **omnetpp.ini**, I have

![image](https://user-images.githubusercontent.com/89237022/130185148-be85ff34-a0be-4ca0-b30f-a704ecda9afb.png)

The **rsusensor.xml** contains
![image](https://user-images.githubusercontent.com/89237022/130185201-ef80082c-b685-4d73-84b3-3c8a96e846a0.png)

I have added sensor to the RSU, but the errors are as follows:

**no valid object of type 'N5traci17VehicleControllerE' registered -- in module (artery::RadarSensor) World.rsu[0].environmentModel.FrontRadar (id=273), during network initialization.**

My questions are : 
Is the Front Sensor supposed to be used only with vehicles? And is there a use case for adding sensors to RSU ? How do I modify it?

Regards

**Comment by riebl** [comment]
Currently, all entities of the environment model need to exist in SUMO. However, the RSUs are usually only defined in OMNeT++. I agree that many use cases exist where RSUs equipped with sensors are valuable. I will try to relax the environment model's dependency on SUMO entities.

**Comment by riebl** [comment]
You can now equip RSUs with sensors since commit bc7013066c2f00aa84324d71cf0a9e9ffdf07b00. I have added an example to the *rsu_grid* scenario as well based on your modifications.
