### ISSUE TITLE
Cannot see the denm messages in Wireshark 

### ISSUE THREAD

**Issue by goksunazlican** [riebl/artery#225]
I'm trying to see loopback of den messages by running _ImpactReductionUseCase_ with the _mtits2017_ scenario, however, I cannot see them in Wireshark. 
Previously, I have tried it via vanetza-socktap to send and receive denm and I could explicitly see den messages there.

What may be wrong with the usage of artery here?

**Comment by riebl** [comment]
The network communication of the simulation is not sent over any actual network or loopback device of your computer, i.e. Wireshark has no possibility to intercept any of these simulated packets.
