### ISSUE TITLE
Tutorial Artery+Omnet

### ISSUE THREAD

**Issue by raul-parada** [riebl/artery#227]
Hi, 

Besides the chapter about Artery within the book "Recent Advances in Network Simulation" is there any step-by-step simulation to create from scratch a V2X simulation using an own SUMO map? 

Thanks.

**Comment by riebl** [comment]
I am not aware of any. Contributions are welcome!

**Comment by kenog** [comment]
For Artery you can just use the most recent master branch. Version recommendations for the dependencies can be found in the [Install Instructions](http://artery.v2x-research.eu/install/).

**Comment by raul-parada** [comment]
Since the last update was on July 11, 2020, I though we can use updated versions.

**Comment by kenog** [comment]
Those versions should still work fine though. However, if you want to try more recent versions: I am currently using SUMO 1.10 and Omnet 5.7 without any problems.

**Comment by raul-parada** [comment]
I've created a scenario from scratch (without NED files) where I've added run_XX inside the Makefile inside build. When I try to run the scenario using make run_XX I get "make: *** No rule to make target 'run_XX'. Stop. Which are the basic files to simulate a simple scenario? From a custom SUMO map (rou, net and cfg)

**Comment by riebl** [comment]
You should never ever edit any files in your build directory! Use the `add_opp_run` CMake macro to add run targets for your scenario.

**Comment by raul-parada** [comment]
Where can I find the `add_opp_run` CMake macro?

**Comment by riebl** [comment]
See for example https://github.com/riebl/artery/blob/bc7013066c2f00aa84324d71cf0a9e9ffdf07b00/scenarios/artery/CMakeLists.txt#L1
This invocation of `add_opp_run` enables the `run_example` target.

**Comment by raul-parada** [comment]
I've done it. In a new folder inside scenarios `artery/scenarios/ctc/CMakeLists.txt`. I've added `add_opp_run(ctc CONFIG omnetpp.ini)`. The file omnetpp.ini is also included inside the folder ctc. I've compiled in the build folder` cmake ..`
`cmake --build .` however, there is no any folder named as ctc neither I can execute `make run_ctc`. What I am missing?

**Comment by riebl** [comment]
I bet you have missed adding `add_subdirectory(ctc)` to *artery/scenarios/CMakeLists.txt*, right?

**Comment by raul-parada** [comment]
You were right, I didn't know I had to insert such line. It works now!
