### ISSUE TITLE
Envmod radar sensor direction bug

### ISSUE THREAD

**Issue by CengizYa** [riebl/artery#235]
Hello,

I think I found a bug while working with the envmod in Artery (cmake --build build --target run_example, bc7013066 envmod: enable sensors attached to RSUs): The sensor types FrontRadar and RearRadar are both at the correct position, but the sensor cone opens towards the wrong direction. The sensors also only detect objects that are in the wrong direction. In the image I only included the FrontRadar.
![Bild_2022-01-20_190057](https://user-images.githubusercontent.com/98113637/150395560-2b2e2bcd-1771-42ca-98ca-ce40d7f3a7d7.png)

**Comment by riebl** [comment]
Dear @CengizYa,

Thanks for reporting this issue together with a helpful screenshot. I have identified the problem and pushed a fix to the master branch. RSU and vehicle sensors look both reasonable to me now.
