### ISSUE TITLE
Messages not being received when obstacles added eventhough there is line of sight

### ISSUE THREAD

**Issue by rdn123** [riebl/artery#236]
Hello,

I am currently testing an example of my creation in Artery, I have a RSU and an OBU in a car.
First, I tested the scenario without obstacles and the messages were exchanged perfectly but when I introduced the obstacles no messages were received. There is direct line of sight between them in a part of the trajectory, I have tried solving it but I am unable and any help would be appreciated.

Thank you.

**Comment by riebl** [comment]
You need to give a little bit more details about your configuration:
- Which radio layer are you using? Veins or INET?
- Which radio propagation model are you using?
- What are the related settings in your omnetpp.ini?

Without more information, it is almost impossible to give any sensible advice.

**Comment by rdn123** [comment]
Hello,
I am using INET radio layer with Ieee80211ScalarRadioMedium
Radio propagation model: ConstantSpeedPropagation
PathLossType: FreeSpacePathLoss
ObstacleLossType: IdealObstacleLoss
analogModel:ScalarAnalogModel
backgroundNoiseType:IsotropicScalarBackgroundNoise
Both RSU and OBU have VanetNic
The RSU and the OBU are transmitting 200mW

The same configuration without the obstacles works fine.

Thank you very much for the quick response,

**Comment by riebl** [comment]
I have not used `IdealObstacleLoss` yet. However, I suggest setting a breakpoint in `IdealObstacleLoss::isObstacle` at line 58 which is hit if an obstacle is found between transmitter and receiver. Identifying the blocking object may help to identify the reason for the observed behaviour. Also, be aware that the coordinates of `PhysicalEnvironment` objects are using a coordinate system different from the SUMO coordinate system.

**Comment by rdn123** [comment]
I have done as you suggested. I put the the breakpoint in IdealObstacleLoss::isObstacle at line 58 and apparently there was an obstacle between the transmitter and the receiver even though I could not see that obstacle (I am using PhysicalEnvironmentVisualizer ). Anyway, I took the nearby obstacles away and now there is not any obstacle between them (isObstacle is 0 at line 56)  but I still can not receive anything. The  obstacles seem to be well located as I can see visually. I don´t know what I can be missing.

**Comment by riebl** [comment]
Maybe the INET community can help you because the radio layer is mostly plain INET; Artery just adds some wrapping code ("radio driver") to make it accessible in our architecture.

**Comment by rdn123** [comment]
Ok, thank you!
