### ISSUE TITLE
Can't retrieve message at Physical Layer

### ISSUE THREAD

**Issue by maroueneboubakri** [riebl/artery#237]
Hi @riebl, @Venturina,

I was playing with TestBed scenario using a configuration without USRP,  it turns out that Physical and Link layer are omitted from the message to be handled at [OtaInterfaceStub::sendMessage](https://github.com/riebl/artery/blob/master/src/artery/testbed/OtaInterfaceStub.cc#L30) is that an intended behaviour  ?

Digging into the code, I saw that only Network up to Application layer are only taken. See here: https://github.com/riebl/artery/blob/master/src/artery/testbed/OtaInterfaceLayer.cc#L49 

Is there any reason for that ? The issue now, is when changing to `auto range = create_byte_view(packet->getPayload(), OsiLayer::Physical, OsiLayer::Application);` still can't get the Phy/Link headers.  I mean `auto range = create_byte_view(packet->getPayload(), OsiLayer::Link);` returns empty.

It would be interesting to get the whole message instead, such can forward it as it is to a DUT. Is there any way to get it ?

Reagrds
Maro

**Comment by riebl** [comment]
Dear @maroueneboubakri,

yes, this is intended behaviour: The PHY and MAC headers are handled by the software running on/along with the USRP.
Vanetza ships with some code for dealing with ITS-G5/802.11 MAC headers, which may be useful for you: https://github.com/riebl/vanetza/blob/master/vanetza/access/g5_link_layer.hpp

**Comment by maroueneboubakri** [comment]
Hello @riebl,

Thank you ! I stepped into this code https://github.com/riebl/vanetza/blob/master/tools/socktap/cohda.cpp and took pieces from it to construct the MAC header.
However, I still trying to make socktap work with Cohda link.
I have 2 boards: In the first:
`./socktap --security none -l cohda -i cw-llc0 -a hello`
In the second:
`./socktap --security none -l cohda -i cw-llc0 -a benchmark`

The second board is supposed to increment the message counter ?
Also I notice that the device does not enter promiscuous mode.

When I read the documentation, cohda employs Cohda’s LLC API  I was expecting that the tool uses `/usr/lib/libLLC.so`
which was not the case (see below). It seems to be the same as ethernet except that it prepend MAC header ?
```
ldd socktap
        linux-vdso.so.1 (0x0000ffffa5a71000)
        libboost_system.so.1.71.0 => /usr/lib/libboost_system.so.1.71.0 (0x0000ffffa51ff000)
        libboost_program_options.so.1.71.0 => /usr/lib/libboost_program_options.so.1.71.0 (0x0000ffffa5169000)
        libgps.so.25 => /usr/lib/libgps.so.25 (0x0000ffffa513b000)
        libboost_date_time.so.1.71.0 => /usr/lib/libboost_date_time.so.1.71.0 (0x0000ffffa5119000)
        libGeographic.so.13 => /usr/local/lib/libGeographic.so.13 (0x0000ffffa5087000)
        libcryptopp.so.5.6 => /usr/local/lib64/libcryptopp.so.5.6 (0x0000ffffa49d7000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000ffffa47fd000)
        libm.so.6 => /lib/libm.so.6 (0x0000ffffa4754000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0000ffffa4730000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x0000ffffa4700000)
        libc.so.6 => /lib/libc.so.6 (0x0000ffffa4598000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffa5a43000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x0000ffffa4534000)
        libsystemd.so.0 => /lib/libsystemd.so.0 (0x0000ffffa446c000)
        librt.so.1 => /lib/librt.so.1 (0x0000ffffa4454000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x0000ffffa441f000)
        libcap.so.2 => /lib/libcap.so.2 (0x0000ffffa4409000)
```
Could you provide a quick example which showcase how to use it, maybe I miss a detail.
Using tests from LLC app just works fine.

Regards
Maro
