### ISSUE TITLE
LocalDynamicMap

### ISSUE THREAD

**Issue by lukne541** [riebl/artery#244]
I want to analyze consecutive CAMs. I have only found LocalDynamicMap as a method of doing this, however count is insufficient as I need access to all data in the CAMs. Is there a way of doing this that I have missed, or should I implement something myself?

**Comment by riebl** [comment]
The `LocalDynamicMap` already stores the full CAMs as `CaObject` in its `AwarenessEntry`. You should be able to add a query method to `LocalDynamicMap` without much trouble. For example, you could use the `count` method as a blueprint but return a list of matching `AwarenessEntry` objects. I would be happy to accept a pull request implementing such a query method.
