### ISSUE TITLE
Questions about Artery V2X services 

### ISSUE THREAD

**Issue by Rubinthan** [riebl/artery#245]
Hi,

I have some questions about your Artery project:

1. Can we develop and compile some V2X services independently from artery and add it to artery as a dynamic library when starting the simulation with opp_run? (This would allow adding a new service without recompiling the whole artery project? )  

2. If this is possible how can we define a service independently from artery?

3. Can we disable a service during the simulation and re-enable it at a desired time ? (This would allow to use a V2X service depending on where the car is during the simulation)

4.. Can we develop V2X services in Python or Matlab ?

Thanks,

**Comment by riebl** [comment]
1) That's feasible if your V2X service does not use any Artery objects. However, our build system supports incremental builds, i.e. only files that have changed or when their dependencies have changed will be recompiled.
2) Just as any other C++ library. If you really want to go that way, you may want to depend at least on Vanetza.
3) I had no use case for removing services during a simulation run selectively yet, so this is not implemented. However, you can just add a boolean flag to your service tracking its state: If it is disabled, it may just do nothing when one of its methods is invoked.
4) Thats not supported without additional glue code.
