### ISSUE TITLE
difference between Artery and Artery-C

### ISSUE THREAD

**Issue by yasminechibani** [riebl/artery#250]
Hello, what is the difference between Artery and Artery-C?

**Comment by riebl** [comment]
Well, the readme of Artery-C says: 

> Our simulator relies on the simulation framework SimuLTE and substantially extends it by implementing a dedicated sidelink interface, sidelink resource allocation modes along with control and user planes. (...) A specific feature of Artery-C is the support of dynamic switching between all modes of Cellular V2X.

I think this pretty much nails it.
