### ISSUE TITLE
Wiresahark pcap files and artery extern sources usage

### ISSUE THREAD

**Issue by aintzel2** [riebl/artery#254]
Hello.

I am trying to capture packets (creating pcap files) in the artery project to analyze the traffic in wireshark using the example PcapRecorder from inet. I am using Visual Studio Code IDE (because with OMNET++ I had problems to run artery).
 
Artery uses Cmake to declare the sources, and the thing is that in order to capture packets I need the code that is located in extern/inet... because in artery/src/inet/... there are not all the codes that I need.

So, is there any way to call the codes from extern/inet/src/... or is it necessary to copy the codes to the sources directory of artery and then declare them in the Cmake of that sources by hand.
 
I don't know if there is any other easier way to capture packets.

Thanks in advance.

**Comment by riebl** [comment]
For the record: There is no need to copy any source files from extern/inet/src because those are compiled by Artery's CMake build configuration.
