### ISSUE TITLE
Intersection and Longitudinal Collision Detection

### ISSUE THREAD

**Issue by aintzel2** [riebl/artery#255]
Hello @riebl.

I am trying to avoid collision both Intersection and Longitudinal using CAM messages. Is there any method in artery that detects there is going to be a collision?

**Comment by riebl** [comment]
No, there are no explicit collision detection algorithms in Artery. However, Christina implemented a time-to-collision trigger for Artery's storyboard: https://github.com/riebl/artery/blob/master/src/artery/storyboard/TtcCondition.h
This triggering condition fires if two vehicles possibly crash within a specified time window, assuming constant movement.
