### ISSUE TITLE
Vehicle control

### ISSUE THREAD

**Issue by aintzel2** [riebl/artery#257]
Hello @riebl.

I'm trying to control vehicles via `VehicleController`. I'm calling `VehicleController.h` functions in `CaService` to stop a car. When I use `get` function it works perfectly:

`auto& vehicle = getFacilities().get_const<traci::VehicleController>()`
`vehicle.getSpeed().value()`

But when I try the same with `set` it doesn't work:
`vehicle.setSpeed(0) //Stop the vehicle`

When I write the object `vehicle.` I get the `get` functions in the suggestions but not the `set` functions. And of course, when i simulate  doesn't work. What can be the problem?

**Comment by riebl** [comment]
When you say "it doesn't work" you mean it does not even compile, right?
`VehicleController::setSpeed` expects a Boost.Unit quantity, i.e. `0` is not sufficient. You need to pass `0.0 * boost::units::si::meter_per_second`, for example.

**Comment by aintzel2** [comment]
Thanks for your answer @riebl 

Yes, I meant that it did not compile.

Now I tried these two things:
1. `vehicle.setSpeed(0.0 * boost::units::si::meter_per_second);`
2. `static const vanetza::units::Velocity stop {0.0 * boost::units::si::meter_per_second};`
    `vehicle.setSpeed(stop);`

But I get the same error message:

![image](https://user-images.githubusercontent.com/109578078/182540415-bd2d5767-9d17-49ac-9560-83104c3e253c.png)

**Comment by aintzel2** [comment]
Sorry I didn't meant to close the issue

**Comment by riebl** [comment]
You cannot call non-const methods on objects via const references. `VehicleController::setSpeed` is a non-const method whereas `getSpeed` is a const method. You can retrieve a non-const reference to `VehicleController` by `getFacilities().get_mutable<traci::VehicleController>()`.
