### ISSUE TITLE
ExampleService class extract CAM

### ISSUE THREAD

**Issue by aintzel2** [riebl/artery#258]
Hi @riebl . I'm using `ExampleService.cc` to create another service. But I don't know how to get de CAM message from` CaService`. In `ExampleService::receiveSignal` there is `cObject*`. Have I to cast it to extract the CAM or is there another way to do this?

Thanks.

**Comment by riebl** [comment]
You can cast the `cObject*` to `CaObject*` if the source is the *CamReceived* or *CamSent* signal.
