### ISSUE TITLE
Sumo not found when running run_example

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [riebl/artery#265]
Hi all,
I have installed all the required packages and built correctly Omnetpp, artery and sumo.
I have added the Omnetpp directory as well as the sumo one to the path in the .bashrc but then
when I run make run_example from Artery build folder I get sumo not found as you can see in the attached capture.

So should I set the path somewhere in one of the artery file? Where is Artery looking for sumo? I have it installed in /home/martina.

Thanks in advance,

Martina
![Screenshot from 2022-11-21 16-16-38](https://user-images.githubusercontent.com/102963213/203091820-4f5ec0ab-fa5b-47a0-9ffd-dd0bcf8d8948.png)

**Comment by kenog** [comment]
Hi @MartinaBarbiFivecomm,

setting the PATH variable correctly should be fine. You need to add the `bin` folder inside SUMO's main directory. Did you do that? It should look something like `/home/martina/sumo/bin`.
If you set it in your `.bashrc` you also need to restart your terminal for it to become effective.

Best regards
Keno

**Comment by MartinaBarbiFivecomm** [comment]
Thank you for replying.
Yes I had already set the path in the bashrc (see the attached pic, I tried with both commands on line 119 and 121)
 restarted the terminal, restarted the virtual machine, reinstalled sumo and artery but still getting the same error **sh: 1: sumo not found**. 
I`m not sure what I am doing wrong, as artery is able to find omnetpp but not sumo. Any help is appreciated.

Thank you very much,

Martina

![Bashrc_file](https://user-images.githubusercontent.com/102963213/203298563-4e3ba825-dd68-4b13-ad3f-4e42168114e3.PNG)

**Comment by hagau** [comment]
@MartinaBarbiFivecomm Did you compile SUMO in release mode? If one compiles SUMO in debug mode, the binary is named `sumoD`, thus leading to this error message.

This happened to me more than once, by the way :smiley:

**Comment by MartinaBarbiFivecomm** [comment]
No, I compiled it using cmake ../.. not the debug mode

**Comment by kenog** [comment]
You set `SUMO_HOME` to the `bin` directory but not the `PATH`. I think your config should be:
```
export SUMO_HOME="/home/martina/sumo"
export PATH="$HOME/omnetpp-5.6.2/bin:$SUMO_HOME/bin:$PATH"
```

**Comment by MartinaBarbiFivecomm** [comment]
Thank you very much, that worked.! :)
Sorry but it is the very first time for me working with Omnetpp and SUMO.

Thank you.!

**Comment by riebl** [comment]
For future reference: If you type `which sumo` in your terminal and it shows you the full path to your SUMO installation, then Artery can find the executable without any further hints too.
If you have a very unusual setup and cannot modify the PATH variable for some reason, you may want to set the `sumo` parameter of the `PosixLauncher` module. That said, I never had a reason to do so.

PS: Thanks @kenog and @hagau for supporting @MartinaBarbiFivecomm so competently.
