### ISSUE TITLE
Default Channel Access Scheme in Artery Services (DEN and CA) 

### ISSUE THREAD

**Issue by 1234MaDa** [riebl/artery#269]
Hello ! I need your help with this issue please ! 

I want to check what kind of channel access scheme is used in Artery for the 802.11p/ ITS G5 messages transmissions ? (Is it TDMA ?) 

Where can i find the source code related to the channel access scheme in artery please ? 

I want to modify the source code of the channel access scheme of the services i am using to study the performances like latency and PRR when i modify or combine channel access schemes ! 

Thanks in advance !

**Comment by riebl** [comment]
IEEE 802.11p uses CSMA/CA and Artery can employ either Veins or INET as radio models. Hence you cannot find the channel access model in our code directly but in _extern/veins_ and _extern/inet_, respectively.
