### ISSUE TITLE
Failed to "cmake --build ."

### ISSUE THREAD

**Issue by HuyTyskland** [riebl/artery#274]
Hello, I am playing around with Artery to simulate platoons under ETSI standards.

Right now, I am following this [instruction](http://artery.v2x-research.eu/install/) to install Artery. However, when inserting "cmake --build .", I got an error as the description below. I tracked the file and tried to delete "-h", which I think is not a good option to do.
I am installing Artery on Ubuntu 20.04 on VMWare.

Error:
`etsi-platoon@ubuntu:~/src/artery/build$ cmake --build .

[  0%] Generating message inet/applications/base/ApplicationPacket of INET

opp_msgtool: unknown option -h

make[2]: *** [CMakeFiles/INET.dir/build.make:63: INET_gen/inet/applications/base/ApplicationPacket_m.cc] Error 1

make[1]: *** [CMakeFiles/Makefile2:542: CMakeFiles/INET.dir/all] Error 2

make: *** [Makefile:141: all] Error 2
`
What should I do to fix this issue?

Thank you very much,
Huy Nguyen.

**Comment by awillecke** [comment]
Hey,

did you try to build Artery with OMNeT++ 6.0? For now, Artery only supports versions up to 5.x.

Best regards
Alex

**Comment by HuyTyskland** [comment]
Hello @awillecke , thank you very much for your reply. I just fixed the issue a few days ago (sorry for late response) and it is exactly as you said.
