### ISSUE TITLE
Code to save results

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [riebl/artery#277]
Good afternoon,

sorry but I recently started using artery, omnet++ and so on.
In artery where is the code meant to save the results? In order to understand what is being saved for each scenario.

Thank you very much,

Martina

**Comment by awillecke** [comment]
Hi,

in Artery, you can use the [result recording features of OMNet++](https://doc.omnetpp.org/omnetpp/manual/#cha:ana-sim). For example, the `CaService` can [record](https://github.com/riebl/artery/blob/master/src/artery/application/CaService.ned#L24) the station ID and genDeltaTime when [receiving a CAM](https://github.com/riebl/artery/blob/master/src/artery/application/CaService.cc#L115). If it does is determined in the `omnetpp.ini` of the scenario you run. The example scenario has all recordings [disabled](https://github.com/riebl/artery/blob/master/scenarios/artery/omnetpp.ini#L9) by default. On how to enable recordings of all or only specific signals/statistics you are interested in, please refer to the OMNet++ documentation.

Best regards
Alex

**Comment by MartinaBarbiFivecomm** [comment]
Thank you for your reply. However I have few more questions please:

- In the highway-police scenario I get a results folder with scalar and vector data, but in the omnetpp.ini of this scenario there is no recording code to store  those vectors. So where is it configured?

- When trying to open the vec file in the Omnet++ IDE nothing is loading, or if I try to open the whole directory for example Desktop/artery/scenarios/highway-police it gives me an error saying that the directory could not be loaded. Do you know why is this happening?

Thanks in advance for your help,

Martina

**Comment by awillecke** [comment]
I have no experience with the highway-police scenario, but at a first glance it seems that it (or rather its services) does not record anything. That is why the result files are empty, and you cannot find any code for recording. You would need to implement the recording of the measurements you are interested in yourself. Maybe this part of the [documentation](https://doc.omnetpp.org/omnetpp/manual/#sec:simple-modules:signal-based-statistics) is helpful.

If you just want to try recording data, you could enable recordings by the `channelLoadRecorder` in the `envmod` config section. Adding something like this should work:
```
*.node[*].channelLoadRecorder[*].ChannelLoad.vector-recording = true
*.node[*].channelLoadRecorder[*].ChannelLoad.scalar-recording = true
*.node[*].channelLoadRecorder[*].ChannelLoad.statistic-recording = true
```

**Comment by MartinaBarbiFivecomm** [comment]
I did put these lines **.scalar-recording = true and **.vector-recording = true in the omnetpp.ini file and it stores some variables when also running the general configuration. However when I plot the data for the four vehicles I get these histograms for the minSNIR and PacketErrorRate, but I actually do not understand what is the x-axis representing? in the minSNIR which units are those values? And in the PacketErrorRate it should be something below 1 as it is usually a percentage right?

![SNIR](https://user-images.gith

![PacketErrorRate](https://user-images.githubusercontent.com/102963213/228865045-bb802445-81ee-4c7e-b83c-791e88ba9d12.png)
ubusercontent.com/102963213/228865022-13ec8a69-70c9-4dc0-8c98-90bd86ac9444.png)

**Comment by riebl** [comment]
The last time I have been using the OMNeT++ IDE is years ago. Thus, I cannot say what it is plotting there exactly. I assume you can get some details in the "Properties" section in the bottom left corner of your screenshots.

The scalars and vectors you see in the results files are default statistics produced by the INET WLAN model. As long as those are not explicitly disabled, you will find them in the result files. If you look for `@statistic` in the *.ned files, you will find a vast number of metrics you could record.

My personal favourite for collecting data with OMNeT++ is its SQLite backend. You can have a look at *scenarios/car2car-grid/omnetpp.ini* where this backend is used. Furthermore, this scenario can serve as an example of how to enable Artery-specific metrics such as *LinkLatency*. With the SQLite backend, the result files are SQLite databases you can open and process independently of the OMNeT++ IDE. For my thesis, I have used Python a lot for analysing the data and creating plots.
