### ISSUE TITLE
Loading files in Omnet++ IDE after running artery Simulation

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [riebl/artery#278]
Good morning,

I experiencing issues while loading the highway-police directory into Omnet++. When I try to load the whole directory I get this error 

![omnet_Importing_Error](https://user-images.githubusercontent.com/102963213/229046657-732a68aa-8fe6-4236-af19-62e0c8bf4f44.png)

while if I try to import one the .vec results file nothing shows up in Omnet++ IDE. 

What the issue could be?

Many thanks,

Martina

**Comment by riebl** [comment]
No OMNeT++ IDE project exists in *scenarios/highway-police*. If I remember correctly, the IDE looks for *.project* and/or *.cproject* files. Since those do not exist, you cannot open the directory as an "existing project".

**Comment by MartinaBarbiFivecomm** [comment]
Yes but I should be able to open the .vec file, using open file and it does not load it most of the times.

**Comment by riebl** [comment]
Sorry, I am far from being an expert for the OMNeT++ IDE. You likely get better support from an OMNeT++ user group.
