### ISSUE TITLE
Highway-police scenario messages

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [riebl/artery#279]
Good afternoon,

I would like to ask you why in the highway-police scenario the cars which are not police (node[0], node[1], node[2]) are exchanging messages among them and with the police (as shown in the attached screeshot)?

The way it should work is that the police is transmitting to the others, and the other cars reacting to the message if not in the same lane as the police. But as you see in the attached picture they are exchanging messages between them and with the police. In the ClearLaneService.cc  there is no trigger () call so they should send nothing right? Am I missing something?

![Messages_Police_Scenario](https://user-images.githubusercontent.com/102963213/230602268-5d306657-7057-4866-9129-598a954bac82.PNG)

Thank you very much in advance,

Martina

**Comment by riebl** [comment]
The GeoNetworkwing protocol demands that stations send a so-called beacon roughly every 3 seconds if no other single-hop broadcast (SHB) is sent. Thus, if the vehicles were equipped with `CaService`, a CAM would be sent by them at least once per second and thus no beacons need to be generated by the network layer. In the highway-police scenario, the vehicles are not equipped with `CaService` though. Hence, their routers generate beacons according to the ETSI GeoNetworking rules.
However, you can disable beaconing explicitly in Artery: https://github.com/riebl/artery/blob/a7f8f099bf0031b0a26e1271168604791279ff4c/src/artery/networking/Router.ned#L19
