### ISSUE TITLE
Mobility question

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [riebl/artery#284]
Good morning,

which is the difference between the INET VehicleMobility and the Veins mobility?

Mant thanks,

Martina

**Comment by riebl** [comment]
Uhm, the former is for INET and the latter for Veins :-)

**Comment by MartinaBarbiFivecomm** [comment]
Yes, that I understand but what is the difference in terms of the implementation of mobility?

**Comment by riebl** [comment]
From Artery's perspective, there is no big difference: Just provide the (vehicle) position from the road traffic simulation to the INET or Veins radio model. In Artery, we provide only the necessary glue code for the respective radio model.

**Comment by MartinaBarbiFivecomm** [comment]
Ok, thanks.!
