### ISSUE TITLE
Vehicle types supported by artery 

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#286]
Hi,

What are the different vehicle types does artery supports? And how to model a new vehicle type in artery?

Best Regards,
Ambica

**Comment by awillecke** [comment]
Hi,

Artery can spawn different OMNet++ nodes, such as [inet.Car](https://github.com/riebl/artery/blob/master/src/artery/inet/Car.ned) or [inet.PlainVehicle](https://github.com/riebl/artery/blob/master/src/artery/inet/PlainVehicle.ned), when a vehicle of any type is departing in SUMO using the [MultiTypeModuleMapper](https://github.com/riebl/artery/blob/master/scenarios/artery/omnetpp.ini#L70) in a probabilistic fashion. Also, persons are supported. If you would like to create a new vehicle type, you could for example create a new NED module, which inherits from the `inet.Car`, add submodules as you like and tell the mapper to spawn those.

If you refer to the [vehicle types of SUMO](https://sumo.dlr.de/docs/Vehicle_Type_Parameter_Defaults.html), Artery is not yet able to distinguish between those and considers them all the same AFAIK.

Best regards
Alex

**Comment by awillecke** [comment]
Cars and motorcycles are both vehicles and will be handled the same by the ModuleMapper. If a communicating node with a middleware is created, you can, however, influence which services are run [using filters](https://github.com/riebl/artery/blob/master/scenarios/artery/services.xml#L12). If, in your SUMO scenario, motorcycles and normal vehicles are distinguishable by name, you could match that name using filters and instantiate services differently. This may be enough to fulfill your requirements.

Best regards
Alex

**Comment by Ambica2022** [comment]
Thank you Alex
