### ISSUE TITLE
CaService: indicate() might not be activated

### ISSUE THREAD

**Issue by HuyTyskland** [riebl/artery#287]
Hello everyone,

Currently, I am using `CaService` as a service for my `artery.inet.car`. As far as I understand (based on chapter 12 of the book "Recent Advances in Network Simulation"), the `indicate()` method is activated when a message is received. However, it seems like that method is not activated in my case or I understand it incorrectly.

**Situation**: I want to count the number of sent and received message. So I declared `NumSent` and `NumReceived` variable to record those data. I, then, registered two signals corresponding to the "sent" and "received" counter. The "sent" signal is emitted in `CaService::sendCam()` with the 'NumSent` and the "received" signal is emitted in the `CaService::indicated()` with the `NumReceived`.

**Problem**: while the `NumSent` is displayed in the statistics of Omnet++, the `NumReceived` is not.

**Approach**: I used gdb to set 2 breakpoints at the place where I emitted the two signals but only the one at `CaService::sendCam()` worked. I doubt that the `indicated()`  was not executed when my simulation was running.

**Question**: Do I understand `indicated()` incorrectly or something caused this issue?

Kind regards,
Huy Nguyen.

**Comment by HuyTyskland** [comment]
A little update: it seems like the problem is about my scenario, not the `CaService`. I run the `debug_example` which also uses `CaService`. I set three breakpoints at `sendCam()`, `indicate()`, and the one at `indicate()` did show up.
So I think it's more about my scenario.

**Comment by awillecke** [comment]
Hey,

can you share the relevant parts of your scenario configuration?
The  `*.node[*].middleware.services` parameter and the corresponding XML file would be of interest here. 

Also: is there more than one vehicle in your scenario that is equipped with the `CaService` by the mapper? The sender won't receive its own message.

Best regards
Alex

**Comment by HuyTyskland** [comment]
Hello @awillecke 

My omnetpp.ini is [here](https://github.com/HuyTyskland/artery_thesis/blob/receptionSendingStatistic/scenarios/step1_multilane_noConsideration/omnetpp.ini). The middleware service of each node is using `CaService` as regulated [here](https://github.com/HuyTyskland/artery_thesis/blob/receptionSendingStatistic/scenarios/step1_multilane_noConsideration/services.xml). I used `artery.inet.car` in my [vehicles.xml](https://github.com/HuyTyskland/artery_thesis/blob/receptionSendingStatistic/scenarios/step1_multilane_noConsideration/vehicles.xml).

Yes, I know the sender cannot receive its message. Currently, there are only 6 vehicles in my simulation as described [here](https://github.com/HuyTyskland/artery_thesis/blob/receptionSendingStatistic/scenarios/step1_multilane_noConsideration/highway_insertion_6lanes.rou.xml). However, other vehicles also do not receive any CAM. I filtered the result in General.anf with "middleware" and in all 6 vehicles, only the # of sent messages are displayed.

best regards,
Huy Nguyen.

**Comment by awillecke** [comment]
I think you need to change the [listener port](https://github.com/HuyTyskland/artery_thesis/blob/receptionSendingStatistic/scenarios/step1_multilane_noConsideration/services.xml#L4) to 2001 since CAMs are [sent to this BTP port](https://github.com/riebl/artery/blob/master/src/artery/application/CaService.cc#L176).

**Comment by HuyTyskland** [comment]
hello @awillecke  that indeed true. that fixed the issue.

Thank you very much.
