### ISSUE TITLE
DENM - New usecase

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#288]
Hi,

When trying to add a new usecase for DENM service, following error occured.

std::runtime_error: Can't determine size for unaligned PER encoding of type DENM because of Latitude sub-type -- in module (artery::VehicleMiddleware) World.node[0].middleware (id=23), at t=1.159284461639s, event #5

What could be the reason behind this? 

Regards,
Ambica

**Comment by fysch** [comment]
Hi, take a look at #200.
You need to make sure that your Latitude-value is within bounds, and maybe you need to add `projParameter` to the `<location>`-Tag in your scenario.

**Comment by Ambica2022** [comment]
Hi,

Thank you. It is working.

Regards,
Ambica
