### ISSUE TITLE
Supported: DSC - DCC Sensitivity Control and TAC - Transmit Access Control.

### ISSUE THREAD

**Issue by HuyTyskland** [riebl/artery#289]
Hello everyone, 

Currently, I am adapting ETSI DCC control mechanism in multi-lane platoons. Beside Transmit Power Control and Transmit Rate Control, I also saw DSC (DCC Sensitivity Control) and TAC (Transmit Access Control) are DCC-Access mechanisms. 

I wonder if DSC and TAC are supported in Artery or only TPC, TRC, and TDC are supported. If not, do you suggest any alternative to test those mechanisms? So far, I don't see any part about this in Artery.

Best regards,
Huy Nguyen.

**Comment by riebl** [comment]
I no longer remember the original source, but DSC is considered unfair AFAIK. Just imagine that one vehicle sets the threshold at -80 dBm and another at -70 dBm: The station with the -70 dBm threshold will ignore all those receptions between -80 and -70 dBm, which don't contribute to the channel busy ratio (CBR) then. Consequently, this station has a lower CBR and thus fewer transmission restrictions, though the channel is equally congested.
Thus, I never had a big interest in DSC. However, it could be implemented by modifying the CBR calculations based on power levels, see `PowerLevelRx`.

TAC is simply a queueing discipline, and the one described in the (old) ETSI DCC specification does not look smart to me at all. I guess that's also why it was dropped later on. There are transmit queues in Vanetza, though.

**Comment by HuyTyskland** [comment]
Hello @riebl 

Sorry for this very late reply. I see the point now.

Thank you for your reply.
