### ISSUE TITLE
Detecting Pedestrians

### ISSUE THREAD

**Issue by akhilsimha7** [riebl/artery#295]
Dear @vandit86,

adding pedestrians to Artery should be feasible without too much effort. I have not worked on this yet, however.
Detection of pedestrians would be possible as soon as "SUMO persons" are added to the `GlobalEnvironmentModel`.
For the communication part, `BasicNodeManager` would need to create OMNeT++ module instances for pedestrians similar to how it handles vehicles at the moment.

_Originally posted by @riebl in https://github.com/riebl/artery/issues/145#issuecomment-739801149_
            

Was anyone able to get this working? I just want the pedestrians to be detected by the sensors.

**Comment by riebl** [comment]
You will need to add persons in the `GlobalEnvironmentModel` similar to vehicles. The relevant code section is this: https://github.com/riebl/artery/blob/4bc468e372091fa392d43c5fc3358821a21534c9/src/artery/envmod/GlobalEnvironmentModel.cc#L259-L272

As you can see, it currently only adds and removes vehicles. You will need to add `EnvironmentalModelObject` instances for each SUMO person.
