### ISSUE TITLE
Help needed: Docker Documentation needed

### ISSUE THREAD

**Issue by Enough7** [riebl/artery#296]
Hi,

I got it eventually working after some [strugle](https://github.com/riebl/artery/issues/154#issuecomment-1613732253). 
Now I am wondering how do I use this container.
When I start it I would expect an graphical interface showing up.
I guess this might be not possible.
So my next expectation would be that the container acts as some sort of building helper.
If this is the case how do I start Artery from my host system?

Best regards

I also get on start this error
```
<!> Network '' not found, check .ini and .ned files
```

**Comment by riebl** [comment]
Artery's Docker container does not include any GUI. Neither OMNeT++ nor SUMO are built with their graphical frontends.
The idea of having Artery in a container is to run multiple instances with different parameter sets, e.g. running a large parameter study on a cluster.

For a graphical interface, I recommend running Artery natively on your host or via Vagrant on a virtual machine.

**Comment by Enough7** [comment]
Ahhh okay I understand.
Do you mind if I add your given information to the project?
Maybe in the readme or the dockerfile as a comment.
