### ISSUE TITLE
plot between "receiving power of a receiver" and "distance from transmitter"

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#299]
> Dear Yichao,
> 
> RSSI is usually a device-dependent metric, which is hard to compare between manufacturers. Hence I recommend going for the received signal strength expressed in dBm instead. As you have already discovered, the received power is calculated by INET but not passed up to the application layer. Extending every layer to pass-through this information might be a little bit too much effort. I would try this way:
> 
>     * extend `PowerLevelRx` (could be a sub-class) by a getter which allows access to the power level of the last received packet
> 
>     * the application module looks up your customized `PowerLevelRx` module during initialization, which should be located at _.wlan[0].max.rx_
> 
>     * cast the looked-up `cSimpleModule` to the `PowerLevelRx` class type and store it in a member attribute of the application module
> 
>     * the application can then retrieve the last received power level at data indication: Since there is no delay while passing up a packet from the radio to the application layer, the getter gives you the power level of the just received packet.
> 
> 
> I admit this approach is a little bit hacky, as it violates the OSI layer isolation. In my opinion, this hack is acceptable for some experiments, though.
Hi,
@riebl , will this https://inet.omnetpp.org/docs/showcases/wireless/pathloss/doc/index.html help in finding received signal strength? If so, how to use it in Artery? 
Actually I need to plot a graph between receiving power of a receiver and distance from transmitter.
 
Thank you,
Ambica

_Originally posted by @Ambica2022 in https://github.com/riebl/artery/issues/264#issuecomment-1645277593_

**Comment by riebl** [comment]
Hi @Ambica2022, these path loss models are used to derive the received signal strength from the transmission's power. However, this model is attached to the global World.radioMedium whereas PowerLevelRx exists for each vehicle. Thus, I don't believe that the PathLoss model is the right spot to intercept the individual signal strengths.
