### ISSUE TITLE
Get the exact number of sent message from services

### ISSUE THREAD

**Issue by denkipez** [riebl/artery#300]
Dear Riebl, 

I've been working on the mtits2017 scenarios, and i would like to know how could i get the exact number of sent message by the service. Actually i got the number of messages sent when the service has been called but it doesn't take into count the number of  messages are sent to every vehicles in the zone. Do you know how i might change this ? 

I did sum every messages sent and received messages, and there is way more received messages than sent message. Which leads to a loss rate way higher than 1. 

Thank you for your help!

**Comment by fysch** [comment]
Hi,
since most messages are sent as broadcast, the message is only sent once but received by multiple vehicles. Therefore, you can't just divide these numbers to get the loss rate.

I suspect with "in the zone" you mean the maximum transmission range?
If you know the maximum transmission range (in meters) of your radio, you could use the SeeThroughSensor to get the number of vehicles in range.

**Comment by denkipez** [comment]
Dear Fysch, 

Thank you for your answer !

Yes, the "zone" was the maximum transmission range, but each message has a request that tells the range of the zone where vehicles will receive the message. 

How do i enable the SeeThroughSensor ? Will the output be a vector that tells every middleware update the number of vehicle in the transmission range?

**Comment by fysch** [comment]
> each message has a request that tells the range of the zone where vehicles will receive the message.

I'm assuming you send a GeoBroadcast and here you mean the destination area of your request?
This destination area will most likely be different from the maximum transmission range of your radio.
Please see the [ETSI EN 302 636-4-1](https://www.etsi.org/deliver/etsi_en/302600_302699/3026360401/01.04.01_60/en_3026360401v010401p.pdf) if you want to know how GeoBroadcast works in detail.


> How do i enable the SeeThroughSensor ? Will the output be a vector that tells every middleware update the number of vehicle in the transmission range?

Have a look at the example scenario in `scenarios/artery`. With the `sensors.xml` file, you can equip vehicles with different kinds of sensors. Further configuration of those sensors is done in the `omnetpp.ini` file.
You also need to familiarize yourself with the [EnvironmentModel](http://artery.v2x-research.eu/features/envmod/).
The sensor will get you a list of vehicles that are within the defined sensor range.

**Comment by riebl** [comment]
I usually record the vehicle positions along with transmission and reception events for calculating the loss or reception rates. The recorded OMNeT++ vector files can be processed with a Python script, for example. For each transmission event, I can look up the vehicles within a (theoretical) maximum transmission range in this data set. Then you only need to further look up the number of receptions for this particular transmission.
Admittedly, this is a little bit of post-processing effort but I don't see how we could directly record such a metric with OMNeT++.
