### ISSUE TITLE
Information exchanging between modules and Number of entries in Location table

### ISSUE THREAD

**Issue by HuyTyskland** [riebl/artery#303]
Dear @riebl and everyone,

Currently I am working with Artery and Vanetza and I have two questions:
- I am doing some reading about the location table in GeoNet and I am curious how can I retrieve the number of entries (corresponding to the estimated number of neighbouring of an ITS)? I looked at the location table class and the SoftStateMap class and haven't figured out which function/variable I can use. I can add a counter to the location table class but I want to make sure not reinventing the wheel.

- With the Vanetza module, how can I make the `dcc` sub-module and `router` sub-module to exchange information. To be specific, I want to periodically send the number of entries from the first question from `router` sub-module to `dcc` submodules. 

Kind regards,
Huy Nguyen.

**Comment by fysch** [comment]
> how can I retrieve the number of entries (corresponding to the estimated number of neighbouring of an ITS)? 

You can get an iterator over all neighbours by calling `LocationTable::neighbours()`.
`std::distance(neighbours.begin(), neighbours.end())` should then give you the number of neighbours.
However, if efficiency is important, it might be better to implement a new counter.


>  With the Vanetza module, how can I make the `dcc` sub-module and `router` sub-module to exchange information.

If you want communication between modules in Artery, the easiest way might be using omnetpp signals.
The dcc submodule can then subscribe to the signal and the router can emit signals.
There are plenty of examples in Artery, where you can get inspired.

**Comment by HuyTyskland** [comment]
hello @fysch , thank you for your reply. Indeed there are examples about emitting signals and subscribing signals in Artery as I am reading those.

However, I am a bit confused about the process so would you mind correcting me on this:
- Let say I want to emit CountSignal attached with variable Count from A.cc and A.ned from `Router` submodule. I can do the signal registration and signal emitting from A.cc and A.ned. 
- However, I am confused about the process of subscribing and extracting information from the signal. Assume that I need the CountSignal at B.cc of the `dcc` submodule. With the emitting I describe, I will need to subscribe to CountSignal in the `initialize()`, and then I will write a function called `receiveSignal()`. Am I right?
If so, I have a question about the set of inputs for `receiveSignal()`: 
1. always the omnetpp cComponent: `cComponent*`
2. simsignal_t signal: `simsignal_t signal`
3. the type of the variable/object that attached with the signal (in my case it is `int` of the Count variable):`int countValue`
4. always a cObject*: `cObject*`
Let say, I want to assign another variable, ReceivedCount, declared in B.h with Count. I can just do ` ReceivedCount = countValue`. Am I right?

**Comment by fysch** [comment]
> Am I right?

Yes, that seems correct.


> Also, do I need to add anything to `connections` in `Vanetza.ned` files or anything similar to establish connection between `dcc` submodule and `router` submodule?

Afaik: no.
Your sender-class just needs to inherit from `omnetpp::cComponent` and the receiver-class from `omnetpp::cIListener`.
And in the .ned file of the sender-class you need to declare the signal by using `@signal`.


A more detailed explanation is also available in the [Simulation Manual (chapter 4.14.2)](https://doc.omnetpp.org/omnetpp/SimulationManual.pdf)

**Comment by HuyTyskland** [comment]
Ah I understand. Thank you very much

**Comment by fysch** [comment]
Assuming you are in `src/artery/networking/Router.cc`:
```
auto neighbours = getLocationTable().neighbours();
auto numNeighbours = std::distance(neighbours.begin(), neighbours.end());
```
If you are somewhere else, you need to find a way to get access to the LocationTable.

**Comment by HuyTyskland** [comment]
Hello @fysch , your suggestion works so thank you for that.

On the listener's side, there is an issue. So the class I am working right now is `LimericDccEntity` class inherited from `DccEntityBase` class inherited from `omnetpp::cListener` class. In the `DccEntityBase` class, the function `receiveSignal()` is defined. However that is not what I want. That is why I defined another `receiveSignal()` in LimericDccEntity. And I think that leads to my problem.

Problem: before declaring `receiveSignal()` in LimericDccEntity.h and defining it in LimericDccEntity.c and after subscribing the signal I want in LimericDccEntity, I have a signal called `avgCBR` and it is displayed as a vector. However, right after I declared and defined `receiveSignal()`, that caused `avgCBR` to disappear. 

What might be the cause of this issue and do you have any suggestion on this?

**Comment by HuyTyskland** [comment]
I can solve it now. 
I misunderstood the `subscribe()` and that was why I could not receive anything.

No worries and thank you. I shall close this issue
