### ISSUE TITLE
duplicated DENM messages 

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#311]
Hi,

I noticed that DENM message is received multiple number of times by the receiver even though it is sent only once by the sender.
For example   
denmsent : 1 (Vehicle 1)
denmreceived : more than 15....all 15 are with same denmactionId but at different times(Vehicle 2)

Any clue on this?Thanks in advance.

Regards,
Ambica

**Comment by riebl** [comment]
All received DEN messages are passed to the DEN service, including those received by forwarding stations. Thus, it is perfectly normal that you receive the same DEN message multiple times.
Other than CAMs which are "single hop broadcast" (SHB), DENMs employ the GeoBoardcast (GBC) mechanism to enhance the coverage. However, the ETSI ITS-G5 standard has some flaws regarding the Contention-Based Forwarding (CBF) algorithm used by default for GeoBroadcast. One effect is a rather poor rejection rate of duplicate messages.

**Comment by riebl** [comment]
Yes, only the first reception of a distinct DENM message is usually relevant.
The "pattern" depends on many aspects such as the network topology, vehicle density, and channel congestion.

**Comment by Ambica2022** [comment]
Thank you
