### ISSUE TITLE
updateDENM and terminateDENM

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#312]
Hi,

When I try to update DENM,noticed that new denmActionId is generating.....actually same  denmActionId should be maintained for updateDENM until station_Id of originating vehicle remains same. 
Actually I did not find code related to updateDENM and terminateDENM in artery.Is it available?If so,can somebody give me a clue.Thank you.

Regards,
Ambica

**Comment by riebl** [comment]
Our DEN service relies on multiple `den::UseCase` implementations located in *src/artery/application/den*. Each of these implementations decides when a particular DENM for the respective use case shall be generated and how the DENM shall be filled. If a use case involves *update* or *termination* DENMs, it is the use case's responsibility to maintain the necessary data. For many use cases, a prior DENM is never terminated but just becomes outdated and will not be sent anymore.

**Comment by Ambica2022** [comment]
Thank you Raphael
