### ISSUE TITLE
CAM and DENM messages

### ISSUE THREAD

**Issue by Ztalhai** [riebl/artery#320]
I want to see the CAM (cooperative Awareness Message) and DENM (Decentralized Environmental Notification Message) messages in the artery simulation framework, but I could not find them. How can I see these messages on the simulation?

**Comment by riebl** [comment]
You can "see" these messages in the OMNeT++ event scheduler's future event list. They are not visualized on the canvas, however.

**Comment by Ztalhai** [comment]
Thank you for this information, but I cannot see some of these messages in Artery's ready-made examples, how can I integrate them into the examples and see them?
