### ISSUE TITLE
DEN use cases

### ISSUE THREAD

**Issue by Ztalhai** [riebl/artery#321]
enter parameter 'World.node[0].middleware.DEN.useCases' : 
After adding the story.py file to the highway-police scenario, when I want to run it, I see a text like this and I don't know what to write here.

**Comment by riebl** [comment]
This is not related to any *story.py* file but to an activated *DenService* in your *services.xml*.
See https://github.com/riebl/artery/blob/d4cc6fabff42c6c39e344da8a5ac849028175cf6/scenarios/storyboard/omnetpp.ini#L19 for an example of how to configure the DEN service, i.e. which of its use cases shall be enabled. Of course, you can also add your own use cases if you want to.
