### ISSUE TITLE
connecting artery simulation scenario with the external v2x device

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#322]
Hi,

I would like to connect artery simulation scenario with the external v2x device, device's state of v2x stack is controlled with MQTT messages. Could you please help me with the initial steps to be done?

Regards,
Ambica

**Comment by riebl** [comment]
You will most likely need a special event scheduler for this purpose to synchronize time between simulation and your external device. Have a look at the testbed scenario and its use of `artery::TestbedScheduler`. This should give you a good idea how to insert events in the simulation on behalf of your external device.

**Comment by Ambica2022** [comment]
Thank you.
How to send facility layer messages(CAM/DENM) from Artery to external v2x stack through ethernet?

Regards,
Ambica

**Comment by Ambica2022** [comment]
Hi,

Can this be achieved with Transfusion service?

Thanks,
Ambica
