### ISSUE TITLE
Traffic Lights management

### ISSUE THREAD

**Issue by alizz-99** [riebl/artery#323]
Hello! 
I have created a service to incorporate it in the RSU, and I would like to control the traffic lights from this service. For example, the vehicles has the mVehicleController = &getFacilities().get_const<traci::VehicleController>(); but for the RSU-s this doesn't work for me. I don't know if there is any other way to get to the traci data from these service files.

Thank you!!

**Comment by riebl** [comment]
An RSU is not a vehicle and thus has no `VehicleController`. You can get access to the TraCI API via the *World.traci.core* module, though. 

1. Look up the *World.traci.core* module:  `cModule* traci = getModuleByPath("World.traci.core");`
2. Cast `cModule*` to `traci::Core*`: auto core = check_and_cast<traci::Core*>(source);
3. Get API object from Core: `core->getAPI()`

Of course, you should check for each step if the operation was successful, i.e. that no null pointer is returned.
