### ISSUE TITLE
Problem with adding new files to INET (<!> Error: Cannot load library) 

### ISSUE THREAD

**Issue by Meghna2069** [riebl/artery#324]
Hello ! 

Please, I need your help with the following issue, actually, each time i create a new module under inet i get the following error: "<!> Error: Cannot load library '/home/laptop/artery/build/src/artery/envmod/libartery_envmod.so': /home/laptop/artery/build/extern/libINET.so: undefined symbol: _ZTIN4inet9ieee802114glvfE" 

I do not understand what is the reason behind this error, although i enter make cleanall and make makefiles each time i add a new file, i am always getting this error and i do not think that it is a coding issue because when i put the same code in files that already exist under inet, i do not get this error, what shall i do please, it's been days now since i faced this error and i can not move on ! 

Thank you very much in advance for your help !

**Comment by Meghna2069** [comment]
Thank you for replying ! 

Here are the warnings i see when i run my project: 

"/home/laptop/artery/extern/inet/src/inet/common/serializer/SerializerBase.cc: In destructor ‘virtual inet::serializer::SerializerRegistrationList::~SerializerRegistrationList()’:
/home/laptop/artery/inet/src/inet/common/serializer/SerializerBase.cc:163:129: warning: throw will always call terminate() [-Wterminate]
  163 |         throw cRuntimeError("SerializerRegistrationList not empty, should call the SerializerRegistrationList::clear() function");
      |                                                                                                                                 ^
/home/laptop/artery/extern/inet/src/inet/common/serializer/SerializerBase.cc:163:129: note: in C++11 destructors default to noexcept" 

"/home/laptop/artery/extern/inet/src/inet/common/serializer/ipv4/IPv4Serializer.cc: In destructor ‘virtual inet::serializer::IPv4OptionSerializerRegistrationList::~IPv4OptionSerializerRegistrationList()’:
/home/laptop/artery/extern/inet/src/inet/common/serializer/ipv4/IPv4Serializer.cc:409:129: warning: throw will always call terminate() [-Wterminate]
  409 |         throw cRuntimeError("SerializerRegistrationList not empty, should call the SerializerRegistrationList::clear() function");
      |                                                                                                                                 ^
/home/laptop/artery/extern/inet/src/inet/common/serializer/ipv4/IPv4Serializer.cc:409:129: note: in C++11 destructors default to noexcept" 

"In file included from /home/laptop/artery/extern/simulte/src/stack/mac/layer/LteMacEnbD2D.cc:14:
/home/laptop/artery/extern/simulte/src/stack/mac/amc/AmcPilotD2D.h: In member function ‘virtual std::vector<short unsigned int> AmcPilotD2D::getMultiBandCqi(MacNodeId, Direction)’:
/home/laptop/artery/extern/simulte/src/stack/mac/amc/AmcPilotD2D.h:54:83: warning: no return statement in function returning non-void [-Wreturn-type]
   54 |     virtual std::vector<Cqi>  getMultiBandCqi(MacNodeId id, const Direction dir) {};
      |                                                                                   ^
"

The problem is that i do not see my modified files, neither do i  see the ones i added during compilation and then i get the message error that indicates that it can not load library ! 

Do you think that the error might exist in the code ? Aren't they any other reasons behind this compilation error ? and why i do not see the files i added during execution of my project ? Have you got an idea about that please ?

**Comment by riebl** [comment]
When adding new files to INET you will need to run the configuration stage of CMake again, i.e. go to your build directory and invoke `cmake ..` there. This step will search for all source files found in the *extern* subdirectories and add them to the build target. A follow-up build will then include also the new source files.
