### ISSUE TITLE
Segementation fault (core dumps) in artery::FovSensor::refreshDisplay

### ISSUE THREAD

**Issue by JiahaoZZhang** [riebl/artery#329]
Hello all,
In our simulation, we equiped RSUs with FovSensor with following configuration in omnetpp.ini si;imilar to the scenario rsu_grid:

*.staticNodes.nodes = xmldoc("RSUs.xml")
*.rsu*.environmentModel.*.drawSensorCone = true
*.rsu*.environmentModel.*.drawLinesOfSight = true
*.rsu*.environmentModel.*.drawDetectedObjects = true
*.rsu*.environmentModel.*.drawBlockingObstacles = true
*.rsu*.environmentModel.sensors = xmldoc("rsusensors.xml")

in addition, we add the following configuration to vehicles:

*.node[*].environmentModel.*.drawSensorCone = true
*.node[*].environmentModel.*.drawLinesOfSight = true
*.node[*].environmentModel.*.drawDetectedObjects = true
*.node[*].environmentModel.*.drawBlockingObstacles = true

At the end of the simulation (after executing all program), we always have a problem of:
Segmentation fault (core dumped)
scenarios/CMakeFiles/run_Tjunction.dir/build.make:70: recipe for target 'scenarios/CMakeFiles/run_Tjunction' failed
make[3]: *** [scenarios/CMakeFiles/run_Tjunction] Error 139
CMakeFiles/Makefile2:12971: recipe for target 'scenarios/CMakeFiles/run_Tjunction.dir/all' failed
make[2]: *** [scenarios/CMakeFiles/run_Tjunction.dir/all] Error 2
CMakeFiles/Makefile2:12978: recipe for target 'scenarios/CMakeFiles/run_Tjunction.dir/rule' failed
make[1]: *** [scenarios/CMakeFiles/run_Tjunction.dir/rule] Error 2
Makefile:5626: recipe for target 'run_Tjunction' failed
make: *** [run_Tjunction] Error 2

We use the mode debug and we get the following error:
0x00007fffeda23aee in artery::FovSensor::refreshDisplay (this=<error reading variable: Cannot access memory at address 0x7fffffffb3c8>)
    at /src/artery/envmod/sensor/FovSensor.cc:250
warning: Source file is more recent than executable.
250             mSensorConeFigure->setPoints(points);

Do you have any idea of what could be the origin of the bug?

Thank in advance,
jiahao

**Comment by riebl** [comment]
Thanks for reporting this issue, it is fixed in our *master* branch now.
