### ISSUE TITLE
Error on run_example

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#33]
While trying to run the simulation "run_example", right after selecting the chosen config and trying to start the simulation, I'm getting this error:

std::runtime_error: Can't determine size for unaligned PER encoding of type CAM because of Latitude sub-type -- in module (artery::VehicleMiddleware) World.node[0].appl.middleware (id=16), at t=0.260276337038s, event #5

Is this a known error?

**Comment by riebl** [comment]
I assume the problem has been identified properly -> Close.

**Comment by goksunazlican** [comment]
> While trying to run the simulation "run_example", right after selecting the chosen config and trying to start the simulation, I'm getting this error:
> 
> std::runtime_error: Can't determine size for unaligned PER encoding of type CAM because of Latitude sub-type -- in module (artery::VehicleMiddleware) World.node[0].appl.middleware (id=16), at t=0.260276337038s, event #5
> 
> Is this a known error?

Hi, I have the same issue. Did the written solutions work for you? I have the proj library but still the same.
