### ISSUE TITLE
Equip services to vehicles

### ISSUE THREAD

**Issue by alizz-99** [riebl/artery#331]
Hi! I am trying to equip my own service to vehicles, and I want to filter it according to their type. For example, only equip cars that are "car-shuttle" type. I do it in the following way:
```
<services>
    <service type="CarService">
        <listener port="2001" />
        <filters><type pattern="car-shuttle" /></filters>.
    </service>
</services>
```
but then no car is equipped with my CarService. In filters, the type tag is used for that?

Thank you very much!

**Comment by riebl** [comment]
Example usage at https://github.com/riebl/artery/blob/ef807a74fd2eba48abd2c31b4a7f5a8a895a9027/scenarios/artery/services.xml#L6

The type filter checks the module type of the host entities.
