### ISSUE TITLE
Problems running CAM Fixed and Dynamic with the same scenario

### ISSUE THREAD

**Issue by hpmjunior78** [riebl/artery#333]
I've built a higway scenario to run the CAService in Fixed and Dynamic CAM generation methods. Weirdly, both runs are giving the same results: same numbers of CAMs sent; same CAMGenerationDeltaTime. Considering speed of cars are high, the number of CAMs should be much higher in dynamic method. Where am I goind wrong? I'm choosing between Fixed and Dynamic only in OMNET QTEnv GUI.

**Comment by riebl** [comment]
Please have a look at the bundled car2car-grid scenario, which has configurations for fixed rate and dynamic CAM generation rules. I suppose the parameters are not set correctly in your simulation configuration; you can check these in the module tree of the GUI at each vehicle's CA service.

**Comment by hpmjunior78** [comment]
"which has configurations for fixed rate and dynamic CAM generation rules", do you mean omnetpp.ini? If yes, my file looks like
![Captura de tela de 2024-04-16 18-28-59](https://github.com/riebl/artery/assets/47758059/d5af8a71-66b0-476c-93f6-5ea6d1676226)
I've included some configurations in cam_dynamic part, trying to receive different results but cam_dynamic and cam_fixed keep showing the same number of CAMs sent and received.

**Comment by hpmjunior78** [comment]
Hi Riebl, thanks for your answers. I've checked QtEnv GUI and I understand that the parameters are being applied to all vehicles. Unfortunately, Dynamic and Fixed CAMs keep showing the same result for a highway scenario with speed values varying from 1 to 35 m/s. I'm sending attached some figures with GUI parameters.
[Artery-CAService-CAMStatic.pdf](https://github.com/riebl/artery/files/15080803/Artery-CAService-CAMStatic.pdf)
[Artery-CAService-CAMDynamic.pdf](https://github.com/riebl/artery/files/15080810/Artery-CAService-CAMDynamic.pdf)

**Comment by riebl** [comment]
Okay, your parameters look sane. Unfortunately, it is quite tricky to analyse what is going wrong in your setup remotely. Can you please check if the *car2car-grid* scenario works as expected? With this scenario I see a different number of generated CAMs for sure. Maybe this helps us to track down your issue.
