### ISSUE TITLE
about a cmake error

### ISSUE THREAD

**Issue by wangquandashabi** [riebl/artery#335]
while doing the step which run“$cmake ..”，it reported me that
“CMake Error at CMakeLists.txt:29 (if):
  if given arguments:

    "Boost_VERSION_STRING" "VERSION_GREATER_EQUAL" "1.75"

  Unknown arguments specified

”
the current boost version on my computer is 1.85，how can i deal with this cmake error？

**Comment by wangquandashabi** [comment]
the code ""Boost_VERSION_STRING" "VERSION_GREATER_EQUAL" "1.75"" is on Cmakelist.txt between line 29-31

**Comment by riebl** [comment]
Which version of CMake are you using?

**Comment by wangquandashabi** [comment]
The cmake version I am using is 3.5.1,is there something matter with it?

**Comment by riebl** [comment]
It turns out that "VERSION_GREATER_EQUAL" was introduced with CMake 3.7, so please update your CMake version. I will update the minimum required version in Artery's CMakeLists.txt accordingly.

By the way, CMake 3.5 is extremely old. Even Debian Buster (oldoldstable today) ships with CMake 3.13.

**Comment by wangquandashabi** [comment]
thanks for your answer!but after the step"$cmake .."completed successfully,an error occured on the next step
"$cmake --build . ".
It is reported that:
"/home/wangquan/artery/extern/vanetza/vanetza/access/g5_link_layer.cpp:32:45: error: 
      default initialization of an object of const type 'const
      ieee802::dot11::QosControl' without a user-provided default constructor
    static const ieee802::dot11::QosControl default_qos_control;
                                            ^
                                                               {}
1 error generated.
"
how can I deal with it? the current Cmake version has updated to 3.29.2
you can also know about the error report by view the picture.
<img width="561" alt="e9847b941c72efb0c999899c3a5dafe" src="https://github.com/riebl/artery/assets/166980607/16e75ebd-7863-4c04-9221-ea4d5e7a41b3">

**Comment by riebl** [comment]
Are you using an ancient Linux distribution? Looks like your C++ compiler is also not up-to-date, I suspect something like GCC 4.8 which has only incomplete C++11 support.
