### ISSUE TITLE
Regarding creating a new service to stationary nodes(rsu)

### ISSUE THREAD

**Issue by Chiqq** [riebl/artery#337]
Hi! !

I'm recently trying to create a custom service with my own scenario. Thanks to the documentations on the official website and example scenarios, I am currently be able to create new service to vehicle nodes. However, when it comes to stationary nodes, I will encounter the following error:

(NED module type "RSUService" not found (fully qualified type name expected) -- in module (artery::StationaryMiddleware) World.rsuRSU_0.middleware (id=34), at t=0.548813502304s, event #2)
![question1](https://github.com/riebl/artery/assets/168071347/0355e89c-78d8-40fb-b84c-b2fa4a01e079)

Here's my service setting:
1. Create the stationary points with RSUs.xml
```
<RSUs>
<rsu id="RSU_0" positionX="103.0" positionY="100.0">
    <antenna direction="-1.5707963267948966"/>
    <antenna direction="0"/>
</rsu>
</RSUs>
```
2. Define separate rsuservices.xml
```
<?xml version="1.0" encoding="utf-8"?>
<services>
	<service type="RSUService">
		<listener port="8001" />
	</service>
</services>
```
The RSUService.ned/.h/.cc are all located in the same scenario folder.

3. Set service.xml in omnetpp.ini
```
*.staticNodes.nodes = xmldoc("RSUs.xml")
*.node[*].middleware.services = xmldoc("services.xml")

*.rsu*.middleware.datetime = "2018-03-19 10:00:00"
*.rsu*.middleware.services = xmldoc("rsuservices.xml")
```
The vehicle nodes will use the services.xml which is separate with rsuservice.xml

4. Following the guideline to create the CMakeLists.txt
```
add_artery_feature(junctionservice VehicleService.cc RSUService.cc)
generate_opp_message(Blockagestatus.msg TARGET junctionservice DIRECTORY junctionservice_msgs)
add_opp_run(junctiontest CONFIG omnetpp.ini)
```

If I use services from application directory such as RsuCaService in the rsuservice.xml, there'll be no problem. So, I'm wondering that maybe something wrong with the CMakelist that it didn't account my RSUService.xml for stationary nodes. 

Could anybody help me?

**Comment by Chiqq** [comment]
> Hi! !
> 
> I'm recently trying to create a custom service with my own scenario. Thanks to the documentations on the official website and example scenarios, I am currently be able to create new service to vehicle nodes. However, when it comes to stationary nodes, I will encounter the following error:
> 
> (NED module type "RSUService" not found (fully qualified type name expected) -- in module (artery::StationaryMiddleware) World.rsuRSU_0.middleware (id=34), at t=0.548813502304s, event #2) ![question1](https://private-user-images.githubusercontent.com/168071347/325519274-0355e89c-78d8-40fb-b84c-b2fa4a01e079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTc5MTcsIm5iZiI6MTcxNDA5NzYxNywicGF0aCI6Ii8xNjgwNzEzNDcvMzI1NTE5Mjc0LTAzNTVlODljLTc4ZDgtNDBmYi1iODRjLWIyZmE0YTAxZTA3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMjEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTVmZjJkZTNkYWYwNTE3NThkNWEzNTk4ZmE0NTAyZTFjYWVjYzBiMDhjYmZmNTVkYWFiNWViYTRhOTEzODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NYcqVpmusqQCsYw2LYdm82clYqDoE3_i46dh9Ipa404)
> 
> Here's my service setting:
> 
> 1. Create the stationary points with RSUs.xml
> 
> ```
> <RSUs>
> <rsu id="RSU_0" positionX="103.0" positionY="100.0">
>     <antenna direction="-1.5707963267948966"/>
>     <antenna direction="0"/>
> </rsu>
> </RSUs>
> ```
> 
> 2. Define separate rsuservices.xml
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <services>
> 	<service type="RSUService">
> 		<listener port="8001" />
> 	</service>
> </services>
> ```
> 
> The RSUService.ned/.h/.cc are all located in the same scenario folder.
> 
> 3. Set service.xml in omnetpp.ini
> 
> ```
> *.staticNodes.nodes = xmldoc("RSUs.xml")
> *.node[*].middleware.services = xmldoc("services.xml")
> 
> *.rsu*.middleware.datetime = "2018-03-19 10:00:00"
> *.rsu*.middleware.services = xmldoc("rsuservices.xml")
> ```
> 
> The vehicle nodes will use the services.xml which is separate with rsuservice.xml
> 
> 4. Following the guideline to create the CMakeLists.txt
> 
> ```
> add_artery_feature(junctionservice VehicleService.cc RSUService.cc)
> generate_opp_message(Blockagestatus.msg TARGET junctionservice DIRECTORY junctionservice_msgs)
> add_opp_run(junctiontest CONFIG omnetpp.ini)
> ```
> 
> If I use services from application directory such as RsuCaService in the rsuservice.xml, there'll be no problem. So, I'm wondering that maybe something wrong with the CMakelist that it didn't account my RSUService.xml for stationary nodes.
> 
> Could anybody help me?

I now change the run setting in CMakelist.txt to:
'''
add_opp_run(junctiontest NED_FOLDERS ${CMAKE_CURRENT_SOURCE_DIR} CONFIG omnetpp.ini)
'''
Got no more error described above. Is this solution right?

**Comment by riebl** [comment]
Yes, the location of your new NED files needs to be included so OMNeT++ finds them during runtime.

**Comment by Chiqq** [comment]
Thank you very much for the reply and your time!!
