### ISSUE TITLE
VanetRx

### ISSUE THREAD

**Issue by sadek58d** [riebl/artery#34]
artery/src/artery/inet/VanetRx.cc:19:25: error: no matching function for call to ‘VanetRx::initialize(int&)’
     Rx::initialize(stage);
artery/extern/inet/src/inet/linklayer/ieee80211/mac/Rx.h:53:22: note: candidate: ‘virtual void inet::ieee80211::Rx::initialize()’
         virtual void initialize() override;
artery/extern/inet/src/inet/linklayer/ieee80211/mac/Rx.h:53:22: note: candidate expects 0 arguments, 1 provided

**Comment by sadek58d** [comment]
artery/extern/inet/src/inet/linklayer/ieee80211/mac/Rx.h:53:22: note:   candidate expects 0 arguments, 1 provided

**Comment by Venturina** [comment]
Could you please explain what you are trying when you face this error?

The inet in the correct version should have a `virtual void initialize(int stage) override;` method located in `artery/extern/inet/src/inet/linklayer/ieee80211/mac/Rx.h`. Can you check this please?

**Comment by salem8585** [comment]
yes thanks , that was version mismatch

**Comment by sadek58d** [comment]
Thanks, that was version mismatch
