### ISSUE TITLE
Is yaw_rate getting calculated?

### ISSUE THREAD

**Issue by Ambica2022** [riebl/artery#348]
Hi,

I noticed that curvature is calculated based on yaw_rate in vehicledataprovider.....but yaw_rate is not calculated anywhere.............but.........is set to "not a number" (NaN) using std::numeric_limits<double>::quiet_NaN() when an instance of VehicleKinematics is created.  is my understanding correct? or any clue how can I get it calculated? 

Thanks in advance.

Best Regards
Ambica

**Comment by riebl** [comment]
Both, `yaw_rate` and `acceleration` are calculated in `VehicleDataProvider::update`.
