### ISSUE TITLE
Omnet++ IDE project import

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#35]
Hello,

as discussed in: https://github.com/riebl/artery/issues/30

I successfully imported artery's build directory as a project into omnet's IDE, the issue is that the src folder inside the build directory doesn't contain the .ned files I require to use in my personal project. It actually only has a small amount of files from the original src project folder...

This is a issue, since i'm unable to import the .ned files I require to use in my personal project since the IDE is unable to find them on project explorer... Of course, I already have the original artery's path into my NEDPATH env. variable.

**Comment by Venturina** [comment]
I'm not sure why you are looking for the .ned files in your build folder?

If you take a look in `[Source directory]` in your Eclipse `Project Explorer` which .ned files are missing?

**Comment by 1140464BV** [comment]
I can't seem to find what you are referring to as "[Source directory] in your Eclipse Project Explorer"...

**Comment by Venturina** [comment]
![image](https://user-images.githubusercontent.com/9103855/45685036-6321d080-bb48-11e8-9f61-3293aeb4d3cc.png)

If this directory is missing, it seems that the import of the project did not work well. However, I'm not an expert with the omnet IDE as I personally do not use it.

**Comment by 1140464BV** [comment]
It really is missing... I followed this steps after git-cloning artery's project:

    Create a build which is sibling directory of the source directory (build directories as subdirectories of the source directory seem to be not well supported by Eclipse)
    cd into your created build directory and execute cmake (cmake path/to/your/artery)
    Generate Eclipse project files in your build directory (eg.: cmake /build/dir -G 'Eclipse CDT4 - Unix Makefiles')
    Open the IDE and import the project using your created build folder
    Add needed include paths
    The project's sources should be found in [Source directory] found in Eclipse's Project Explorer

This is my IDE tree:

![image](https://user-images.githubusercontent.com/33874410/45685294-d1629500-bb40-11e8-9a1d-882a4032162c.png)

What can this possibly be?

**Comment by Venturina** [comment]
For me, this happened when the `build` folder was located inside the artery directory.
After creating the `build` directory as a **sibling** directory of artery, the problem was gone.

Can you tell me what your `cmake /build/dir -G 'Eclipse CDT4 - Unix Makefiles'` outputs?

**Comment by 1140464BV** [comment]
So basically i should create the build directory **outside** artery's main folder, right? I was creating it as a artery subdirectory...

**Comment by Venturina** [comment]
Yes.. As I have explicitly told in my instructions..

> Create a **build which is sibling directory** of the source directory (**build directories as subdirectories of the source directory seem to be not well supported by Eclipse**)

**Comment by 1140464BV** [comment]
How should I create it then? typical _mkdir_ anywhere outside artery's main folder?

**Comment by 1140464BV** [comment]
Already was able to import artery to the IDE, with the required [Source directory] reachable through the IDE. 
What should be the way to import a .ned from the project? 
What path should I add to NEDPATH in order to be able to import this required files from this [Source directory] into my project?

**Comment by Venturina** [comment]
I would assume that you have to add all artery folders (artery's src, extern/inet, extern/veins, extern/simulte).
This is only a guess and I have also no idea how to manage that in the IDE, as we don't use the IDE for developing artery.
