### ISSUE TITLE
Sharing data between a service and an UdpApp running in the same node

### ISSUE THREAD

**Issue by JohnnyMinho** [riebl/artery#353]
Hello.
As said in the title i'm trying to share some data between a service and a UdpApp which are running in the same RSU.
I've already tried to do this trough signals but i'm getting nowhere since the signal isn't being received in the service.
Can someone give me a hint on how to do this?

**Comment by riebl** [comment]
The most simple way is to look up the other module on the same host, cast its pointer to the appropriate sub-class and call its methods directly then. Have a look at `inet::findModuleFromPar` or `inet::getModuleFromPar` which neatly handles the look-up and cast in a single step, e.g. used by `Router`.

**Comment by JohnnyMinho** [comment]
Hello! Thanks for the quick answer!
This is more related to signals, but it seems that the service isn't able to subscribe to the signal. I verified this trough the isSubscribed() method and it always returns that the signals wasn't subscribed.
Also, is it possible to use the idealChannel or the sendDirect method from omnet? This is more due to curiosity than to solve the problem.
Anyways, thanks once more!

**Comment by riebl** [comment]
Modules need to implement the `omnetpp::cListener` interface so you can handle incoming signals in them. Then, its inherited method `isSubscribed(signal, this)` should return true. Please note that signals are propagated upwards only in the module tree, i.e. when you subscribe for signals at a module it will only receive signals emitted by itself and its sub-modules.

Calling `cSimpleModule::sendDirect` should be feasible as well. I just prefer typed interfaces; with `sendDirect` you need to cast the generic `cMessage*` to its particular sub-type before you can get any specific data out of it.

**Comment by JohnnyMinho** [comment]
Once again thanks, everything is working at the moment.
By the way, I implemented the resume() and the stop and replace route commands in the TraCI api. I don't know if it is of any help to the project as a whole since it is a pretty small amount of lines and of limited use for most cases but if you need the altered code tell me.
