### ISSUE TITLE
NED types could not be fully resolved 

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#37]
Dear,

Afterimporting artery and integrating it into my project NED's, as I can see through the omnet's IDE all went with success. The problem is while trying to run my simulation, after the NED loading I get this error:

Error: The following NED types could not be fully resolved due to a missing base type or interface: artery.veins.ApplicationLayer, artery.veins.ConnectionManager, artery.veins.Mobility, artery.veins.ObstacleControl

What should this mean? any error on imports not caught by the IDE?

**Comment by Venturina** [comment]
Are the ned files located `artery/extern/veins` correctly added to your nedpath?

**Comment by 1140464BV** [comment]
I'm actually including a local veins installation that was installed some time ago for inclusion in a different project, it resembles a git installation of it, version 4.7.1... I'm importing artery's source code by copying it into my project sources directory and mannualy importing them correctly until no errors appear on my IDE...

**Comment by riebl** [comment]
So this is actually not an issue of Artery at all. Closing.
