### ISSUE TITLE
Error: Class "InetMobility" not found

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#38]
Hello,
after trying to include Car.ned from your project into one of my networks, with NEDPATH resolved correctly and with no error on .ned's loading, after this and on Network initialization, i get this error:

Error: Class "InetMobility" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) MANET.anode[0] (id=4), during network setup

Already confirmed InetMobility.cc has Define_Module() called...

**Comment by riebl** [comment]
@1140464BV Do you see any "undefined symbol" messages or alike in the command line prompt when starting the simulation environment?

**Comment by 1140464BV** [comment]
Not really. The error comes up right after Ned files loading and during Network set up. This Network refers Car.ned as a submodule.

**Comment by Venturina** [comment]
Can try to run your simulation with the command line run flag `-h classes`?
It should then print out all your registered classes. If everything runs like expected there should be a line containing `class InetMobility`. 

On my system, the output looks like the following:

> 
> OMNeT++ Discrete Event Simulation  (C) 1992-2018 Andras Varga, OpenSim Ltd.
> Version: 5.4.1, build: 180629-5e28390, edition: Academic Public License -- NOT FOR COMMERCIAL USE
> See the license for distribution terms and warranty disclaimer
> 
> Setting up Qtenv...
> 
> 
> Registered C++ classes, including modules, channels and messages:
>   class AckTimeOutMessage
>   class AirFrame11p
>   class AsioData
>   class AsioScheduler
>   class BaseMacLayer
>   class BaseMobility
>   class BasePhyLayer
>   class BaseWorldUtility
>   class BasicSafetyMessage
>   class BorderMsg
>   class CaObject
>   class CaService
>   class ChannelLoadReport
>   class ChannelSenseRequest
>   class ConnectionManager
>   class CounterFigure
>   class ExampleService
>   class GaugeFigure
>   class GeoNetPacket
>   class IndexedImageFigure
>   class IndicatorLabelFigure
>   class IndicatorTextFigure
>   class InetMobility
>   class InetRadioDriver
>   class LinearGaugeFigure
>   class LinearMobility
>   class Mac1609_4
>   class Mac80211Ack
>   class Mac80211Pkt
>  ...

**Comment by 1140464BV** [comment]
My simulation runs based on a executable, that follows some steps, that more or less follow this topics:

Running simulation based on configuration file: X
Running startup code fragments
some ROS stuff
Loading configuration ini file
Activating general section in configuration
Creating configuration object
Validating configuration
Setting user interface
Setting up Cmdenv...


Which step should I alter to introduce those flags?

**Comment by Venturina** [comment]
You have to run the `opp_run` with that `-h classes` flag.

Somewhere during your setup's startup phase, you call  `opp_run` with your libraries and your simulation's .ini file. At this point, you have to extend the command with the with `-h classes`.

You can trie that by simply calling `opp_run -h classes` somewhere in your terminal. This should only list all omnet base classes, not containing anything from veins or inet or artery.
As this gives you no information, you have to add the flag to your simulation's startup to check if all classes as registered properly (like indicated before).
