### ISSUE TITLE
SQLite error Not NULL constraint failed

### ISSUE THREAD

**Issue by MounaKaroui** [riebl/artery#41]
Dear Artery users, 
I have a problem, simulations starts normally  and then at 120 s, I obtain this bug :
"SQLite error 'NOT NULL constraint failed: vectorData.value' on file 'results/inet_rsu-#0.vec' while processing statistic signal stateChanged (id=124) with data type long, emitted from (inet::ieee80211::Contention)World.node[29].wlan[0].mac.hcf.edca.edcaf[3].contention -- in module (inet::ieee80211::Contention) World.node[29].wlan[0].mac.hcf.edca.edcaf[3].contention (id=2154), at t=120.781021488476s, event #500162"
Have you an idea about this kind of issues ? 
Regards, 
Mouna

**Comment by MounaKaroui** [comment]
I googled the problem, I tried to understand the origin of this problem : https://stackoverflow.com/questions/48297071/sqlite-not-null-constraint-failed
For my case this bug occurs when I increase the number of vehicles in the simulation, or when I set vehicle every second in sumo configuration file rou.xml.

**Comment by riebl** [comment]
Hi @MounaKaroui,

I haven't noticed this kind of error message yet. Since it is triggered when processing `@statistic` I assume that either the `@statistic` is not correctly configured or you have spotted an OMNeT++ bug.
Which version of OMNeT++ are you using? 5.4.1?
Is this problem occurring with Artery's master branch? Have you modified anything compared to master?

**Comment by MounaKaroui** [comment]
Hi @riebl, 
I am using  OMNeT++ 5.4.1.  I test it for my example, I tried to test that on Artery default example, another problem occurs which is "std::runtime_error: Can't determine size for unaligned PER encoding of type CAM because of SpeedValue sub-type -- in module (artery::VehicleMiddleware) World.node[5].middleware (id=547), at t=125.869631790672s, event #1853542".

**Comment by riebl** [comment]
@MounaKaroui Did the hint to #33 solve your problem? Please close this issue ticket if that is the case.

**Comment by riebl** [comment]
No update since a long time, closing.
