### ISSUE TITLE
Question about enabling security and changing the AnalogModel

### ISSUE THREAD

**Issue by oscarmex1986** [riebl/artery#45]
Hello. I don't think this goes in the issues page, but I'll post it anyway. I was wondering if the Security Entity is enabled by default, since Line 26 in Vanetza.ned shows: 
` security: <default("")>`
In the last version of Artery I was working with, this was dealt with in Middleware.ned, setting a value to true.
Also, and this might be more of a Veins question, do you happen to know how to activate the Nakagami analog model in config.xml? I mean, which tags and values would be the ones to write in there. 

Thanks!

**Comment by m-wegner** [comment]
For Nakagami we use the following entry in our omnetpp.ini:
```
*.radioMedium.pathLossType = "NakagamiFading"
```

**Comment by riebl** [comment]
Security is disabled by default for performance reasons. You can enable it by setting the typename of Vanetza.ned's security submodule to "artery.networking.SecurityEntity". SecurityEntity has further parameters to customise its behaviour, see SecurityEntity.ned.

m-wegner's approach works when you are using INET as foundation. For Veins, you need to edit the config.xml and set the AnalogueModel's type to "NakagamiFading" (not tested).

**Comment by riebl** [comment]
Sorry @oscarmex1986, it turns out that I have made another mistake when refactoring the integration of Vanetza in Artery. I have added a simple example to `scenarios/artery/omnetpp.ini`, the `inet_security` configuration, at 699a9a56c4d95e1eaf566ccd1c8d4a67b4379b9f.

**Comment by riebl** [comment]
Oops, that's embarrassing: I missed to add the `ISecurityEntity` module interface to the previous commit.

**Comment by oscarmex1986** [comment]
Great. Security is enabled now. Thanks.
