### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by masa1228masa** [riebl/artery#52]
Hello,
When I built, no error came out.
But when I did
"cmake --build build --target run_example"
and chose "veins" in Set Up inifile Configuration,
the following error occurred.

"""
A runtime error occurred:

Class "VeinsConnectionManager" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) World (id=1), during network setup

Launch a debugger with the following command?

nemiver --attach=12722 &
"""

Does anybody know how to fix this?
Please let me know.
Best regards,
Masahiro

**Comment by riebl** [comment]
Have you built Veins at all, i.e. called `make veins` in Artery's root directory?

**Comment by masa1228masa** [comment]
Yes! I did

`git clone --recurse-submodule https://github.com/riebl/artery.git`
`cd artery`
`make veins`
`make vanetza`
`make inet`
`mkdir build`
`cd build`
`cmake ..`
`cmake ..`
`cmake --build .`
`cmake --build build --target run_example`

I did "cmake .." twice because of #51.
Just in case, I built this under
Ubuntu 16.04.5
omnet++ 5.4.1
cmake 3.5.1
GNU make 4.1
gcc 5.4.0
g++ 5.4.0
boost 1.67.0

and I installed all requirements listed in veins, vanetza, omnetpp.

**Comment by masa1228masa** [comment]
Okey, I solved this problem.

I don't know in detail, but python environment was the problem.
I used pyenv to install python and this made the problem.
I uninstalled pyenv and built again.
And the problem was solved.

Sorry for bothering.
Best regards,
Masahiro
