### ISSUE TITLE
Debugging Artery

### ISSUE THREAD

**Issue by rtobi** [riebl/artery#53]
Hello guys,

I was able to configure the build in debug mode as mentioned in #48. Still I have some open issues regarding the debugging, hope someone can help me:
1) Using the gdb from the command line, I am able to start the simulation, also the QT environment launches. But whenever I try to set a breakpoint (using (gdb) break /file:line), the message "No Source file named ..." appears. Note, that full file path was used. What am I doing wrong?
2) Is it possible to debug the simulation from the Omnet++ environment in Eclipse? If yes, which setting I have to use?

Many thanks and best regards!

**Comment by danieladriano** [comment]
Hi @rtobi,

When the message "No Source file named ..." appears, just put "y" (without the quotes) to set your breakpoint

Ex:

(gdb) b PoliceServiceEnvmod.cc:17
No source file named PoliceServiceEnvmod.cc.
Make breakpoint pending on future shared library load? (y or [n]) y

Regards,
Daniel

**Comment by rtobi** [comment]
Thanks for your reply @danieladriano !
Yes, debugging with gdb using the command line is working in the meantime, exactly as you said. Although this is painful and slow. Think the message "No Source file named... " might not be helpful in order to get the Debugger running in Eclipse. Do you have experience how to set that up or do you know if it is even working?

Best regards,
Tobi

**Comment by danieladriano** [comment]
Hi @rtobi 

I agree, it's painful and slow. There is two issues treat about Artery running in Eclipse ([#11](https://github.com/riebl/artery/issues/11) and [#35](https://github.com/riebl/artery/issues/35)), maybe can help you. I don't use Eclipse for developing my application on artery, so i dont know if ir work.

Regards,
Daniel

**Comment by riebl** [comment]
Artery is not supporting Eclipse-based setups, i.e. you may get it running but it requires some manual work. Let me know if you have a proposal how to make Eclipse integration easier.
