### ISSUE TITLE
How to record x/y position of all vehicles?

### ISSUE THREAD

**Issue by m-wegner** [riebl/artery#54]
We want to record the x/y positions of all vehiceles in simulation, i.e., also those that do not run a middleware (PlainVehicle.ned).

We've found that a communicating car already has statistics for these metrics in (Car.ned)[https://github.com/riebl/artery/blob/master/src/artery/inet/Car.ned]:
```
@statistic[posX](source="xCoord(mobilityPos(mobilityStateChanged))"; record=vector?);
@statistic[posY](source="yCoord(mobilityPos(mobilityStateChanged))"; record=vector?);
```

However, we were not able to enable the recording of these statistics, even if we enabled everything globally.

Have we missed something and can you point us to the correct method to enable these statistics? Could we just add these lines to the `PlainVehicle.ned`, or do they need a middleware to be triggered? Are they currently triggered at all?

Thanks in advance!

**Comment by riebl** [comment]
Hi Martin,

those `posX` and `posY` statistics can be moved to `PlainVehicle` as they depend only on a signal emitted by the mobility submodule. Then these can be recorded for "dumb" vehicles as well.

Regards,
Raphael

**Comment by ruisonghan** [comment]
In the setting of your simulation, have u done this?

```bash
**.posX.result-recording-modes = vector
```
[https://doc.omnetpp.org/omnetpp/manual/#sec:ana-sim:direct-result-recording](url)

**Comment by riebl** [comment]
I consider this issue as resolved. Both statistics, posX and posY, have been moved to `artery.inet.PlainVehicle`, see a3131466.
