### ISSUE TITLE
Receive messages - RSU

### ISSUE THREAD

**Issue by danieladriano** [riebl/artery#59]
Hi @riebl  its me again :-)

I'm update my Artery fork for the newest version. I have a service running in a RSU (purely an OMNeT++ module) with send and receive messages for some vehicles using GBC. After the update, the application on RSU can send messages but no more receive.

The service running in the vehicle, can send messages V2V but not for my RSU. 

I have tested with SHB and then works fine.

My initial Artery fork is from September and I see there is a lot of changes since then. I'm trying to find the problem, but without success.

Do you have any idea what possible is wrong ?

Regards,
Daniel

**Comment by riebl** [comment]
Hi @danieladriano,

I have just checked GBC reception with `DenService` which seems to be working as intended. Hence, I do not assume that anything is severely broken. Did I understand you correctly that only the communication between RSUs and vehicles is broken but among the same type is working? Maybe the security entity is configured differently and thus dropped by one of them? You can check this by looking at `node[x].vanetza` (and `rsu[x].vanetza`) if `SecurityEntity` is present.

Regards,
Raphael

**Comment by danieladriano** [comment]
Hi @riebl ,

In my service, when the message have the vehicle as origin and a RSU as destine, the communication via GBC don't work. But the inverse (RSU to Vehicle) its working and V2V too.

If I change from GBC for SHB, the communication works fine.

About the security entity, I don't have `SecurityEntity` set at `node[x].vanetza` or `rsu[x].vanetza`.

This is my code for send a packet from vehicle to RSU.

```
void VehicleService::sendPacket(cPacket* packet)
{
    btp::DataRequestB req;
    req.destination_port = host_cast<VehicleService::port_type>(getPortNumber());
    req.gn.transport_type = geonet::TransportType::GBC;
    req.gn.traffic_class.tc_id(static_cast<unsigned>(dcc::Profile::DP1));
    req.gn.communication_profile = geonet::CommunicationProfile::ITS_G5;

    geonet::Area area;
    area.shape = geonet::Circle();

    using units::si::meter;
    geonet::Circle destination_shape;
    destination_shape.r = 100.0 * meter;
    area.shape = destination_shape;

    area.position.latitude = opLatitude;
    area.position.longitude = opLongitude;
    req.gn.destination = area;

    request(req, packet);
}
```

Thanks for the helping.

Regards,
Daniel

**Comment by danieladriano** [comment]
Hi @riebl ,

Thanks for the help and the bug fix. I will test my application again and give you a feedback.

I have no experience with test cases, but if I have any ideas, I will pass on to you.

Thanks again.

Regards,
Daniel
