### ISSUE TITLE
Error when building artery

### ISSUE THREAD

**Issue by tomas0620** [riebl/artery#63]
When building artery from scratch, we get the following errors:
`src/artery/CMakeFiles/core.dir/build.make:1203: recipe for target 'src/artery/CMakeFiles/core.dir/inet/AntennaMobility.cc.o' failed
make[2]: *** [src/artery/CMakeFiles/core.dir/inet/AntennaMobility.cc.o] Error 1
CMakeFiles/Makefile2:221: recipe for target 'src/artery/CMakeFiles/core.dir/all' failed
make[1]: *** [src/artery/CMakeFiles/core.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`

I have troubles with inet also (fixed by [this ](https://stackoverflow.com/questions/50212616/error-building-inet-in-omnet/50217982#50217982) )

full error after command `cmake --build .` is in this file:
[error.txt](https://github.com/riebl/artery/files/2888955/error.txt)

**Comment by riebl** [comment]
I assume INET's `IMobility` interface has changed from 3.6.4 (bundled with Artery) to 3.99.3 (the version mentioned on the linked stackoverflow page). Hence, those "marked 'override', but does not override" errors appear. I recommend to stick with the INET version referenced by Artery as git submodule.
A simple workaround for the "osgEarthUtil/ObjectLocator" problem: Either disable OpenSceneGraph entirely (see OMNeT++'s `configure.user` file) or install osgEarth.

**Comment by riebl** [comment]
No update since more than 14 days, closing.
Feel free to reopen this issue ticket if it is not resolved yet.

**Comment by fehlfarbe** [comment]
Hi I have the same problem with Ubuntu 18.04. I can build INET with `make inet WITH_OSGEARTH=OFF` but building artery with `cmake --build .` gives me the osgEarth error again:

```
inet/common/geometry/common/CoordinateSystem.cc:21:10: fatal error: osgEarthUtil/ObjectLocator: No such file or directory
 #include <osgEarthUtil/ObjectLocator>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
How can I pass `WITH_OSGEARTH=OFF` to the artery build command?

**Comment by riebl** [comment]
Either disable osgEarth entirely in your OMNeT++ installation (see its configure.user file) or you can pass additional arguments to make via the `MAKE_ARGUMENTS` CMake variable.

**Comment by fehlfarbe** [comment]
Thanks! Adding `set(MAKE_ARGUMENTS WITH_OSGEARTH=OFF)` to CMakeLists.txt did the trick!
