### ISSUE TITLE
Is there a way to send DENM messages on demand?

### ISSUE THREAD

**Issue by oscarmex1986** [riebl/artery#68]
I modified the example scenario that is run with --target run_example and I added custom road and took away the obstacles. In the default configuration, the services.xml have the CAM service and an Example service, but I would like to add DENM messages that are triggered on demand, let's say, each exponential(10 s). Is there a way to do so by just activating the DEN service in the services.xml file and modifying the trigger method in DenService.cc?  Or, is there an example of the DEN service that I can run and/or modify as the --taget run_example?

**Comment by riebl** [comment]
I suppose the easiest way to achieve this is to create a distinct service (`DummyDenService`?) which is transmitting a DENM whenever a previously scheduled self-message is handled.
