### ISSUE TITLE
repeated simulations failing due to pybind

### ISSUE THREAD

**Issue by oslind** [riebl/artery#69]
When repeating simulation runs, in omnet++ with the "repeat" keyword in the .ini file, pybind is initialized several times. This leads to an error in the "initialize_interpreter" function in embed.h stating: "The interpreter is already running".

**Comment by riebl** [comment]
Thanks for reporting this issue!

**Comment by ruisonghan** [comment]
Hi,

When I set ```repeat``` to a number, it didn't work as expected. 
Is this because of using Qtenv GUI? How could I change to the command line to execute my source code? Thanks a lot.

**Comment by riebl** [comment]
@ruisonghan https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:parameter-studies might be a good read for you. For big parameter studies I sometimes create a custom Makefile which calls `opp_run` then.
