### ISSUE TITLE
How to remove a vehicle from the simulation?

### ISSUE THREAD

**Issue by ruisonghan** [riebl/artery#71]
Hi, Riebl

I wrote a service which is modified from the CAM service and its main function is to regularly check the location of a vehicle and remove the vehicle if it reaches specific areas that I have defined. 

In this service, I called ```remove(self, vehID, reason)``` function from ```traci``` to remove the vehicle from SUMO and it did work. However, I don't know how to remove a vehicle from OMNeT++. 

I guess I should call some function from ```artery/src/traci/BasicNodeManager.cc``` to destruct a vehicle node but I am not sure about how to do it. Do u have any suggestion on this? 

Thanks.

**Comment by riebl** [comment]
Does the vehicle node persist the next TraCI update step? I would expect that it is getting removed by then as `BasicNodeManager` subscribes to the respective list of vehicle IDs.

**Comment by ruisonghan** [comment]
> Does the vehicle node persist the next TraCI update step? I would expect that it is getting removed by then as `BasicNodeManager` subscribes to the respective list of vehicle IDs.

I am not sure what will happen in the next TraCI step. My application and DENM application can both operate a vehicle by calling functions from ```VehicleController```. Maybe DENM tries to access the vehicle information after my application and that's where the problem is?

**Comment by riebl** [comment]
So Artery is crashing after calling TraCI's `remove` at the moment? Maybe I am missing your exact problem…
I am also confused about the motivation to remove a vehicle manually because it sounds quite violent ("You will be assimilated. Resistance is futile.").

**Comment by ruisonghan** [comment]
> So Artery is crashing after calling TraCI's `remove` at the moment? Maybe I am missing your exact problem…
> I am also confused about the motivation to remove a vehicle manually because it sounds quite violent ("You will be assimilated. Resistance is futile.").

Hi, Riebl

Sorry for the late reply. I want to remove a vehicle manually because I want to do some search in measuring how a vehicle can get away from a specific area after receiving some accident alerts from DENMs. Since SUMO and Artery just support giving edges or roads as destiantions, the time got from my simulation won't be accurate. 

For using the remove, the vehicle was removed in SUMO, and it did disappear. However, I could still see this vehicle node in OMNeT++. I guess this is because I didn't call a destructor to remove it and some other applications were also keeping checking the vehicle status at the same time step since these applications didn't have updates about this vehicle. I am not sure whether my guess is right or not.

BR

**Comment by riebl** [comment]
Two simple ideas worth trying before looking for a more complicated solution:
- remove the vehicle with another reason code (default is "vaporized"). Maybe "arrived" will play nicely with `BasicNodeManager`
- do not remove but move the vehicles out-of-the-way via TraCI's moveToXY. Please note that the the edge and lane id arguments are not strictly required
