### ISSUE TITLE
unaligned PER encoding of type CAM because of SpeedValue

### ISSUE THREAD

**Issue by ruisonghan** [riebl/artery#72]
Hi, everyone and Riebl

I found **a simulation problem related to the usage of SUMO (version 1.2.0)**. It is not a common problem but I will still share it here to prevent similar issues from happening. 

I randomly generated lots of scenarios to test my algorithms and unfortunately, **a car crash happened in one of my scenarios**.

The SUMO (v 1.2.0) showed the following information:
```bash
Warning: Teleporting vehicle 'flow58.0'; collision with vehicle 'flow53.0', lane='D6C6_0', gap=-4.49, time=10.50 stage=move.
Warning: Vehicle 'flow58.0' teleports beyond arrival edge 'D6C6', time 10.50.
...
** Event #1264128   t=10.638438170822   Elapsed: 68.5237s (1m 08s)  8% completed  (0% total)
     Speed:     ev/sec=18498.5   simsec/sec=0.170704   ev/simsec=108366
     Messages:  created: 1542015   present: 1848   in FES: 284
...
```
**Basically, a car (named "flow58.0" or node[59] or stationID "135497281") hit another car and has been removed by SUMO. Then, the problem came to OMNet++ and my simulation stopped.**

```bash
** Event #1267874   t=10.6623510106   Elapsed: 68.7196s (1m 08s)  8% completed  (0% total)
     Speed:     ev/sec=19115.7   simsec/sec=0.12172   ev/simsec=157047
     Messages:  created: 1546923   present: 2098   in FES: 385

<!> Error: std::runtime_error: Can't determine size for unaligned PER encoding of type CAM because of SpeedValue sub-type -- in module (artery::VehicleMiddleware) World.node[59].middleware (id=4329), at t=10.6623510106s, event #1267874
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
Run statistics: total 12, errors 1, skipped 11
```
By checking the SppedValue of this vehicle in CAM, **I found that a negative value was given to the CAMs from that vehicle, and this caused my problem.** 

```bash
Vehicle1632621729 speed: 803
Vehicle135497281 speed: -107374182400
```
**However, when using another laptop with SUMO v1.1.0, there is no such issue.** Thus, there could be some difference between these two versions of SUMO. When doing our simulation, we should consider the possible car crash issues (design your scenarios well) and the problems of removing vehicles from SUMO and OMNeT++.

PS:

When generating my scenarios, I used the default vehicles models. Besides, the topology of road networks is abstract and looks like a checkerboard. Vehicles have random positions and initial speed. I didn't pay much attention here since I put more focus on my algorithms. 

I don't know what happened in OMNeT++ after the vehicle was removed by SUMO. It seems that this vehicle sent another CAM message before it was removed in OMNeT++ and used the ```speedValue``` got from TraCI. 

Maybe there should be an order for executing the service CAM, DENM and our applications to make sure that when a vehicle is removed in SUMO, artery will know this and cancel the following operations (from CAM, DENM, etc.).

**Comment by riebl** [comment]
Thanks @ruisonghan for sharing this information!
It would be interesting to know if the FCD output of SUMO 1.2 also includes such insane speed values. Could you try to run SUMO with the `--fcd-output` option and check the generated log file?
Maybe this is simply a regression bug of SUMO.
Otherwise, we can only clamp SUMO speed values to the range supported by CAMs to avoid encoding errors.

**Comment by riebl** [comment]
@ruisonghan You can also try to set BasicNodeManager's destroyVehiclesOnCrash parameter to true. Teleported vehicles will then be removed from OMNeT++.

**Comment by ruisonghan** [comment]
I found the same issue in SUMO 1.0.1, and the way Riebl suggested does work.
