### ISSUE TITLE
Error make vanetza

### ISSUE THREAD

**Issue by enioprates** [riebl/artery#73]
Hello.
When I'm doing the make vanetza, I'm receiving an error:
[ 82%] Linking CXX shared library ../../lib/libvanetza_security.so
/usr/bin/ld: /usr/local/lib/libGeographic.a(Geodesic.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libGeographic.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Can someone help me with it?

**Comment by riebl** [comment]
You cannot link a static library (libGeographic.a) to a shared library (libvanetza_security.so) if former is not compiled with the "Position Independent Code" (PIC) option. I recommend you to compile GeographicLib as shared library.

**Comment by enioprates** [comment]
I already reinstalled the library as Shared, but the Vanetza keep looking for the static library (.a). There's a way to change this in Vanetza configuration?

**Comment by riebl** [comment]
Yes, you can explicitly set the CMake cache variable `GeographicLib_LIBRARY_RELEASE` to the shared library.

**Comment by enioprates** [comment]
Thanks for the help!
In my case, the solution was rebuild the vanetzza, but changing the CMakeLists:
option(BUILD_SHARED_LIBS "Build shared libraries" OFF) to 
option(BUILD_SHARED_LIBS "Build shared libraries" ON). 
Now it works. I don't know why the original file was off, but it works now.
