### ISSUE TITLE
CAMessage packet size

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#75]
Dear all,

Just a brief question, as CAMessages are very dependent on the amount of information the application chooses to send to them, their packet size can vary a lot... In Artery, are you able to provide me with a fixed value for this metric?

**Comment by riebl** [comment]
Artery's `CaService` generates CAMs of varying size as well, e.g. by adding the low frequency container from time to time.

**Comment by 1140464BV** [comment]
So, is there anyway for me to easily figure out when and with what size a packet was sent? I know timestamps of sent and received CAMs are being logged...

**Comment by riebl** [comment]
If you have a `CaObject` you can call `caobj.asn1().size()` to get its size in bytes. This size reflects only the length of the CAM. It does not include overhead by other protocols, e.g. BTP, GeoNetworking, Security, MAC framing etc.

Based on `CaObject` you can also add a `cObjectResultFilter` ("camLength"?) similar to already existing "camStationId" and "camGenerationDeltaTime" (see CaObject.cc).

**Comment by 1140464BV** [comment]
Is the packet size logged on omnet++'s GUI under the name "GeoNetPacket" the size of the full packet with all the stack headers included? (i.e 332 Bytes for a CAM without lowfreqContainer)

**Comment by riebl** [comment]
A `GeoNetPacket` is, as the name implies, a packet containing GeoNetworking headers and all upper layers. It does not account for 802.11 overhead.

**Comment by 1140464BV** [comment]
how many bytes does the 802.11 headers add up to those 332?

**Comment by riebl** [comment]
24 bytes 802.11 MAC header (QoS data) + 4 bytes FCS + 2 bytes for the EtherType at LLC (if EPD is used).
