### ISSUE TITLE
run_example

### ISSUE THREAD

**Issue by cuita85202** [riebl/artery#77]
Hey Riebl 

I want want to thank you for this awesome work. Sorry for reopening an issue about run_example but it seems that no body had this issue before.

I did build everything successfully except to run the existing example.
Here is the error message:

~/artery% cmake --build build --target run_example         
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
-- SimuLTE integration disabled
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   system
-- Enable Veins integration
-- Enable INET integration
-- pybind11 v2.2.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/veins/artery/build
Scanning dependencies of target traci
[  0%] Building CXX object src/traci/CMakeFiles/traci.dir/BasicNodeManager.cc.o
[  1%] Building CXX object src/traci/CMakeFiles/traci.dir/BasicSubscriptionManager.cc.o
[  1%] Building CXX object src/traci/CMakeFiles/traci.dir/Core.cc.o
[  2%] Linking CXX shared library libtraci.so
[ 18%] Built target traci
[ 19%] Building Vanetza (external dependency)
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
-- Cohda SDK not found (missing:  COHDA_ROOT) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/veins/artery/extern/vanetza/build
[  0%] Built target access
[ 63%] Built target asn1
[ 66%] Built target common
[ 70%] Built target net
[ 82%] Built target security
[ 87%] Built target dcc
[ 98%] Built target geonet
[ 99%] Built target btp
[100%] Built target facilities
[100%] Built target gnss
[100%] Built target proxy_fake_feed
[ 19%] Built target build_vanetza
[ 19%] Building INET (external dependency)
*** COMPILING with:
clang++ -c -std=c++11 -O3 -DNDEBUG=1 -MMD -MP -MF .d  -fPIC  -Wno-deprecated-register -Wno-unused-function -fno-stack-protector -DHAVE_SWAPCONTEXT -DWITH_MPI -DXMLPARSER=libxml -DPREFER_QTENV -DWITH_QTENV -DWITH_PARSIM -DWITH_NETBUILDER -DWITH_OSG -DWITH_OSGEARTH -Wno-overloaded-virtual  -DINET_EXPORT -I. -I/home/veins/src/omnetpp/include
*** LINKING with:
clang++ -shared -fPIC -o ../out/clang-release/src/libINET.so -Wl,--no-as-needed -Wl,--whole-archive  -Wl,--no-whole-archive -loppenvir -loppsim -ldl -lstdc++  -lOpenThreads -losg -losgText -losgDB -losgEarth -losgEarthUtil -Wl,-rpath,/home/veins/src/omnetpp/lib -Wl,-rpath,/lib -Wl,-rpath,.  -L/home/veins/src/omnetpp/lib
Building...
[ 19%] Built target build_inet
[ 20%] Building Veins (external dependency)
[ 20%] Built target build_veins
[ 20%] Generating artery/utility/AsioData
Scanning dependencies of target core
[ 21%] Building CXX object src/artery/CMakeFiles/core.dir/application/Middleware.cc.o
[ 22%] Building CXX object src/artery/CMakeFiles/core.dir/application/VehicleMiddleware.cc.o
[ 22%] Building CXX object src/artery/CMakeFiles/core.dir/networking/DccEntityBase.cc.o
[ 23%] Building CXX object src/artery/CMakeFiles/core.dir/networking/Router.cc.o
[ 24%] Building CXX object src/artery/CMakeFiles/core.dir/networking/SecurityEntity.cc.o
[ 24%] Building CXX object src/artery/CMakeFiles/core.dir/networking/StationaryPositionProvider.cc.o
[ 25%] Building CXX object src/artery/CMakeFiles/core.dir/networking/VehiclePositionProvider.cc.o
[ 25%] Building CXX object src/artery/CMakeFiles/core.dir/utility/AsioScheduler.cc.o
[ 26%] Building CXX object src/artery/CMakeFiles/core.dir/utility/AsioTask.cc.o
[ 27%] Building CXX object src/artery/CMakeFiles/core.dir/__/__/opp_messages/artery/utility/AsioData_m.cc.o
[ 28%] Building CXX object src/artery/CMakeFiles/core.dir/veins/VeinsRadioDriver.cc.o
[ 28%] Building CXX object src/artery/CMakeFiles/core.dir/inet/AntennaMobility.cc.o
[ 29%] Building CXX object src/artery/CMakeFiles/core.dir/inet/DistanceSwitchPathLoss.cc.o
[ 30%] Building CXX object src/artery/CMakeFiles/core.dir/inet/InetRadioDriver.cc.o
[ 31%] Building CXX object src/artery/CMakeFiles/core.dir/inet/InetMobility.cc.o
[ 31%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/LinkClassifier.cc.o
[ 32%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/NLOSb.cc.o
[ 34%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/NLOSf.cc.o
[ 35%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/NLOSv.cc.o
[ 35%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/ObstacleIndex.cc.o
[ 36%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/PathLoss.cc.o
[ 37%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/SmallScaleVariation.cc.o
[ 38%] Building CXX object src/artery/CMakeFiles/core.dir/inet/gemv2/VehicleIndex.cc.o
[ 39%] Building CXX object src/artery/CMakeFiles/core.dir/inet/VanetRx.cc.o
[ 40%] Linking CXX shared library libartery_core.so
[ 70%] Built target core
Scanning dependencies of target envmod
[ 70%] Building CXX object src/artery/envmod/CMakeFiles/envmod.dir/GlobalEnvironmentModel.cc.o
[ 71%] Building CXX object src/artery/envmod/CMakeFiles/envmod.dir/LocalEnvironmentModel.cc.o
[ 72%] Building CXX object src/artery/envmod/CMakeFiles/envmod.dir/sensor/BaseSensor.cc.o
[ 73%] Building CXX object src/artery/envmod/CMakeFiles/envmod.dir/sensor/CamSensor.cc.o
[ 74%] Linking CXX shared library libartery_envmod.so
[ 82%] Built target envmod
Scanning dependencies of target storyboard
[ 84%] Building CXX object src/artery/storyboard/CMakeFiles/storyboard.dir/Storyboard.cc.o
[ 84%] Linking CXX shared library libartery_storyboard.so
[100%] Built target storyboard
OMNeT++ Discrete Event Simulation  (C) 1992-2017 Andras Varga, OpenSim Ltd.
Version: 5.3, build: 180411-87513e3, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Qtenv...

Loading NED files from /home/veins/artery/src/artery: 
<!> Error: Could not load NED sources from '/home/veins/artery/src/artery': Syntax error, at /home/veins/artery/src/artery/networking/Vanetza.ned:27

End.
scenarios/artery/CMakeFiles/run_example.dir/build.make:57: recipe for target 'scenarios/artery/CMakeFiles/run_example' failed
make[3]: *** [scenarios/artery/CMakeFiles/run_example] Error 1
CMakeFiles/Makefile2:653: recipe for target 'scenarios/artery/CMakeFiles/run_example.dir/all' failed
make[2]: *** [scenarios/artery/CMakeFiles/run_example.dir/all] Error 2
CMakeFiles/Makefile2:660: recipe for target 'scenarios/artery/CMakeFiles/run_example.dir/rule' failed
make[1]: *** [scenarios/artery/CMakeFiles/run_example.dir/rule] Error 2
Makefile:285: recipe for target 'run_example' failed
make: *** [run_example] Error 2
zsh: exit 2     cmake --build build --target run_example

if you can help me with that.
Thank you

**Comment by riebl** [comment]
OMNeT++ 5.3 is not supported by Artery, please update to 5.4 (or 5.5, but this has not been tested yet).
