### ISSUE TITLE
Truncation of lat and long in DENMs

### ISSUE THREAD

**Issue by oslind** [riebl/artery#8]
https://github.com/riebl/artery/blob/99cacef54f435b142ffa343ceeb06c647d82f981/src/artery/application/DenmService.cc#L144

and

https://github.com/riebl/artery/blob/99cacef54f435b142ffa343ceeb06c647d82f981/src/artery/application/DenmService.cc#L145

does not do what they are supposed to do (convert the degrees to microdegrees). The longitude is simply multiplied by a factor of 10 by Longitude_oneMicrodegreeEast and the same goes for the latitude but since eventPosition.longitude  and the eventPosition.latitude in the management container are integers its this only results in a slightly more precise but still truncated coordinate.

**Comment by riebl** [comment]
You are absolutely right, this should not have happened. Fixed in https://github.com/riebl/artery/commit/f2cef344b6f9d1c471c23de52c8203a110fba719, thanks!
I thought boost::units::quantity would help me to prevent such conversion errors but it turned out to be a nightmare...
