### ISSUE TITLE
Is there any way to send CAM/DENM message using Ethernet?

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#80]
I am new to simulator and exploring to send CAM/DENM message using ethernet. 

In Storyboard example, CAM/DENM message are using Inet.linklayer.ieee80211. Can it be possible to send message via Ethernet protocol. I am refering VanetNic.ned file that is being used in example.
How to create ned file for Ethernet. What are the variables required in ned files. Any idea ?

**Comment by riebl** [comment]
I suggest to get familiar with the INET framework first and implement a custom `artery.nic.IRadioDriver` then. Though Ethernet is obviously not a wireless communication type, the radio driver is the component to adapt any kind of link layer.
