### ISSUE TITLE
Run highway-police example

### ISSUE THREAD

**Issue by casohite** [riebl/artery#81]
Hello

I can run the run_example by the floowing command: **cmake --build build --target run_example**

But if I want to run scenarios/highway-police example, how I can do?

thank you

**Comment by casohite** [comment]
I don't know what happen but now I have an error !

```
veins:~/artery/artery% cmake --build build --target run_example
[ 18%] Built target traci
[ 19%] Building Vanetza (external dependency)
make[4]: *** No rule to make target 'vanetza'.  Stop.
CMakeFiles/build_vanetza.dir/build.make:57: recipe for target 'CMakeFiles/build_vanetza' failed
make[3]: *** [CMakeFiles/build_vanetza] Error 2
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/build_vanetza.dir/all' failed
make[2]: *** [CMakeFiles/build_vanetza.dir/all] Error 2
CMakeFiles/Makefile2:665: recipe for target 'scenarios/artery/CMakeFiles/run_example.dir/rule' failed
make[1]: *** [scenarios/artery/CMakeFiles/run_example.dir/rule] Error 2
Makefile:285: recipe for target 'run_example' failed
make: *** [run_example] Error 2
zsh: exit 2     cmake --build build --target run_example
```

**Comment by casohite** [comment]
Hello,
Where can I found a documentation in order to develop my own scenario?
For example, how can I import map, add RSU/OBU, send CAM, send DENM, etc.
Thank you

**Comment by riebl** [comment]
`make run_highway_police`
There is not much documentation on how to create a scenario. Just have a look at the existing scenarios and adapt them to your needs.

Advertisement: [Recent Advances in Network Simulation](https://www.springer.com/de/book/9783030128418) includes a chapter where the highway_police scenario is created step by step.
