### ISSUE TITLE
Send CAM/DENM message via storyboard application to socktap-cam application

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#82]
Is there any way to send CAM/DENM message from storyboard test application to socktap-cam application?
I am trying to execute run_storyboard sample application and when it is triggering CAM/DENM message then it can be received by socktap-cam application.

**Comment by riebl** [comment]
That is possible but does not work out of the box. Artery's *testbed* feature demonstrates how an external radio device (in that case an USRP) can be used as gateway to a device-under-test (DUT). Such a DUT can be any compatible ITS device.
Integrating an implementation-under-test (IUT) such as *socktap-cam* is even possible without special hardware. Still, you will need to define an interface for the data exchange between IUT and the simulation environment.
