### ISSUE TITLE
GEMV2 assertion in vehile obstacle list

### ISSUE THREAD

**Issue by awillecke** [riebl/artery#84]
While testing scenarios for RSUs, I found a bug in the GEMV2 path loss model, which causes an assertion error.

It states:
```
ASSERT: Condition 'obs.size() > 2' does not hold in function 'computeMultipleKnifeEdge' at /*****/artery/src/artery/inet/gemv2/NLOSv.cc:152 -- in module (inet::physicallayer::Ieee80211Radio) World.node[1].wlan[0].radio (id=40), at t=27.024494955528s, event #132483
```

I've pushed the scenario on my fork of artery here:
awillecke@c2965760ae11c86b169e176fd1b4175215074e84

As far as I can tell the bug is located in here
https://github.com/riebl/artery/blob/5ed846e6bcd753c09aa2f7f8f1dc125f1453e67b/src/artery/inet/gemv2/NLOSv.cc#L77-L101
and is triggered, when the receiving node is located within outline of another obstructing vehicle.

In this case 
https://github.com/riebl/artery/blob/5ed846e6bcd753c09aa2f7f8f1dc125f1453e67b/src/artery/inet/gemv2/NLOSv.cc#L83
returns the list containing the obstructing vehicle, but 
https://github.com/riebl/artery/blob/5ed846e6bcd753c09aa2f7f8f1dc125f1453e67b/src/artery/inet/gemv2/NLOSv.cc#L89
returns an empty list, which causes the assertion error in
https://github.com/riebl/artery/blob/5ed846e6bcd753c09aa2f7f8f1dc125f1453e67b/src/artery/inet/gemv2/NLOSv.cc#L146

Somehow this all happens before the vehicle is destroyed by the core due to `destroyVehiclesOnCrash = true`.

**Comment by riebl** [comment]
@awillecke very interesting observations! Obviously, I had not enough imagination to foresee those corner cases. Issue is fixed in `master` branch.
