### ISSUE TITLE
Regarding LTE scenarios

### ISSUE THREAD

**Issue by 1140464BV** [riebl/artery#86]
Dear all,

Is there any documentation regarding the LTE related scenarios? I'm interested in the usage and analysis of vehicular scenarios using LTE-V2X instead of the "traditional" ETSI ITS-G5 settings.

**Comment by riebl** [comment]
Do you want to run IP-based applications over LTE or GeoNetworking on top of LTE?

**Comment by 1140464BV** [comment]
The idea would be to do something like the "car-2-car grid" scenario, however, using LTE settings instead of the default ones... Actually now I noticed the "rsu-grid" example, any possible informations regarding it as well?

**Comment by riebl** [comment]
At the moment, Artery services such as `CaService` cannot use LTE as radio technology. We are missing a `LteRadioDriver` implementation which couples SimuLTE radios and ETSI ITS stack. Hence, the LTE radio is only accessible by IP applications so far.

The "rsu-grid" scenario is a contribution by @awillecke (TU Braunschweig) with automated placing of RSUs. Not much to say about it with respect to LTE.

**Comment by 1140464BV** [comment]
So to use a similar service to CaService, I'm not able to test out LTE as the communication profile right?

In respect to, rsu-grid, what kind of messages are being sent by the RSU services?

**Comment by kenog** [comment]
You can configure the services running on the RSUs in the [rsuservices.xml](https://github.com/riebl/artery/blob/master/scenarios/rsu_grid/rsuservices.xml). What messages they send depends on the specific service. The `CaService` e.g., will send CAMs. But you can implement your own services transmitting your own messages.

**Comment by 1140464BV** [comment]
Already checked it, do you have anything published regarding this scenario with RSUs exchanging CAMs inbetween them and vehicles?

**Comment by kenog** [comment]
Not sure what you mean. You can use the existing code to do that, yes. Just enable the `CaService` on both vehicles and RSUs and you are done. But like @riebl said, you are restricted to CAMs sent via ITS-G5.

**Comment by 1140464BV** [comment]
Just a doubt regarding the behaviour of the CaService on the RSUs, is the payload information similar to the ones sent by vehicles?

**Comment by kenog** [comment]
After talking to @awillecke, I have to admit, that the `CaService` is currently not implemented for RSUs. General Information about RSU CAMs can be found in ETSI EN 302 637-2.

**Comment by riebl** [comment]
It should not be too hard to write a `CaRsuService` sending special RSU CAMs. Since a RSU is stationary by nature, one can omit those dynamic triggering conditions as well. In my opinion, those RSU CAMs make only sense when you are specifically interested in "protected communication zones" (reduced transmission power to play nice with toll stations).

**Comment by riebl** [comment]
For the record: We have nowadays a `RsuCaService` which generates CAMs that announce protected communication zones.
