### ISSUE TITLE
problem in understanding the flow of storybaord application

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#87]
We are trying to understand the flow of storyboard application and not able to understand the flow of sequence from sumo-gui to BasicNodeManager. 

We are trying to add new dynamic vehicle when we are receiving cam signal of obu that are not present in sumo. 

Please provide some guideline to understand the flow.

**Comment by riebl** [comment]
I think you are looking for `TraCIAPI::VehicleScope::add` which allows you to add vehicles on demand. `BasicNodeManager` will handle those manually added vehicles just as any other vehicle, no modifications are needed.
You can get an instance of `TraCIAPI::VehicleScope` via the `traci.Core` module: `core->getLiteAPI().vehicle()`

**Comment by ShilpiPhadnis** [comment]
Many thanks Riebl. Problem is solved. :)
