### ISSUE TITLE
Cannot resolve module type 'EtherPhy' (not in the loaded NED files?)

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [riebl/artery#88]
Hi 
I am using Omnet++ 5.4.1 version. I want to use Ethernet as physical layer to send CAMs and DENMs by running storyboard application in artery. For this purpose, I used " EtherPhy " in my World.ned file and also imported " inet.physicallayer.ethernet " into World.ned file. When I run storyboard application it is asking for confirmation like -
" **Submodule physicallayer: Cannot resolve module type 'EtherPhy' (not in the loaded NED files?), at /home/srilekha/Downloads/artery-final/src/artery/inet/World.ned:37 -- in module (omnetpp::cModule) World (id=1), during network setup** ".
After this confirmation, simulation is not running as expected. 
I have added the following piece of code under submodules into World.ned file - 

`physicallayer: EtherPhy {
            parameters:
                @display("i=block/rxtx");
        }
`

Here I am attaching you World.ned file where I made few changes. Please help me to proceed further.
[World.ned.tar.gz](https://github.com/riebl/artery/files/3724863/World.ned.tar.gz)

**Comment by riebl** [comment]
You need to import `import inet.physicallayer.ethernet.EtherPhy` otherwise OMNeT++ does not know where to look for the requested `EtherPhy` module.

**Comment by SrilekhaPavuluri** [comment]
Thank You, even after trying like that , it is showing - 
" **Class "inet::physicallayer::EtherPhy" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) World (id=1), during network setup** ". 
Do I have to add EtherPhy anywhere else ?

**Comment by riebl** [comment]
Please note that your issue is related to INET rather than Artery. Also, `EtherPhy` is only available since INET 4.1 but Artery's master is still using INET 3.6 to maintain compatibility with SimuLTE.
