### ISSUE TITLE
pointers not removed from LocalEnvironmentModel when vehicle exits simulation

### ISSUE THREAD

**Issue by EmilyBourne** [riebl/artery#9]
The following assertion fails when a vehicle exits the simulation

ASSERT: Condition '!obj_ptr.expired()' does not hold in function 'printSensorObjectList' at artery/src/artery/envmod/service/EnvmodPrinter.cc:41 -- in module (artery::EnvmodPrinter) World.node[2].middleware.artery.envmod.service.EnvmodPrinter (id=77), at t=257.989177300176s, event #12471810

**Comment by riebl** [comment]
Thank you for reporting this issue!
