### ISSUE TITLE
Issue: <!> Root privileges needed -- in module (inet::TcpSessionSocketApp) Socketethernet.client.app0, during network initialization

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#90]
Hi Riebl,
I am trying to create raw socket communication between two host. I have taken two standard host and connected both with Eth100M. I created two application TcpSessionSocketApp and TcpEchoSocketApp with base class a cSimpleModule and added configuration related to application in omnet.ini file.
During initialization of process it is failed to create socket communication:
<!> Root privileges needed -- in module (inet::TcpSessionSocketApp) Socketethernet.client.app0, during network initialization.

I tried to provide admin privileges to omnetpp, opp_run_dbg, opp_run_release, myapplication , TcpSessionSocketApp and TcpEchoSocketApp.

sudo setcap cap_net_admin,cap_net_raw=eip
(Not working)
after that I tried to give root access to all applications:
sudo chown root:root
(Not working)
afte that I provide admin privileges to my account:
useradd -m -G root
Still issue persist.

**Comment by riebl** [comment]
INET contains a readme regarding privilege settings for network emulation: https://github.com/inet-framework/inet/blob/master/examples/emulation/README
Artery's issue tracker is not the right plase to address INET problems, though.
