### ISSUE TITLE
Implement Ethernet socket layer instead of ieee80211 in storyboard application

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#91]
We are trying to implement ethernet interface instead of ieee80211 to execute storyboard application.
to change layer ieee80211 to ethernet we observed that below changes are required:
1. we need to implement EtherNic.ned file that will implement IEthernetInterface.
2. we have to update omnet.ini file to use EtherNic.ned file.
3. We have to do changes in InetRadioDriver.cc to change ieee80211Mac to EtherMac
4. We need to update world.ned file to update physical layer and LLC layer.

We need to understand the control flow of application from physical layer->mac layer -> LLC layer -> application layer.
Could you please provide basic sequence flow of application from one layer to another?

**Comment by riebl** [comment]
Physical, medium access and link layer are entirely handled by INET, nothing special here from Artery's perspective.
`artery.inet.InetRadioDriver` adapts the NIC provided by INET. Such a radio driver communicates with the Vanetza module, which deals with the ITS-G5 protocols. Application layer, e.g. CA and DEN messages, are handled by services attached to the middleware. The middleware is connected to the Vanetza ITS-G5 stack.

**Comment by ShilpiPhadnis** [comment]
Thanks Riebl for your reply. 
I tried to change the layer and did changes in below files:
1. storyboard application omnet.ini file:
2. InetRadioDriver.cc, .h and .ned file
3. Instead of world.ned, we created new file EtherWorld.ned file
4. Instead of vanetNic.ned, we created new file EtherNic.ned file.
5. Changes done in Car.ned file. 
We are receiving segmentation fault after did all changes. 
Could you please check why we are facing this issue.
Please find my changes attached.
[EthernetRelatedChanges.tar.gz](https://github.com/riebl/artery/files/3787119/EthernetRelatedChanges.tar.gz)

What I observed is that  it is getting crashed before launching sumo-gui.

**Comment by riebl** [comment]
Please push your changes to a git repository if you want me to have a closer look at your code. Handling tarballs manually is far too cumbersome.

**Comment by riebl** [comment]
continued in #96
