### ISSUE TITLE
Creating and adding own ITS-G5 service into scenario

### ISSUE THREAD

**Issue by mattherbert1** [riebl/artery#93]
Dear Riebl and Everyone,

I would like to implement my own ITS-G5 service and add it to a scenario, namely to car2car-grid. I am  a beginner with the framework and my question would be that what steps should I take to add my own implemented service successfully to the scenario? How should I modify the CMake files if it is necessary. 

Thank you in advance,
 mattherbert1

Edit: I forgot one more thing. I have an ASN.1 file which I would use to represent the message that this service should use. How can I integrate it into Artery using asn1c?

**Comment by riebl** [comment]
Hi @mattherbert1,

general-purpose ITS-G5 services are usually located in `src/artery/application`. However, this is no strict requirement. For example, the `PoliceService` is located in `scenarios/highway-police` as it specifically designed for this particular scenario. Please add your service's source file to `src/artery/CMakeLists.txt` just as its sibling source files.
The middleware module of V2X vehicles reads a service description file, usually named `services.xml`. During initialisation, therein specified services are attached to the hosting vehicle.

I suggest to add the code generated by asn1c to a subdirectory, e.g. `src/artery/application/<your_service_name>`. Add those source files to `CMakeLists.txt` as well. Decide on your own if you want to add them to `src/artery/CMakeLists.txt` or use CMake's `add_subdirectory`. You will only need the code representing your particular message but not the additional asn1c support code, e.g. `constr_*.{h,c}`, `*_decoder.{h,c}`, `*_encoder.{h,c}` etc. as those are already shipped by Vanetza.

**Comment by riebl** [comment]
According to @mattherbert1's comment in #97, this issue is solved.
