### ISSUE TITLE
UnicastForwarding NextHop

### ISSUE THREAD

**Issue by fehlfarbe** [riebl/artery#94]
Hi,
I want to test a different `itsGnNonAreaForwardingAlgorithm` that selects a neighbour from the location table and forwards the message to this neighbour (like Greedy forwarding).
So I added the new algorithm in `forwarding_algorithm_selection` that returns a `NextHop` object with a valid MAC address. But the router of the NextHop never receives the forwarded message. It only works with `cBroadcastMacAddress` (that's why CBF is working).

Is this a bug or do I miss something?

**Comment by riebl** [comment]
Is the sending router setting the correct/expected MAC address in its `NextHop` result?
Either your routing algorithm is not working correctly or there is some issue in Artery with unicast frames. From my point of view, I hope it's the former ;-)

**Comment by fehlfarbe** [comment]
Hi,
at the moment I'm just looking for the nearest neighbour in the table and write the packet and MAC address to NextHop object:

```
    MacAddress next_addr;
    GeodeticPosition dest = packet.pdu().extended().position();
    const units::Length own = distance(dest, m_local_position_vector.position());
    units::Length mfr_dist = own;
    for(const LocationTableEntry& b : m_location_table.neighbours()){
        if(b.is_neighbour() && (m_local_position_vector.timestamp - b.get_position_vector().timestamp).value() < 1000) {
            units::Length dist = distance(b.get_position_vector().position(), m_local_position_vector.position());
            if(dist < mfr_dist){
                next_addr = b.link_layer_address();
                mfr_dist = dist;
            }
        }
    }
    nh.transmit(std::move(packet), next_addr);
    return nh;
```

I also added a print to `void Router::pass_down(const MacAddress&, PduPtr, DownPacketPtr)`

```
if(request.destination != cBroadcastMacAddress) {
    std::cout << "passing down request " << request.source << " to " << request.destination << std::endl;
}
```
That says: `passing down request 00:00:00:00:00:00 to 00:00:00:02:00:00`

**Comment by riebl** [comment]
Can you share your changes with me via on git branch? Then I could have a closer look at it and try to determine what is going wrong there.

**Comment by fehlfarbe** [comment]
Thanks! :)

Here are the changes of my Vanetza fork: https://github.com/fehlfarbe/vanetza/commit/a117a08f0bc73598f4fb3bb32079edd2d8e51e78
You can ignore most of the stuff in `itsGnNonAreaForwardingAlgorithm`. I'm convertig the ego and neighbour position vectors to JSON and send it to an external tool that does the routing decision. But at the moment NextHop is selected by these lines: https://github.com/fehlfarbe/vanetza/commit/a117a08f0bc73598f4fb3bb32079edd2d8e51e78#diff-0e230d8e58962c962186b617741e333aR972-R988

And this is my current Artery branch: https://github.com/fehlfarbe/artery/tree/gbc_forwarding

**Comment by riebl** [comment]
There was a bug in Artery's `VeinsRadioDriver` related to reporting the MAC address used by Veins. This is fixed now in the master branch.
Thanks for your help in tracking down this issue!

By the way, unicast frames have been processed correctly with the INET radio model already, i.e. the "inet" configuration in your scenario.
