### ISSUE TITLE
Ethernet related issue

### ISSUE THREAD

**Issue by SahilKelkar** [riebl/artery#96]
Hi Riebl,
We are trying to implement ethernet layer instead of ieee80211 for storyboard application.
I have uploaded my changes in below repository.
https://github.com/SahilKelkar/artery

current issue that we are facing is 
<!> Submodule wlan: Cannot resolve module interface 'EthernetInterface', at artery_inet4/artery/src/artery/inet/Car.ned:35 -- in module (omnetpp::cModule) EtherWorld.node0, at t=0.1s, event #2

Kindly check if we have done implementation in correct way ?

**Comment by SahilKelkar** [comment]
Dear Riebl,
 Kindly check the code once as we are not clear why it is not taken EthernetInterface.

**Comment by riebl** [comment]
First of all, your branch does not even compile.
I also see no reason why you have removed the mobility submodule from `artery/inet/Car.ned`.
Please have a look at INET's examples that show usage of Ethernet NICs. You will need to wire all your cars up someway since they are not wireless anymore. Maybe replacing the `EthernetInterface` (named "EthernetMedium") in your `EtherWorld` by an `EtherSwitch` would be first step in the right direction.
It is a little bit hard for me to understand why you want Ethernet at all for inter-vehicle communication, but of course you can do in simulation whatever you want to.

**Comment by SahilKelkar** [comment]
Hi Riebl,
_First of all, your branch does not even compile._

I pushed my changes. Kindly check and confirm if you are able to compile it now.
_I also see no reason why you have removed the mobility submodule from artery/inet/Car.ned._
antennaMobility is applicable for RF only. Ethernet is RJ 45 cable which is connected to another machine directly hence no RF is there
_Please have a look at INET's examples that show usage of Ethernet NICs. You will need to wire all your cars up someway since they are not wireless anymore. Maybe replacing the EthernetInterface (named "EthernetMedium") in your EtherWorld by an EtherSwitch would be first step in the right direction._
I am not clear with EtherSwitch part. Kindly explain the same.
_It is a little bit hard for me to understand why you want Ethernet at all for inter-vehicle communication, but of course you can do in simulation whatever you want to._
We are using simulator for pc environment and communication is done via Ethernet only.

**Comment by riebl** [comment]
I understand that you don't need *antennaMobility* but *mobility* is actually dealing with car's position itself.
Please be aware that the simulated network technology is independent of any wiring in your computer setup. For example, it is perfectly fine to have virtual wireless NIC capturing over-the-air packets and forwarding those over a real network connection. Maybe something similar to `artery.testbed.TestbedCar` is what you are looking for?

**Comment by ShilpiPhadnis** [comment]
Dear Riebl,
I have checked in my code in below repository:
https://github.com/SahilKelkar/artery/tree/inet4

Changes includes:
1. Changes done in InetRadioDriver to implement Ethernet MAC.
2. Standard host modification.
3. Connections are done middleware <->vanetza<->InetRadioDriver<->modStdHost<->EtherSwitch in car.ned and EtherWorld.ned file.
4. Changes done in omnet.ini in storyboard application.

We are quite confused how cars should be connected with Switch. 
As of now we are receiving error :
getting this error -> Submodule wlan: 'inet.node.inet.StandardHostEx' is not a module interface, at /home/pooja/Downloads/artery-inet4/src/artery/inet/Car.ned:37 -- in module (omnetpp::cModule) EtherWorld.node0, at t=0.1s, event #2 

We are not sure how lowerLayer should be connected with EtherSwitch.

Kindly check the changes we have done and provide suggestion.

**Comment by SahilKelkar** [comment]
Dear Riebl,
I have checked in my code in below repository:
https://github.com/SahilKelkar/artery/tree/inet4

Changes includes:

Changes done in InetRadioDriver to implement Ethernet MAC.
Standard host modification.
Connections are done middleware <->vanetza<->InetRadioDriver<->modStdHost<->EtherSwitch in car.ned and EtherWorld.ned file.
Changes done in omnet.ini in storyboard application.
We are quite confused how cars should be connected with Switch.
As of now we are receiving error :
getting this error -> Submodule wlan: 'inet.node.inet.StandardHostEx' is not a module interface, at /home/pooja/Downloads/artery-inet4/src/artery/inet/Car.ned:37 -- in module (omnetpp::cModule) EtherWorld.node0, at t=0.1s, event #2

We are not sure how lowerLayer should be connected with EtherSwitch.

Kindly check the changes we have done and provide suggestion.

**Comment by riebl** [comment]
Sorry, I don't have the time to go into details. Please refer to INET's examples and tutorials regarding usage of their Ethernet modules.
Also, this is not really an Artery issue so I am closing this ticket.

**Comment by SahilKelkar** [comment]
Dear Riebl,
We are able to fixed above issue and update code is also checked in:
https://github.com/SahilKelkar/artery/tree/inet4

We are facing one issue 
 Module can not cast to 'inet::EtherMac'
on path '.wlan[0].eth[0].mac' defined by par 'EtherWorld.node[0].radioDriver[0].macModule' --
in module (artery::InetRadioDriver) EtherWorld.node[0].radioDriver[0] (id=18), at t=0.1s, event #2

Changes done by us : 
 In Car.ned, wlan is changed to StandardHost and all the required parameters and properties are set in wlan of Car.ned only
" wlan: StandardHostEx {
parameters:
@display(p=250,400,row,100;q=queue);
mac.typename = EtherMac;
encap.typename = EtherEncap;

            mac.csmacdSupport = true;
            mac.address = "auto";
            mac.promiscuous= true;
            mac.duplexMode = true;

            mac.fcsMode= "declared";

            *.interfaceTableModule = default(absPath(".interfaceTable"));

            mac.txQueueLimit= 1000;
            mac.queueModule= "";

            //EtherEncap
            numEthInterfaces = default(0);

            *.macTableModule = default(absPath(".macTable"));

            //encap.fcsMode = "computed";

            //Ipv4
            ipv4.crcMode= "declared";
        *.configurator.networkConfiguratorModule = "";

            forwarding = false;
            multicastForwarding = false;

            *.routingTableModule = default(absPath(".ipv4.routingTable"));
            *.arpModule = default(absPath(".arp"));
            *.icmpModule = default(absPath(".icmp"));

            //Tcp
            tcp.crcMode = "declared";
    } "

Following changes are made in InetRadioDriver.cc -
Changed the line mLinkLayer = inet::findModuleFromPar(par(macModule), host);
to ' mLinkLayer = inet::findModuleFromParinet::EtherMac(par(macModule), host); '
Ieee80211Mac has been changed to EtherMac.
4) Following changes are made in InetRadioDriver.h -
Changed the line inet::Ieee80211Mac* mLinkLayer = nullptr; to inet::EtherMac* mLinkLayer = nullptr;

Seems findModuleFromPar is failed to get the EtherMac data. Kindly check and let us know what changes are required to fix this issue.
