### ISSUE TITLE
Filling a SEQUENCE OF asn.1 type with data

### ISSUE THREAD

**Issue by mattherbert1** [riebl/artery#97]
Dear Riebl,

First of all, thank you for your reply to issue #93 , I was managed to insert my compiled asn code into the framework. Now I am facing the issue that my message also has a SEQUENCE OF type container (like the pathHistory field in CAM) that I would like to fill with data. Could you tell me a safe way to do this even through using CAM/CaService as an example?

Thank you in advance again,
mattherbert1

**Comment by riebl** [comment]
Dear @mattherbert1,

I have just modified the `CaService` to fill CAM's PathHistory with some mock points. This should demonstrate the asn1c API for SEQUENCE OF types sufficiently though the data itself is not sensible.
However, I am not sure if you consider this "safe" ;-)

**Comment by mattherbert1** [comment]
Dear Riebl,

I have just checked out your implementation, thank you for the quick response on Sunday. I wanted to express with word "safe" that I would like to avoid memory leak, and I was not sure that the framework would free my dynamically allocated data.

**Comment by riebl** [comment]
Yes, allocated memory of optional and list-like data structures is freed when the containing data structure is freed. That's the whole purpose of `vanetza::asn1::asn1c_wrapper` (and its `vanetza::asn1::Cam` derivative): Avoiding memory leaks and making life with asn1c a little bit easier.
