### ISSUE TITLE
Connection of vanetza to StandardHost

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#98]
Hi Riebl,

We are trying to modify Standardhost so that it can be connected to Vanetza application. Is there any way to do the same ?

**Comment by riebl** [comment]
I am sorry, I do not understand your question. What do you mean by "Vanetza application"?

**Comment by ShilpiPhadnis** [comment]
As per our understanding RadioDriver upperLayer gates are connected with Vanetza and lowerLayer gater are connected with Ieee802Interface (llc -> mac -> radio).
Instead of RadioDriver can we use StandardHost so that its upperLayer will connect with vanetza and other layers are already handled in StandardHost.
Kindly confirm it is possible or not ?

**Comment by riebl** [comment]
`artery.networking.Vanetza`, the OMNeT++ module integrating Vanetza, requires a partnering `artery.nic.IRadioDriver` implementation. Currently, Artery ships with an implementation for INET's IEEE 802.11 NIC and one for Veins' NIC.
Despite its name, a radio driver does not need a wireless interface. By providing a "StandardHostDriver" you may couple Vanetza with a StandardHost then.

**Comment by ShilpiPhadnis** [comment]
Dear Riebl,
Thanks for your reply.
As per our understanding below are the connections for Ieee80211:
middleware <->vanetza<->InetRadioDriver<->802.11mac/llc/phy

For ethernet connection, we have understanding that 
1. We have to modify standard host:  Add upperlayergate and remove IApp.
2. UpperLayer gate of Standard host is connected to InetRadioDriver and lower layer of Standard host i.e IEthernetInterface is connected with EtherSwitch.
middleware <->vanetza<->InetRadioDriver<->modStdHost<->switch

Kindly confirm that our understanding in terms of Ethernet is correct or we can take another module to fulfill our requirement instead of updating StandardHost?

**Comment by riebl** [comment]
Yes, your illustration of the interconnected components for 802.11 hosts looks correct.
I cannot tell if `StandardHost` is a suitable starting point for whatever you are trying to achieve. `InetRadioDriver` requires INET 802.11 NICs, it won't work out-of-the-box with other INET NICs.
And yes, you will need some "virtual cabling" between simulated hosts, e.g. connect them to a global Ethernet switch module. This replaces the `RadioMedium` then.

**Comment by ShilpiPhadnis** [comment]
Dear Riebl,
As per our requirement do you have any other to solve our issue instead of Standard Host ? 
Regarding InetRadioDriver, what needs to be done to ensure that InetRadioDriver works with standardhost.
My understanding is that during initialization we have to take macModule as EtherMac and not sure about RadioDriveProperties. Can we remove this property? 
I believe some changes are required in receiveSignal()

**Comment by ShilpiPhadnis** [comment]
Dear Riebl,

Kindly confirm our understanding is correct in terms of InetRadioDriver

**Comment by riebl** [comment]
Yes, your radio driver implementation will need to interact with the Ethernet MAC. `RadioDriverProperties` are required to inform upper layers about the MAC link layer address. You can use a fake channel number, however.
I see no need to emit channel load signals for an `EthernetRadioDriver`.

**Comment by riebl** [comment]
Continued in #96
