### ISSUE TITLE
Error while executing make veins and make inet in artery directory

### ISSUE THREAD

**Issue by palash1794** [riebl/artery#99]
Hey! I was installing artery setup in my ubuntu 16.04 virtual machine and after trying multiple times this error pops up while I run **make veins** and **make inet** command in terminal window in artery directory.
**palash@palash-VirtualBox:~/artery$** make veins
cd extern/veins; python2 configure
env: ‘opp_makemake’: No such file or directory
Traceback (most recent call last):
  File "configure", line 47, in <module>
    subprocess.check_call(['env', 'opp_makemake'] + makemake_flags, cwd='src')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env', 'opp_makemake', '-f', '--deep', '--no-deep-includes', '--make-so', '-I', '.', '-o', 'veins', '-O', 'out']' returned non-zero exit status 127
Makefile:34: recipe for target 'extern/veins/src/Makefile' failed
make: *** [extern/veins/src/Makefile] Error **

**palash@palash-VirtualBox:~/artery$ make inet
make -C extern/inet makefiles
make[1]: Entering directory '/home/palash/artery/extern/inet'
/bin/sh: 1: opp_makemake: not found
Makefile:21: recipe for target 'makefiles-so' failed
make[1]: *** [makefiles-so] Error 127
make[1]: Leaving directory '/home/palash/artery/extern/inet'
Makefile:21: recipe for target 'extern/inet/src/Makefile' failed
make: *** [extern/inet/src/Makefile] Error 2
**
Please let me know where is the issue
I have currently installed python 2.7.12 version

**Comment by kenog** [comment]
Did you install Omnet++ beforehand? You need to install it and add its `bin` directory to your `PATH`.

**Comment by palash1794** [comment]
yes I have already downloaded omnet++5.4.1 and configured it.I have also add the path to it's bin directory

**Comment by riebl** [comment]
Still, something is not right with your `PATH` environment variable. Otherwise, the executed script would find `opp_makemake` which is located in OMNeT++'s `bin` directory. Please assure that `opp_makemake` can be run from your shell.

**Comment by palash1794** [comment]
okay I will make sure I have added the correct path and check it again.

**Comment by palash1794** [comment]
Thanks I was able to complete installation setup completely,after I changed the path in bin!

**Comment by VasiKydo** [comment]
Hello! I have the same problem with opp_makemake.

vaso@vaso:~/Veins_lte_project/veins-lte-master$ make makefiles
make -C inet makefiles
make[1]: Entering directory '/home/vaso/Veins_lte_project/veins-lte-master/inet'
cd src && opp_makemake -f --deep --make-so -o inet -O out -pINET -Xapplications/voipstream -Xtransport/tcp_lwip -Xtransport/tcp_nsc -DWITH_TCP_COMMON -DWITH_TCP_INET -DWITH_IPv4 -DWITH_IPv6 -DWITH_xMIPv6 -DWITH_UDP -DWITH_RTP -DWITH_SCTP -DWITH_DHCP -DWITH_ETHERNET -DWITH_PPP -DWITH_EXT_IF -DWITH_MPLS -DWITH_OSPFv2 -DWITH_BGPv4 -DWITH_TRACI -DWITH_MANET
/bin/sh: 1: opp_makemake: not found
Makefile:13: recipe for target 'makefiles' failed
make[1]: *** [makefiles] Error 127
make[1]: Leaving directory '/home/vaso/Veins_lte_project/veins-lte-master/inet'
Makefile:9: recipe for target 'makefiles' failed
make: *** [makefiles] Error 2

I have read all the comments but I don't understand how to add the right path. Any help please?
